/* KELO-INDEX
 * area: ENVIRONMENT / WORLD
 * owner: KELO_WORLD_RENDERER
 * keys: WORLD CHUNK CULL LRU DISTRICT ATLAS LAZY WARM EVICT GARDENS PERFORMANCE CAMERA
 * purpose: renderer data-driven por chunks; solo mantiene assets district visibles y cache LRU limitada
 * public-api: KELO_WORLD_RENDERER.draw/districts/chunkSize/ready/performanceSnapshot
 * consumes: KeloCamera, KELO_TERRAIN_CONTRACT, KELO_ATLAS_CONTRACT, KELO_MOBILE_PERFORMANCE_CONTRACT, tile registry
 * state-owned: cache de chunks y referencias de atlas que el WorldRenderer está usando ahora
 * extension-points: terrain profiles/district visual profiles/atlas contract
 * reuse: nuevos distritos deben declarar assets por contratos, no crear loaders paralelos
 * online: N/A; presentación local del mundo
 * do-not: NO crear Image directamente, NO recorrer mundo completo por frame, NO cache sin límite
 */
(function(){
'use strict';
const R=window.KELO_TILE_REGISTRY,TERRAIN=window.KELO_TERRAIN_CONTRACT,G=window.KELO_GARDENS_ATLAS,J=window.KELO_GARDENS_JOINS,A=window.KELO_ATLAS_CONTRACT,P=window.KELO_MOBILE_PERFORMANCE_CONTRACT,CAM=window.KeloCamera;
if(!R?.atlases||!R?.families||!TERRAIN?.materials||!TERRAIN?.transitions||!TERRAIN?.districts||!G||!J||!A?.acquire||!A?.release||!P?.budgets||!CAM?.worldView){console.error('[Kelo world] registry, terrain/district contract, gardens atlases, atlas contract, mobile performance contract or KeloCamera.worldView missing');return;}
const TILE=R.worldTileSize||32,CHUNK=512,F=R.families,cache=new Map(),MAX=Math.max(4,Number(P.budgets.chunkCacheCap)||24),CULL_MARGIN=Math.max(0,Number(P.budgets.chunkCullMarginChunks)||1);
let gardenImg=null,gardenJoinImg=null,terrainReady=false,gardenReady=false,gardenJoinReady=false,ready=false,gardenWanted=false,gardenHeld=false,gardenLoadPromise=null,gardenLoadGeneration=0,gardenAcquireCount=0,gardenReleaseCount=0,chunkBuildCount=0,chunkHitCount=0,chunkEvictionCount=0;
const DISTRICTS=TERRAIN.districts,GARDEN_DISTRICT=DISTRICTS.find(d=>d.id==='gardens')||null;
const ROADS=Object.freeze([{x:384,y:1408,w:800,h:64},{x:1088,y:1408,w:96,h:160},{x:1088,y:1488,w:1792,h:96},{x:1376,y:384,w:128,h:2500},{x:1376,y:736,w:1120,h:128},{x:1376,y:2304,w:640,h:128}]);
const PADS=Object.freeze([{x:1888,y:1424,w:512,h:288},{x:1792,y:640,w:608,h:256}]);
const GARDEN_PATHS=Object.freeze([{x:1216,y:2304,w:160,h:64},{x:1504,y:2304,w:192,h:64},{x:1248,y:2368,w:64,h:192},{x:1600,y:2368,w:64,h:160},{x:1216,y:2528,w:128,h:96},{x:1568,y:2496,w:128,h:96},{x:1664,y:2432,w:32,h:64}]);
const GARDEN_PATH_CUTS=Object.freeze([{x:1216,y:2528,w:32,h:32},{x:1312,y:2528,w:32,h:32},{x:1216,y:2592,w:32,h:32},{x:1312,y:2592,w:32,h:32},{x:1568,y:2496,w:32,h:32},{x:1664,y:2496,w:32,h:32},{x:1568,y:2560,w:32,h:32},{x:1664,y:2560,w:32,h:32}]);
function inside(x,y,r){return x>=r.x&&y>=r.y&&x<r.x+r.w&&y<r.y+r.h;}
function intersects(a,b){return !!(a&&b&&a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y);}
function gardenPath(x,y){return GARDEN_PATHS.some(r=>inside(x,y,r))&&!GARDEN_PATH_CUTS.some(r=>inside(x,y,r));}
function road(x,y){return ROADS.some(r=>inside(x,y,r))||PADS.some(r=>inside(x,y,r))||gardenPath(x,y);}
function district(x,y){return TERRAIN.districtForPoint?.(x,y)||DISTRICTS.find(d=>inside(x,y,d))||null;}
function profile(x,y){return TERRAIN.profileFor(district(x,y)?.id);}
function terrainAt(x,y){const p=profile(x,y);return road(x,y)?p.pathTerrain:p.baseTerrain;}
function hash(x,y,s=0){return Math.abs(((x+17+s)*73856093)^((y+29+s)*19349663));}
function pick(x,y,l){return l[hash(x,y)%l.length];}
function terrainAtlasKeys(){const keys=new Set();for(const def of Object.values(TERRAIN.materials)){if(def.atlas)keys.add(def.atlas);if(def.detailAtlas)keys.add(def.detailAtlas);}for(const set of Object.values(TERRAIN.transitions))if(set.atlas)keys.add(set.atlas);return Object.freeze([...keys]);}
const TERRAIN_ATLAS_KEYS=terrainAtlasKeys(),ATLAS_IMAGES=Object.create(null);
for(const key of TERRAIN_ATLAS_KEYS){const atlas=R.atlases[key],managed=A.describe(key);if(!atlas||!managed){console.error('[Kelo world] terrain contract references unmanaged atlas',key);return;}ATLAS_IMAGES[key]={image:null,atlas,ready:false};}
if(!A.describe('gardensBase')||!A.describe('gardensJoins')){console.error('[Kelo world] gardens atlases are not registered in Atlas Contract');return;}
function atlasOrigin(atlas,id){const cols=atlas.columns||Math.floor(atlas.width/TILE);return{x:(id%cols)*TILE,y:Math.floor(id/cols)*TILE};}
function drawAtlasTile(g,atlasKey,id,x,y){const entry=ATLAS_IMAGES[atlasKey];if(!entry?.ready||!entry.image||id==null)return false;const p=atlasOrigin(entry.atlas,id);g.drawImage(entry.image,p.x,p.y,TILE,TILE,x,y,TILE,TILE);return true;}
function materialPool(def,profileDef,X,Y){const base=F[def.family]||[];if(!base.length)return base;if(profileDef.detailCluster&&Array.isArray(def.variationGroups)&&def.variationGroups.length){const macroX=Math.floor(X/3),macroY=Math.floor(Y/3),group=hash(macroX,macroY,131)%7===0?1:0;return def.variationGroups[Math.min(group,def.variationGroups.length-1)]||base;}return base;}
function drawMaterial(g,key,X,Y,dx,dy,profileDef){const def=TERRAIN.materials[key];if(!def)return false;const pool=materialPool(def,profileDef,X,Y);if(!pool.length)return false;let id=pick(X,Y,pool);if(profileDef.pathAccentEvery&&def.accentFamily&&F[def.accentFamily]?.length&&hash(X,Y,11)%profileDef.pathAccentEvery===0)id=pick(X+3,Y+7,F[def.accentFamily]);drawAtlasTile(g,def.atlas,id,dx,dy);if(profileDef.pathDetail&&def.detailAtlas&&def.detailFamily&&F[def.detailFamily]?.length){const detailId=pick(X+13,Y+5,F[def.detailFamily]);drawAtlasTile(g,def.detailAtlas,detailId,dx,dy);}return true;}
const SIDE_STEPS=Object.freeze([{bit:TERRAIN.sideBits.top,dx:0,dy:-TILE},{bit:TERRAIN.sideBits.right,dx:TILE,dy:0},{bit:TERRAIN.sideBits.bottom,dx:0,dy:TILE},{bit:TERRAIN.sideBits.left,dx:-TILE,dy:0}]);
function transitionMask(wx,wy,set){let mask=0;for(const side of SIDE_STEPS)if(terrainAt(wx+TILE/2+side.dx,wy+TILE/2+side.dy)===set.neighbour)mask|=side.bit;return mask;}
function drawTerrainTransitions(g,materialKey,wx,wy,dx,dy){for(const set of Object.values(TERRAIN.transitions)){if(set.owner!==materialKey)continue;const mask=transitionMask(wx,wy,set);if(!mask)continue;const frame=TERRAIN.frameFor(set.owner,set.neighbour,mask);if(frame!=null)drawAtlasTile(g,set.atlas,frame,dx,dy);}}
function gardenOrigin(id){return{x:(id%G.columns)*TILE,y:Math.floor(id/G.columns)*TILE};}
function gardenJoinOrigin(id){return{x:(id%J.columns)*TILE,y:Math.floor(id/J.columns)*TILE};}
function drawGarden(g,id,x,y){if(!gardenImg)return;const p=gardenOrigin(id);g.drawImage(gardenImg,p.x,p.y,TILE,TILE,x,y,TILE,TILE);}
function drawGardenRotated(g,id,x,y,turns=0){if(!gardenImg)return;const p=gardenOrigin(id),q=((turns%4)+4)%4;if(!q){g.drawImage(gardenImg,p.x,p.y,TILE,TILE,x,y,TILE,TILE);return;}g.save();g.translate(x+TILE/2,y+TILE/2);g.rotate(q*Math.PI/2);g.drawImage(gardenImg,p.x,p.y,TILE,TILE,-TILE/2,-TILE/2,TILE,TILE);g.restore();}
function drawGardenJoin(g,id,x,y){if(!gardenJoinImg)return;const p=gardenJoinOrigin(id);g.drawImage(gardenJoinImg,p.x,p.y,TILE,TILE,x,y,TILE,TILE);}
const GT=G.tiles,JT=J.tiles,GC=R.styles?.gardensCompositions||null,GCM=new Map();
function registerGardenCell(cell){const baseId=GT[cell[2]],joinId=JT[cell[2]],turns=cell[3];if(baseId!=null)GCM.set(cell[0]+','+cell[1],{atlas:'base',id:baseId,...(turns!=null?{turns}:{})});else if(joinId!=null)GCM.set(cell[0]+','+cell[1],{atlas:'join',id:joinId});}
for(const comp of GC?.compositions||[])for(const cell of comp.cells||[])registerGardenCell(cell);for(const cell of GC?.fixedPlacements||[])registerGardenCell(cell);
function gardenOverlay(X,Y){const lx=X-33,ly=Y-67;if(lx<0||ly<0||lx>=28||ly>=22)return null;if(lx>=20&&lx<=24&&ly>=9&&ly<=12)return null;const k=lx+','+ly;if(GCM.has(k))return GCM.get(k);if(hash(lx,ly,77)%29===0)return{atlas:'base',id:GT.FLOWER_TUFT};return null;}
const TILE_OVERLAY_PROVIDERS=Object.freeze({'garden-compositions-v1':gardenOverlay});
function drawTileOverlay(g,visualProfile,terrainProfile,materialKey,X,Y,dx,dy){const providerId=visualProfile?.tileOverlayProvider;if(!providerId||materialKey!==terrainProfile.baseTerrain)return;const provider=TILE_OVERLAY_PROVIDERS[providerId];if(!provider)return;const ov=provider(X,Y);if(ov?.atlas==='join')drawGardenJoin(g,ov.id,dx,dy);else if(ov?.atlas==='base'&&ov.turns!=null)drawGardenRotated(g,ov.id,dx,dy,ov.turns);else if(ov?.atlas==='base')drawGarden(g,ov.id,dx,dy);}
function reportCache(){if(!window.KELO_WORLD_AUDIT)return;window.KELO_WORLD_AUDIT.chunkCacheSize=cache.size;window.KELO_WORLD_AUDIT.chunkBuildCount=chunkBuildCount;window.KELO_WORLD_AUDIT.chunkHitCount=chunkHitCount;window.KELO_WORLD_AUDIT.chunkEvictionCount=chunkEvictionCount;try{window.dispatchEvent(new CustomEvent('kelo:world-audit'));}catch{}}
function touchCache(key,value){cache.delete(key);cache.set(key,value);}
function build(cx,cy){const key=cx+','+cy;if(cache.has(key)){const hit=cache.get(key);touchCache(key,hit);chunkHitCount+=1;return hit;}const c=document.createElement('canvas');c.width=CHUNK;c.height=CHUNK;const g=c.getContext('2d');g.imageSmoothingEnabled=false;const wx0=cx*CHUNK,wy0=cy*CHUNK,n=Math.ceil(CHUNK/TILE);for(let gy=0;gy<n;gy++)for(let gx=0;gx<n;gx++){const wx=wx0+gx*TILE,wy=wy0+gy*TILE,mx=wx+TILE/2,my=wy+TILE/2,X=Math.floor(wx/TILE),Y=Math.floor(wy/TILE),d=district(mx,my),vp=TERRAIN.districtVisualProfileFor(d?.id),p=TERRAIN.profileFor(d?.id),materialKey=terrainAt(mx,my);drawMaterial(g,materialKey,X,Y,gx*TILE,gy*TILE,p);drawTerrainTransitions(g,materialKey,wx,wy,gx*TILE,gy*TILE);drawTileOverlay(g,vp,p,materialKey,X,Y,gx*TILE,gy*TILE);}cache.set(key,c);chunkBuildCount+=1;if(cache.size>MAX){cache.delete(cache.keys().next().value);chunkEvictionCount+=1;}reportCache();return c;}
function bounds(){const view=CAM.worldView(),margin=CHUNK*CULL_MARGIN;return{minX:Math.max(0,Math.floor((view.left-margin)/CHUNK)),maxX:Math.min(Math.ceil((window.CONFIG?.worldWidth||3600)/CHUNK)-1,Math.floor((view.right+margin)/CHUNK)),minY:Math.max(0,Math.floor((view.top-margin)/CHUNK)),maxY:Math.min(Math.ceil((window.CONFIG?.worldHeight||3200)/CHUNK)-1,Math.floor((view.bottom+margin)/CHUNK))};}
function boundsRect(b){return{x:b.minX*CHUNK,y:b.minY*CHUNK,w:(b.maxX-b.minX+1)*CHUNK,h:(b.maxY-b.minY+1)*CHUNK};}
function chunkTouchesDistrict(cx,cy,d){return !!d&&intersects({x:cx*CHUNK,y:cy*CHUNK,w:CHUNK,h:CHUNK},{x:d.x,y:d.y,w:d.w,h:d.h});}
function invalidateDistrict(d){if(!d)return 0;let removed=0;for(const key of Array.from(cache.keys())){const parts=key.split(','),cx=Number(parts[0]),cy=Number(parts[1]);if(chunkTouchesDistrict(cx,cy,d)){cache.delete(key);removed+=1;}}if(removed)reportCache();return removed;}
function updateDistrictAudit(){const cam=window.camera||{x:1440,y:1520},active=district(cam.x,cam.y);window.KELO_WORLD_AUDIT.activeDistrictLabel=active?.id||null;}
function updateGardenAudit(){if(!window.KELO_WORLD_AUDIT)return;Object.assign(window.KELO_WORLD_AUDIT,{gardensAssetLoaded:gardenReady,gardensJoinAssetLoaded:gardenJoinReady,gardensResident:gardenHeld,gardensWanted:gardenWanted,gardensLoading:!!gardenLoadPromise,gardenAcquireCount,gardenReleaseCount});}
async function acquireGardenAssets(generation){try{const [base,joins]=await Promise.all([A.acquire('gardensBase'),A.acquire('gardensJoins')]);if(generation!==gardenLoadGeneration||!gardenWanted){A.release('gardensBase');A.release('gardensJoins');return;}gardenImg=base;gardenJoinImg=joins;gardenReady=true;gardenJoinReady=true;gardenHeld=true;gardenAcquireCount+=1;invalidateDistrict(GARDEN_DISTRICT);updateGardenAudit();}catch(err){try{A.release('gardensBase',{warmMs:0});A.release('gardensJoins',{warmMs:0});}catch(e){}gardenImg=null;gardenJoinImg=null;gardenReady=false;gardenJoinReady=false;gardenHeld=false;console.error('[Kelo world] gardens lazy atlas acquisition failed',err);}finally{if(generation===gardenLoadGeneration)gardenLoadPromise=null;updateGardenAudit();}}
function requestGardens(){gardenWanted=true;if(gardenHeld||gardenLoadPromise){updateGardenAudit();return;}const generation=++gardenLoadGeneration;gardenLoadPromise=acquireGardenAssets(generation);updateGardenAudit();}
function releaseGardens(){gardenWanted=false;++gardenLoadGeneration;gardenLoadPromise=null;if(gardenHeld){A.release('gardensBase');A.release('gardensJoins');gardenReleaseCount+=1;}gardenHeld=false;gardenImg=null;gardenJoinImg=null;gardenReady=false;gardenJoinReady=false;invalidateDistrict(GARDEN_DISTRICT);updateGardenAudit();}
function syncDistrictAssets(b){if(window.KELO_WORLD_DECORATION_RESET===true)return;const needGardens=!!GARDEN_DISTRICT&&intersects(boundsRect(b),{x:GARDEN_DISTRICT.x,y:GARDEN_DISTRICT.y,w:GARDEN_DISTRICT.w,h:GARDEN_DISTRICT.h});if(needGardens)requestGardens();else if(gardenWanted||gardenHeld||gardenLoadPromise)releaseGardens();}
function draw(g){if(!ready)return false;const b=bounds();syncDistrictAssets(b);for(let y=b.minY;y<=b.maxY;y++)for(let x=b.minX;x<=b.maxX;x++)g.drawImage(build(x,y),x*CHUNK,y*CHUNK);updateDistrictAudit();return true;}
function syncReady(){terrainReady=TERRAIN_ATLAS_KEYS.every(key=>ATLAS_IMAGES[key]?.ready===true);ready=terrainReady;if(ready)Object.assign(window.KELO_WORLD_AUDIT,{ready:true,assetLoaded:true,transitionAssetLoaded:true,grassVariationAssetLoaded:true,marbleVariationAssetLoaded:true,terrainAtlasesReady:true,atlasConsumerMode:'atlas-contract-managed-v2-lazy-district',worldOwnsImageLoader:false,atlasContractVersion:A.policy.version});updateGardenAudit();}
async function acquireManagedAtlases(){try{await Promise.all(TERRAIN_ATLAS_KEYS.map(async key=>{const image=await A.acquire(key);ATLAS_IMAGES[key].image=image;ATLAS_IMAGES[key].ready=true;}));syncReady();}catch(err){console.error('[Kelo world] managed core terrain atlas acquisition failed',err);}}
function performanceSnapshot(){return Object.freeze({version:'world-v1.27-performance',ready,chunkCacheSize:cache.size,chunkCacheCap:MAX,chunkBuildCount,chunkHitCount,chunkEvictionCount,activeDistrictLabel:window.KELO_WORLD_AUDIT?.activeDistrictLabel||null,gardensResident:gardenHeld,gardensWanted:gardenWanted,gardensLoading:!!gardenLoadPromise,gardenAcquireCount,gardenReleaseCount});}
const commerceProfile=TERRAIN.profileFor('commerce');
window.KELO_WORLD_AUDIT={version:'world-v1.27-performance',ready:false,assetLoaded:false,transitionAssetLoaded:false,grassVariationAssetLoaded:false,marbleVariationAssetLoaded:false,gardensAssetLoaded:false,gardensJoinAssetLoaded:false,gardensResident:false,gardensWanted:false,gardensLoading:false,gardenAcquireCount:0,gardenReleaseCount:0,terrainAtlasesReady:false,atlasConsumerMode:'atlas-contract-managed-v2-lazy-district',worldOwnsImageLoader:false,atlasContractVersion:A.policy.version,mobilePerformanceContractVersion:P.version,viewportOwner:'KeloCamera',viewportMode:'kelo-camera-world-view-v1',chunkCacheCap:MAX,chunkCullMarginChunks:CULL_MARGIN,chunkCacheSize:0,chunkCacheMode:'lru-v1',chunkBuildCount:0,chunkHitCount:0,chunkEvictionCount:0,terrainContractVersion:TERRAIN.version,districtVisualProfileVersion:TERRAIN.districtVisualProfileVersion,districtSourceMode:'terrain-contract-district-profiles-v2',districtOverlayMode:'profile-selected-provider-v1',terrainTopology:TERRAIN.topology,terrainMaterialCount:Object.keys(TERRAIN.materials).length,terrainTransitionSetCount:Object.keys(TERRAIN.transitions).length,terrainAtlasCount:TERRAIN_ATLAS_KEYS.length,terrainAtlasKeys:TERRAIN_ATLAS_KEYS,terrainRendererMode:'contract-driven-materials-v2',gardensMode:G.mode,gardensJoinMode:J.mode,gardensPathMode:'fountain-connected-promenade-v3',gardensTransitionMode:'authored-chamfered-path-topology-v1',gardensFramingMode:'registry-authored-modular-framing-v6',gardensCornerMode:'oriented-authored-corner-v1',gardensCornerOrientationCount:4,gardensFixedPlacementMode:GC?.fixedPlacementMode||null,gardensFixedPlacementCount:GC?.fixedPlacementCount||0,gardensCompositionMode:GC?.mode||null,gardensCompositionCount:GC?.compositionCount||0,gardensMarbleMode:R.styles?.marbleVariation?.mode||null,marbleVariationScope:R.styles?.marbleVariation?.scope||null,commerceMarbleVariation:commerceProfile.pathDetail===true,gardensGrassRhythmMode:'terrain-profile-variation-groups-v1',gardensLandmarkClearance:'east-fountain-footprint-v1',grassVariationMode:'authored-eight-variant-atlas-v1',grassVariationCount:(F.grassAuthored||[]).length,marbleVariationCount:(F.marbleVariation||[]).length,roadTransitionMode:'terrain-contract-edge-bitmask-v1',plazaRoadAlignment:'authored-plaza-ground-v1',districtLabelMode:'world-placards-removed-v1',activeDistrictLabel:null,chunkSize:CHUNK,districtCount:DISTRICTS.length,roadCount:ROADS.length+GARDEN_PATHS.length,districtStyleMode:'district-visual-profiles-v3',styledDistrictCount:Object.keys(TERRAIN.districtVisualProfiles).length,ruralRoadMode:'farm-bypass-v1',legacyTJunctionSpecialCase:false,worldWidth:window.CONFIG?.worldWidth||3600,worldHeight:window.CONFIG?.worldHeight||3200};
window.KELO_WORLD_RENDERER=Object.freeze({draw,districts:DISTRICTS,chunkSize:CHUNK,performanceSnapshot,get ready(){return window.KELO_WORLD_DECORATION_RESET===true?true:ready;}});
if(window.KELO_WORLD_DECORATION_RESET===true){ready=true;window.KELO_WORLD_AUDIT.ready=true;window.KELO_WORLD_AUDIT.assetLoaded=false;window.KELO_WORLD_AUDIT.terrainAtlasesReady=false;window.KELO_WORLD_AUDIT.resetBootstrap=true;}else acquireManagedAtlases();
})();
