/* KELO-INDEX
 * area: NETWORK
 * owner: KeloNetAuthority
 * keys: WEBSOCKET INPUT INTENT SEQUENCE PREDICTION RECONCILIATION INTERPOLATION SNAPSHOT PVP VISUAL TITLES COMMERCE PERFORMANCE LOD HEARTBEAT AVATAR IDENTITY
 * purpose: transporte único cliente; PvP conserva input autoritativo y mundo social usa pose change-driven + heartbeat; peers reutilizan KELO_PERF
 * online: cliente jamás declara daño/HP/kills/posición PvP final ni URLs de avatar; servidor devuelve manifests de avatar confiables
 * do-not: NO segundo transporte, NO loop paralelo, NO autoridad gameplay cliente
 */
(function(){
'use strict';
const params=new URLSearchParams(location.search),NET=params.get('net'),PLAYER_KEY_STORAGE='kelo_player_key_v1',ACTIVE_CHARACTER_STORAGE='kelo.active.character.v1',SESSION_STORAGE='kelo.supabase.session.v1';
const pending=new Map(),pendingPvpInputs=new Map(),VISUAL_EVENT_ALLOWLIST=new Set(['CAST_CONFIRMED','PROJECTILE_SPAWNED','PROJECTILE_HIT','PROJECTILE_EXPIRED','ABILITY_IMPACT','STATUS_APPLIED','STATUS_REMOVED','SHIELD_APPLIED','SHIELD_BROKEN','DASH_STARTED','DASH_ENDED','TRAP_PLACED','TRAP_ARMED','TRAP_TRIGGERED','TRAP_EXPIRED','DEATH']);
const INTERPOLATION_DELAY_MS=100,PVP_SEND_HZ=30,PVP_SEND_INTERVAL=1/PVP_SEND_HZ,MAX_PENDING_PVP=128,POSE_CHECK_INTERVAL=.1,POSE_HEARTBEAT_INTERVAL=1;
let requestSeq=1,pvpSequence=1,ws=null,myId=null,sendAcc=0,pvpSendAcc=0,lastPvpAck=0,lastServerTick=0,lastPose=null,lastPoseSentAt=0,onlineIdentity=null,avatarRuntimePromise=null;
const perfCounters={poseSent:0,poseSkippedUnchanged:0,peerUpdates:0,peerUpdateSkipped:0,peerDrawn:0,peerDrawSkipped:0};
function makePlayerKey(){if(window.crypto&&typeof window.crypto.randomUUID==='function')return window.crypto.randomUUID();return'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==='x'?r:(r&3|8);return v.toString(16)})}
function readPlayerKey(){try{let key=localStorage.getItem(PLAYER_KEY_STORAGE);if(!key){key=makePlayerKey();localStorage.setItem(PLAYER_KEY_STORAGE,key)}return key}catch(_){return makePlayerKey()}}
function savePlayerKey(key){if(!key)return;try{localStorage.setItem(PLAYER_KEY_STORAGE,key)}catch(_){}}
function readStoredOnlineIdentity(){try{const raw=localStorage.getItem(SESSION_STORAGE),characterId=localStorage.getItem(ACTIVE_CHARACTER_STORAGE);if(!raw||!characterId)return null;const session=JSON.parse(raw);if(!session?.access_token)return null;return{accessToken:session.access_token,characterId:String(characterId),name:typeof localPlayer!=='undefined'&&localPlayer?.name||'Kelo',expiresAt:Number(session.expires_at)||0};}catch(_){return null}}
async function freshOnlineIdentity(){let row=readStoredOnlineIdentity();if(!row)return null;if(row.expiresAt&&row.expiresAt-Math.floor(Date.now()/1000)<90){try{const mod=await import('./src/online/kelo-supabase-browser-session.mjs?v=2'),session=mod.createKeloSupabaseBrowserSession({root:window});await session.ensureFresh();row=readStoredOnlineIdentity();}catch(_){}}return row;}
function ensureAvatarRuntime(){if(window.KeloCreatorAvatars)return Promise.resolve(window.KeloCreatorAvatars);if(!avatarRuntimePromise)avatarRuntimePromise=import('./src/characters/creator-avatar-runtime.mjs?v=2').then(mod=>mod.installCreatorAvatarRuntime({root:window})).catch(error=>{avatarRuntimePromise=null;throw error;});return avatarRuntimePromise;}
function ingestAvatarManifest(raw,isSelf){if(!raw)return Promise.resolve(null);return ensureAvatarRuntime().then(api=>{const manifest=api.register(raw);if(isSelf&&manifest)api.select(manifest.contentId,{manifest,persistLocal:true});return manifest;}).catch(()=>null)}
window.keloNet={on:false,id:null,peers:{},url:NET,playerKey:readPlayerKey(),nobilitySource:'local-fallback',titleSource:'local-fallback',forgeSource:'local-fallback',commerceSource:'local-fallback',visualEventSource:'local-fallback',avatarSource:'local-fallback',pvpSource:'local-fallback',pvpProjectiles:[]};
const peers=window.keloNet.peers;
function ensureChip(){let chip=document.getElementById('kelo-online');if(chip)return chip;chip=document.createElement('div');chip.id='kelo-online';chip.style.cssText=['position:absolute','top:max(44px, calc(env(safe-area-inset-top) + 36px))','left:max(8px, env(safe-area-inset-left))','z-index:80','pointer-events:none','display:flex','align-items:center','gap:6px','padding:5px 10px','border-radius:999px','background:rgba(10,13,18,.92)','border:1px solid rgba(231,197,106,.35)','color:#e7c56a','font:700 10px/1.2 -apple-system,sans-serif','white-space:nowrap'].join(';');document.body.appendChild(chip);return chip}
function countOnline(){return window.keloNet.on?1+Object.keys(peers).length:0}
function paintChip(state,n){const chip=ensureChip(),dot=state==='on'?'#3ddc84':state==='wait'?'#e7c56a':'#8a9099',label=state==='on'?'Online '+n:state==='wait'?'Conectando':state==='err'?'Sin señal':'Local';chip.innerHTML='<span style="width:7px;height:7px;border-radius:50%;background:'+dot+'"></span><span>'+label+'</span>'}
function nextRequestId(prefix){return prefix+'_'+Date.now().toString(36)+'_'+(requestSeq++).toString(36)}
function request(type,payload,timeoutMs){if(!ws||ws.readyState!==1)return Promise.reject(new Error('NETWORK_OFFLINE'));const requestId=nextRequestId(type.replace(/[^a-z]/gi,''));return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pending.delete(requestId);reject(new Error('NETWORK_TIMEOUT'))},timeoutMs||8000);pending.set(requestId,{resolve,reject,timer});ws.send(JSON.stringify(Object.assign({t:type,requestId},payload||{})))})}
function settle(requestId,ok,value){if(!requestId||!pending.has(requestId))return;const item=pending.get(requestId);pending.delete(requestId);clearTimeout(item.timer);if(ok)item.resolve(value);else item.reject(value instanceof Error?value:new Error(String(value||'SERVER_ERROR')))}
function ingestNobility(snapshot){if(!snapshot)return;window.keloNet.nobilitySource=snapshot.source||'server-authoritative';if(window.KeloNobility&&typeof window.KeloNobility.ingestServerSnapshot==='function')window.KeloNobility.ingestServerSnapshot(snapshot)}
function ingestTitles(snapshot){if(!snapshot)return;window.keloNet.titleSource=snapshot.source||'server-authoritative';if(window.KeloTitles&&typeof window.KeloTitles.ingestServerSnapshot==='function')window.KeloTitles.ingestServerSnapshot(snapshot)}
function ingestForge(snapshot){if(!snapshot)return;window.keloNet.forgeSource='server-authoritative';if(typeof STATE!=='undefined'&&Number.isFinite(snapshot.gold))STATE.gold=snapshot.gold;if(window.KeloEquipment){if(Array.isArray(snapshot.equipment))snapshot.equipment.forEach(item=>window.KeloEquipment.applyServerItem(item));if(typeof localPlayer!=='undefined'){localPlayer.armorScore=snapshot.armorScore||0;localPlayer.auraRank=snapshot.auraRank||0;localPlayer.averageQuality=snapshot.averageQuality||0;localPlayer.averageGrade=snapshot.averageGrade||0;localPlayer.equipmentSummary=snapshot.equipmentSummary||[]}}}
function ingestCommerce(msg){if(!msg)return;window.keloNet.commerceSource='server-authoritative';try{window.dispatchEvent(new CustomEvent('kelo:commerce-server-event',{detail:msg}))}catch(_){}}
function visualMeta(payload){const p=payload||{};return{status:typeof p.status==='string'?p.status.slice(0,40):null,duration:Number.isFinite(Number(p.duration))?Number(p.duration):(p.effect&&Number.isFinite(Number(p.effect.duration))?Number(p.effect.duration):null),targetActorId:p.targetActorId==null?null:String(p.targetActorId).slice(0,80),amount:Number.isFinite(Number(p.amount))?Number(p.amount):null,reason:p.reason==null?null:String(p.reason).slice(0,80)}}
function replicateVisualEvent(name,payload){if(!VISUAL_EVENT_ALLOWLIST.has(name)||!ws||ws.readyState!==1||!window.keloNet.on)return false;if(payload&&(payload.remote===true||payload.networkReplay===true))return false;const context=window.KeloVisualContext&&typeof window.KeloVisualContext.serialize==='function'?window.KeloVisualContext.serialize(payload||{}):null;if(!context)return false;ws.send(JSON.stringify({t:'visual:event',name,context,meta:visualMeta(payload)}));return true}
function ingestVisualEvent(msg){if(!msg||!VISUAL_EVENT_ALLOWLIST.has(msg.name)||!window.KeloVisualEventBus)return;const c=Object.assign({},msg.context||{},msg.meta||{},{remote:true,networkReplay:true,serverTime:Number(msg.serverTime)||null,sourceActorId:msg.actorId||null});c.actorId=msg.actorId||c.actorId;if(c.actorId)c.actor=peers[c.actorId]||null;window.keloNet.visualEventSource='server-relay';window.KeloVisualEventBus.emit(msg.name,c)}
function pvpActive(){try{return !!(window.KeloPvPWorld&&window.KeloPvPWorld.state&&window.KeloPvPWorld.state.combatEnabled)}catch(_){return false}}
function currentAim(){try{const a=window.KeloPvPWorld&&window.KeloPvPWorld.state&&window.KeloPvPWorld.state.aim;if(a&&Number.isFinite(a.x)&&Number.isFinite(a.y))return{x:a.x,y:a.y}}catch(_){}return{x:1,y:0}}
function currentMove(){return{x:typeof input!=='undefined'?Number(input.normX)||0:0,y:typeof input!=='undefined'?Number(input.normY)||0:0}}
function sanitizeUnit(x,y){x=Number(x)||0;y=Number(y)||0;const l=Math.hypot(x,y);if(l>1){x/=l;y/=l}return{x,y}}
function sendCombatIntent(raw){if(!ws||ws.readyState!==1||!window.keloNet.on)return false;const source=raw&&typeof raw==='object'?raw:{},move=sanitizeUnit(source.moveX!=null?source.moveX:currentMove().x,source.moveY!=null?source.moveY:currentMove().y),aim=sanitizeUnit(source.aimX!=null?source.aimX:currentAim().x,source.aimY!=null?source.aimY:currentAim().y),sequence=pvpSequence++,action=String(source.action||'input'),intent={sequence,moveX:move.x,moveY:move.y,aimX:aim.x,aimY:aim.y,action,phase:String(source.phase||'none'),abilityKey:source.abilityKey||null,slot:Number.isInteger(Number(source.slot))?Number(source.slot):null,direction:source.direction||null,position:source.position||null,targetId:source.targetId||null,attackId:source.attackId||null,swordEntityId:source.swordEntityId||null,clientTime:Number(source.clientTime)||Date.now()};const replayDt=action==='input'?PVP_SEND_INTERVAL:0;pendingPvpInputs.set(sequence,{sequence,moveX:move.x,moveY:move.y,aimX:aim.x,aimY:aim.y,replayDt,clientTime:intent.clientTime});while(pendingPvpInputs.size>MAX_PENDING_PVP)pendingPvpInputs.delete(pendingPvpInputs.keys().next().value);ws.send(JSON.stringify({t:'pvp:input',intent}));return sequence}
function peerBase(p){return{id:p.id,name:p.name||'Kelo',x:Number(p.x)||0,y:Number(p.y)||0,vx:0,vy:0,radius:20,hp:Number.isFinite(Number(p.hp))?Number(p.hp):100,maxHp:Number.isFinite(Number(p.maxHp))?Number(p.maxHp):100,mana:Number.isFinite(Number(p.mana))?Number(p.mana):100,maxMana:Number.isFinite(Number(p.maxMana))?Number(p.maxMana):100,gear:{bodyColor:'#7b6cff',armorColor:'#e7c56a',weaponColor:'#fff'},avatarManifest:p.avatarManifest||null,_face:p.face||'down',_gait:p.gait||'idle',zone:p.zone||'plaza',_snapshots:[]}}
function pushPeerSnapshot(peer,p,serverTime){const snap={time:Number(serverTime)||Date.now(),x:Number(p.x)||0,y:Number(p.y)||0,face:p.face||peer._face||'down',gait:p.gait||peer._gait||'idle',zone:p.zone||peer.zone||'plaza',hp:Number.isFinite(Number(p.hp))?Number(p.hp):peer.hp,mana:Number.isFinite(Number(p.mana))?Number(p.mana):peer.mana};peer._snapshots=Array.isArray(peer._snapshots)?peer._snapshots:[];peer._snapshots.push(snap);while(peer._snapshots.length>32)peer._snapshots.shift();peer.zone=snap.zone;peer.hp=snap.hp;peer.mana=snap.mana;peer._face=snap.face;peer._gait=snap.gait}
function upsert(p,serverTime){if(!p||!p.id||p.id===myId)return;const peer=peers[p.id]||peerBase(p);peer.name=p.name||peer.name;peer.nobilityRank=p.nobilityRank||peer.nobilityRank||'none';peer.nobilityPower=Number(p.nobilityPower)||0;peer.equippedTitleId=p.equippedTitleId||null;peer.armorScore=Math.max(0,Math.floor(Number(p.armorScore)||0));peer.auraRank=Math.max(0,Math.min(9,Math.floor(Number(p.auraRank)||0)));peer.averageQuality=Number(p.averageQuality)||0;peer.averageGrade=Number(p.averageGrade)||0;peer.equipmentSummary=Array.isArray(p.equipmentSummary)?p.equipmentSummary:[];peer.avatarManifest=p.avatarManifest||null;if(peer.avatarManifest){window.keloNet.avatarSource='server-authoritative';ingestAvatarManifest(peer.avatarManifest,false)}pushPeerSnapshot(peer,p,serverTime);peers[p.id]=peer;paintChip('on',countOnline())}
function ingest(map,serverTime){if(!map)return;if(myId&&map[myId]?.avatarManifest){window.keloNet.avatarSource='server-authoritative';ingestAvatarManifest(map[myId].avatarManifest,true)}const live={};Object.keys(map).forEach(id=>{live[id]=true;upsert(map[id],serverTime)});Object.keys(peers).forEach(id=>{if(!live[id])delete peers[id]});paintChip(window.keloNet.on?'on':'wait',countOnline())}
function interpolatePeer(peer,nowMs){const snaps=peer._snapshots||[];if(!snaps.length)return;const renderTime=nowMs-INTERPOLATION_DELAY_MS;while(snaps.length>2&&snaps[1].time<=renderTime)snaps.shift();let a=snaps[0],b=snaps[1]||a;if(renderTime<=a.time||a===b){peer.x=a.x;peer.y=a.y}else if(renderTime>=b.time){const dt=Math.max(1,b.time-a.time),extrap=Math.min(50,renderTime-b.time),vx=(b.x-a.x)/dt,vy=(b.y-a.y)/dt;peer.x=b.x+vx*extrap;peer.y=b.y+vy*extrap}else{const t=(renderTime-a.time)/Math.max(1,b.time-a.time);peer.x=a.x+(b.x-a.x)*t;peer.y=a.y+(b.y-a.y)*t}peer._face=b.face||a.face;peer._gait=b.gait||a.gait;peer.zone=b.zone||a.zone;peer.hp=b.hp;peer.mana=b.mana}
function reconcileLocal(serverPlayer){if(!serverPlayer||typeof localPlayer==='undefined')return;if(serverPlayer.avatarManifest)ingestAvatarManifest(serverPlayer.avatarManifest,true);const ack=Math.max(0,Number(serverPlayer.ackSequence)||0);lastPvpAck=Math.max(lastPvpAck,ack);Array.from(pendingPvpInputs.keys()).forEach(seq=>{if(seq<=ack)pendingPvpInputs.delete(seq)});let rx=Number(serverPlayer.x)||localPlayer.x,ry=Number(serverPlayer.y)||localPlayer.y;const speed=typeof CONFIG!=='undefined'&&Number(CONFIG.speed)||320;Array.from(pendingPvpInputs.values()).sort((a,b)=>a.sequence-b.sequence).forEach(item=>{if(item.replayDt>0){rx+=item.moveX*speed*item.replayDt;ry+=item.moveY*speed*item.replayDt}});const error=Math.hypot(rx-localPlayer.x,ry-localPlayer.y),blend=error>80?1:error>8?.5:.2;localPlayer.x+=(rx-localPlayer.x)*blend;localPlayer.y+=(ry-localPlayer.y)*blend;if(Number.isFinite(Number(serverPlayer.hp)))localPlayer.hp=Number(serverPlayer.hp);if(Number.isFinite(Number(serverPlayer.maxHp)))localPlayer.maxHp=Number(serverPlayer.maxHp);if(Number.isFinite(Number(serverPlayer.mana)))localPlayer.mana=Number(serverPlayer.mana);if(Number.isFinite(Number(serverPlayer.maxMana)))localPlayer.maxMana=Number(serverPlayer.maxMana);if(serverPlayer.face)localPlayer._face=serverPlayer.face;window.KELO_PVP_NET_AUDIT={version:'pvp-net-v1',lastAck:lastPvpAck,pending:pendingPvpInputs.size,lastServerTick,reconciliationError:error,interpolationDelayMs:INTERPOLATION_DELAY_MS}}
const consumedPvpEvents=new Set();
function ingestPvpEvents(events,serverTime){if(!Array.isArray(events))return;events.forEach(ev=>{if(!ev||!ev.id||consumedPvpEvents.has(ev.id))return;consumedPvpEvents.add(ev.id);if(consumedPvpEvents.size>256)consumedPvpEvents.delete(consumedPvpEvents.values().next().value);if(!window.KeloVisualEventBus)return;const base={remote:true,networkReplay:true,serverTime:Number(serverTime)||Date.now(),actorId:ev.actorId||null,actor:ev.actorId===myId?localPlayer:peers[ev.actorId]||null,targetActorId:ev.targetId||null,targetActor:ev.targetId===myId?localPlayer:peers[ev.targetId]||null,projectileId:ev.projectileId||ev.projectile&&ev.projectile.id||null,abilityKey:ev.abilityKey||ev.projectile&&ev.projectile.abilityKey||null,direction:ev.direction||null,target:ev.target||ev.position||null,origin:ev.position||null,amount:ev.amount||null};if(ev.type==='PROJECTILE_SPAWNED')window.KeloVisualEventBus.emit('PROJECTILE_SPAWNED',Object.assign(base,{gameplayObject:ev.projectile||null}));else if(ev.type==='PROJECTILE_HIT')window.KeloVisualEventBus.emit('PROJECTILE_HIT',base);else if(ev.type==='PROJECTILE_EXPIRED')window.KeloVisualEventBus.emit('PROJECTILE_EXPIRED',base);else if(ev.type==='DASH_STARTED')window.KeloVisualEventBus.emit('DASH_STARTED',base);else if(ev.type==='DASH_ENDED')window.KeloVisualEventBus.emit('DASH_ENDED',base);else if(ev.type==='DEATH')window.KeloVisualEventBus.emit('DEATH',base)})}
function ingestPvpSnapshot(msg){if(!msg||!msg.players)return;lastServerTick=Math.max(lastServerTick,Number(msg.serverTick)||0);window.keloNet.pvpSource='server-authoritative';window.keloNet.pvpProjectiles=Array.isArray(msg.projectiles)?msg.projectiles.slice():[];const local=msg.players[myId];if(local)reconcileLocal(local);Object.keys(msg.players).forEach(id=>{if(id!==myId)upsert(msg.players[id],msg.serverTime)});ingestPvpEvents(msg.events,msg.serverTime)}
async function sendHello(){onlineIdentity=await freshOnlineIdentity()||onlineIdentity;const msg={t:'hello',name:typeof localPlayer!=='undefined'&&localPlayer?.name||'Kelo',playerKey:window.keloNet.playerKey};if(onlineIdentity?.accessToken&&onlineIdentity?.characterId){msg.accessToken=onlineIdentity.accessToken;msg.characterId=onlineIdentity.characterId;}if(ws&&ws.readyState===1)ws.send(JSON.stringify(msg))}
function connect(){if(!NET){paintChip('off',0);return}try{ws=new WebSocket(NET)}catch(_){paintChip('err',0);return}paintChip('wait',0);ws.onopen=async()=>{window.keloNet.on=true;lastPose=null;lastPoseSentAt=0;await sendHello();paintChip('on',countOnline())};ws.onclose=()=>{window.keloNet.on=false;pending.forEach(item=>{clearTimeout(item.timer);item.reject(new Error('NETWORK_CLOSED'))});pending.clear();pendingPvpInputs.clear();paintChip('err',0);setTimeout(connect,1500)};ws.onerror=()=>paintChip('err',0);ws.onmessage=ev=>{let msg;try{msg=JSON.parse(ev.data)}catch(_){return}if(msg.t==='welcome'){myId=msg.id;window.keloNet.id=myId;window.keloNet.nobilitySource=msg.nobilitySource||window.keloNet.nobilitySource;window.keloNet.titleSource=msg.titleSource||window.keloNet.titleSource;window.keloNet.forgeSource=msg.forgeSource||window.keloNet.forgeSource;window.keloNet.commerceSource=msg.commerceSource||window.keloNet.commerceSource;ingest(msg.players,msg.serverTime)}if(msg.t==='identity'&&msg.playerKey){window.keloNet.playerKey=msg.playerKey;savePlayerKey(msg.playerKey)}if(msg.t==='state')ingest(msg.players,msg.serverTime);if(msg.t==='join'&&msg.player)upsert(msg.player,msg.serverTime);if(msg.t==='leave'&&msg.id){delete peers[msg.id];paintChip(window.keloNet.on?'on':'err',countOnline())}if(msg.t==='avatar:refreshed'){window.keloNet.avatarSource='server-authoritative';if(msg.avatarManifest)ingestAvatarManifest(msg.avatarManifest,true);settle(msg.requestId,true,msg)}if(msg.t==='pvp:snapshot')ingestPvpSnapshot(msg);if(msg.t==='pvp:reject'){if(Number.isFinite(Number(msg.ackSequence)))Array.from(pendingPvpInputs.keys()).forEach(seq=>{if(seq<=Number(msg.ackSequence))pendingPvpInputs.delete(seq)});window.KELO_PVP_NET_REJECT={sequence:msg.sequence||null,code:msg.code||'REJECTED',at:Date.now()}}if(msg.t==='visual:event')ingestVisualEvent(msg);if(msg.t==='nobility:snapshot'){ingestNobility(msg.snapshot);settle(msg.requestId,true,msg.snapshot)}if(msg.t==='nobility:donated'){ingestNobility(msg.snapshot);settle(msg.requestId,true,msg)}if(msg.t==='titles:snapshot'){ingestTitles(msg.snapshot);settle(msg.requestId,true,msg.snapshot)}if(msg.t==='titles:equipped'||msg.t==='titles:unequipped'){ingestTitles(msg.snapshot);settle(msg.requestId,true,msg.snapshot)}if(msg.t==='combat:resolved')settle(msg.requestId,true,msg);if(msg.t==='forge:snapshot'){ingestForge(msg.snapshot);settle(msg.requestId,true,msg.snapshot)}if(msg.t==='forge:result'){if(msg.item&&window.KeloEquipment)window.KeloEquipment.applyServerItem(msg.item);if(Number.isFinite(msg.gold)&&typeof STATE!=='undefined')STATE.gold=msg.gold;settle(msg.requestId,true,msg)}if(msg.t==='forge:combined'){ingestForge(msg.snapshot);settle(msg.requestId,true,msg.snapshot)}if(msg.t==='commerce:result'){ingestCommerce(msg);settle(msg.requestId,true,msg)}if(msg.t==='commerce:event')ingestCommerce(msg);if(msg.t==='error')settle(msg.requestId,false,new Error(msg.code||msg.message||'SERVER_ERROR'))}}
async function refreshAvatar(identityInput){const input=identityInput&&typeof identityInput==='object'?identityInput:{};if(input.characterId){try{localStorage.setItem(ACTIVE_CHARACTER_STORAGE,String(input.characterId))}catch(_){}}onlineIdentity={accessToken:String(input.accessToken||''),characterId:String(input.characterId||''),name:String(input.name||'Kelo')};if(!onlineIdentity.accessToken||!onlineIdentity.characterId)throw new Error('AVATAR_IDENTITY_REQUIRED');const result=await request('avatar:refresh',onlineIdentity,10000);return result}
window.KeloNetAuthority=Object.freeze({version:'net-authority-v7-avatar-sync',isOnline:()=>!!(ws&&ws.readyState===1&&window.keloNet.on),getNobility:()=>request('nobility:get'),donateNobility:(currency,amount)=>request('nobility:donate',{currency,amount:Math.floor(Number(amount))}),getTitles:()=>request('titles:get'),equipTitle:titleId=>request('titles:equip',{titleId:String(titleId||'')}),unequipTitle:()=>request('titles:unequip'),resolveDamage:baseDamage=>request('combat:resolve',{baseDamage:Math.floor(Number(baseDamage))}),getForge:()=>request('forge:get'),attemptForge:(itemId,forgeType,materialLevel,crystals)=>request('forge:attempt',{itemId,forgeType,materialLevel:Math.floor(Number(materialLevel)),crystals:Array.isArray(crystals)?crystals:[]}),combineForgeMaterials:materialId=>request('forge:combine',{materialId}),requestCommerce:(op,payload)=>request('commerce:request',{op:String(op||''),payload:payload&&typeof payload==='object'?payload:{}}),refreshAvatar,syncEquipment:()=>Promise.resolve({ok:true,mode:'server-derived'}),replicateVisualEvent,sendCombatIntent,getPvpPendingCount:()=>pendingPvpInputs.size,getLastPvpAck:()=>lastPvpAck});
if(window.KeloVisualEventBus&&typeof window.KeloVisualEventBus.on==='function')VISUAL_EVENT_ALLOWLIST.forEach(name=>window.KeloVisualEventBus.on(name,payload=>replicateVisualEvent(name,payload)));
connect();
function currentNetworkZone(){if(pvpActive())return'pvp';try{const scene=window.KELO_SCENE_CONTEXT&&window.KELO_SCENE_CONTEXT.current();if(scene&&scene.zoneType==='instance'&&scene.instanceType)return scene.instanceType}catch(_){}return window.keloZone||'plaza'}
function performanceOwner(){return window.KELO_PERF||window.KELO_PERFORMANCE_GOVERNOR||null}
function peerDistance(peer){if(typeof localPlayer==='undefined'||!localPlayer||!peer)return 0;return Math.hypot((Number(peer.x)||0)-(Number(localPlayer.x)||0),(Number(peer.y)||0)-(Number(localPlayer.y)||0))}
function poseSnapshot(){return{x:Number(localPlayer.x)||0,y:Number(localPlayer.y)||0,face:localPlayer._face||'down',gait:localPlayer._gait||'idle',zone:currentNetworkZone()}}
function poseChanged(previous,next){if(!previous)return true;if(previous.zone!==next.zone||previous.face!==next.face||previous.gait!==next.gait)return true;return Math.hypot(next.x-previous.x,next.y-previous.y)>=1.25}
function sendSocialPose(nowMs){const next=poseSnapshot(),changed=poseChanged(lastPose,next),heartbeat=!lastPose||nowMs-lastPoseSentAt>=POSE_HEARTBEAT_INTERVAL*1000;if(!changed&&!heartbeat){perfCounters.poseSkippedUnchanged++;return false}ws.send(JSON.stringify({t:'pose',x:next.x,y:next.y,face:next.face,gait:next.gait,zone:next.zone}));lastPose=next;lastPoseSentAt=nowMs;perfCounters.poseSent++;return true}
function tickNetwork(context){const dt=context.dt;sendAcc+=dt;pvpSendAcc+=dt;if(ws&&ws.readyState===1&&localPlayer){if(pvpActive()){sendAcc=0;while(pvpSendAcc>=PVP_SEND_INTERVAL){pvpSendAcc-=PVP_SEND_INTERVAL;const move=currentMove(),aim=currentAim();sendCombatIntent({action:'input',phase:'held',moveX:move.x,moveY:move.y,aimX:aim.x,aimY:aim.y,clientTime:Date.now()})}}else if(sendAcc>=POSE_CHECK_INTERVAL){sendAcc=0;pvpSendAcc=0;sendSocialPose(Date.now())}}const nowMs=Date.now(),perf=performanceOwner();Object.keys(peers).forEach(id=>{const peer=peers[id],distance=peerDistance(peer);if(!perf||typeof perf.shouldUpdate!=='function'||perf.shouldUpdate('net-peer:'+id,distance,nowMs)){interpolatePeer(peer,nowMs);perfCounters.peerUpdates++}else perfCounters.peerUpdateSkipped++})}
function drawPeers(){if(typeof renderAvatar!=='function')return;const ids=Object.keys(peers);if(!ids.length)return;const perf=performanceOwner(),z=CONFIG.zoom||1;ctx.save();ctx.translate(screenW/2,screenH/2);ctx.scale(z,z);ctx.translate(-camera.x,-camera.y);ids.forEach(id=>{const peer=peers[id];if(pvpActive()&&peer.zone==='pvp')return;const distance=peerDistance(peer);if(perf&&typeof perf.shouldRenderActor==='function'&&!perf.shouldRenderActor(distance)){perfCounters.peerDrawSkipped++;return}renderAvatar(peer,false);perfCounters.peerDrawn++});ctx.restore()}
if(!window.KeloSimulation||!window.KeloRender)throw new Error('Foundation render/simulation owners unavailable before engine-net');window.KeloSimulation.after('engine-net:network',tickNetwork,300);window.KeloRender.afterFrame('engine-net:peers',drawPeers,300);
window.KELO_NET_AUDIT={version:'net-authority-v7-avatar-sync',owner:'KeloNetAuthority',pvpInputIntent:true,sequence:true,reconciliation:true,remoteInterpolation:true,interpolationDelayMs:INTERPOLATION_DELAY_MS,clientDamageAuthority:false,clientPositionAuthorityInPvp:false,clientAvatarUrlAuthority:false,avatarServerManifest:true,poseChangeDriven:true,POSE_HEARTBEAT_INTERVAL,peerLod:true,performanceSnapshot:()=>Object.freeze({...perfCounters,peerCount:Object.keys(peers).length})};
})();