/* KELO-INDEX
 * area: UI / ACCOUNT AUTH
 * owner: KeloAccountAuthUI
 * keys: LOGIN REGISTER EMAIL PASSWORD GUEST ACCOUNT DURABLE CHARACTER MOBILE MODAL
 * purpose: puerta visual de cuenta que consume exclusivamente KeloOnlineAuth y diferencia cuenta durable de invitado local
 * online: al completar una acción recarga para que el único KeloNetAuthority haga hello con la sesión persistida
 * do-not: NO guardar contraseñas, NO crear sockets, NO usar service_role/secret, NO mutar gameplay
 */
(function(){
'use strict';
const VERSION='kelo-account-auth-ui-v1.0.6-sync-world';
const UPGRADE_PENDING='kelo_guest_upgrade_pending_email_v1';
const LOCAL_GUEST_KEY='kelo_local_guest_play_v1';
let root=null,card=null,message=null,busy=false,mode='login',lastState=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=()=>window.KeloOnlineAuth||null;
function queryFlag(name){try{return new URLSearchParams(location.search||'').get(name)==='1'}catch(_){return false}}
function localGuestOptIn(){try{return sessionStorage.getItem(LOCAL_GUEST_KEY)==='1'||localStorage.getItem(LOCAL_GUEST_KEY)==='1'}catch(_){return false}}
function bypassGate(){return queryFlag('mapEditor')||queryFlag('visualLab')||queryFlag('guest')||queryFlag('aiGuest')||localGuestOptIn()||!!window.KeloGuestPlay?.active?.()}
function anonymousDisabled(error){const raw=String(error?.message||error||'').toLowerCase();return /anonymous/.test(raw)&&(raw.includes('disabled')||raw.includes('not enabled')||raw.includes('not allow'))}
function enterLocalPlay(){try{window.KeloGuestPlay?.enterLocal?.()}catch(_){}try{sessionStorage.setItem(LOCAL_GUEST_KEY,'1');localStorage.setItem(LOCAL_GUEST_KEY,'1')}catch(_){}hide()}
function explicitEditorMode(){return bypassGate()}
function style(){if(document.getElementById('kelo-account-auth-style'))return;const el=document.createElement('style');el.id='kelo-account-auth-style';el.textContent=`
#kelo-account-auth{position:fixed;inset:0;z-index:2147482000;display:grid;place-items:center;padding:max(18px,env(safe-area-inset-top)) max(16px,env(safe-area-inset-right)) max(18px,env(safe-area-inset-bottom)) max(16px,env(safe-area-inset-left));background:radial-gradient(circle at 50% 18%,rgba(196,150,56,.16),transparent 35%),linear-gradient(180deg,rgba(3,5,8,.94),rgba(2,3,5,.985));backdrop-filter:blur(10px);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#f4ead3;pointer-events:auto;touch-action:manipulation}
#kelo-account-auth[hidden]{display:none!important}.ka-card{width:min(440px,100%);max-height:min(760px,94dvh);overflow:auto;padding:25px 22px 20px;border:1px solid rgba(224,186,98,.28);border-radius:24px;background:linear-gradient(180deg,rgba(18,19,22,.98),rgba(8,10,13,.99));box-shadow:0 28px 90px rgba(0,0,0,.6),inset 0 1px rgba(255,255,255,.05)}
.ka-mark{width:52px;height:52px;margin:0 auto 12px;display:grid;place-items:center;border-radius:17px;border:1px solid rgba(224,186,98,.38);background:linear-gradient(145deg,#2e2618,#0f1013);font:900 18px/1 Georgia;color:#e5bd62;box-shadow:inset 0 0 24px rgba(224,186,98,.08)}.ka-title{text-align:center;font:800 clamp(24px,7vw,31px)/1.05 Georgia,serif;letter-spacing:.04em;color:#f4dfad}.ka-sub{text-align:center;margin:8px auto 19px;max-width:330px;color:#9fa4ad;font-size:13px;line-height:1.45}.ka-tabs{display:grid;grid-template-columns:1fr 1fr;gap:6px;padding:5px;margin:0 0 15px;border-radius:14px;background:#090b0e;border:1px solid rgba(255,255,255,.06)}.ka-tab{appearance:none;border:0;border-radius:10px;padding:10px 8px;background:transparent;color:#9298a2;font-weight:800;font-size:13px}.ka-tab.is-on{background:#1b1d21;color:#f3d690;box-shadow:0 1px 0 rgba(255,255,255,.05)}
.ka-field{display:grid;gap:6px;margin:11px 0}.ka-label{font-size:11px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:#8f949d}.ka-input{width:100%;min-height:49px;border:1px solid rgba(255,255,255,.10);border-radius:13px;background:#0b0d10;color:#f5f5f5;padding:0 14px;font-size:16px;outline:none;user-select:text;-webkit-user-select:text}.ka-input:focus{border-color:rgba(230,190,96,.65);box-shadow:0 0 0 3px rgba(230,190,96,.08)}.ka-primary,.ka-secondary,.ka-ghost{width:100%;min-height:49px;border-radius:13px;font-size:14px;font-weight:900;letter-spacing:.01em}.ka-primary{border:1px solid #e5bd62;background:linear-gradient(180deg,#e9c976,#c99a3c);color:#161109;box-shadow:0 10px 30px rgba(201,154,60,.17)}.ka-secondary{border:1px solid rgba(229,189,98,.24);background:#15171b;color:#e8d29f}.ka-ghost{border:0;background:transparent;color:#9298a2;min-height:40px}.ka-primary:disabled,.ka-secondary:disabled{opacity:.45}.ka-actions{display:grid;gap:9px;margin-top:15px}.ka-divider{display:flex;align-items:center;gap:10px;margin:16px 0;color:#666c75;font-size:11px}.ka-divider:before,.ka-divider:after{content:"";height:1px;flex:1;background:rgba(255,255,255,.07)}.ka-msg{min-height:18px;margin-top:11px;padding:0 2px;text-align:center;font-size:12px;line-height:1.4;color:#c5c9cf}.ka-msg.err{color:#ffaaa5}.ka-msg.ok{color:#9de6b3}.ka-note{margin-top:13px;padding:11px 12px;border-radius:12px;background:rgba(255,255,255,.035);color:#858b94;font-size:11px;line-height:1.45}.ka-guest{padding:14px;margin:0 0 14px;border:1px solid rgba(229,189,98,.20);border-radius:14px;background:rgba(229,189,98,.055)}.ka-guest strong{display:block;color:#e9cc86;margin-bottom:5px}.ka-account-chip{position:fixed;right:max(10px,env(safe-area-inset-right));top:max(10px,env(safe-area-inset-top));z-index:2147480000;appearance:none;border:1px solid rgba(229,189,98,.25);border-radius:999px;background:rgba(10,12,15,.88);color:#d8bd7b;padding:8px 11px;font:800 11px/1 -apple-system,sans-serif;backdrop-filter:blur(8px)}
@media (min-width:800px){.ka-card{padding:29px 30px 24px}.ka-account-chip{top:14px;right:14px}}
`;document.head.appendChild(el)}
function ensureRoot(){if(root)return root;style();root=document.getElementById('kelo-account-auth');if(!root){root=document.createElement('div');root.id='kelo-account-auth';root.hidden=true;root.innerHTML='<div class="ka-card" role="dialog" aria-modal="true" aria-label="Cuenta de Kelo World"></div>';document.body.appendChild(root)}card=root.querySelector('.ka-card')||root.firstElementChild;if(!card){card=document.createElement('div');card.className='ka-card';card.setAttribute('role','dialog');card.setAttribute('aria-modal','true');card.setAttribute('aria-label','Cuenta de Kelo World');root.appendChild(card)}if(!root.__keloBound){root.__keloBound=true;root.addEventListener('pointerdown',e=>e.stopPropagation(),true);root.addEventListener('pointerup',e=>e.stopPropagation(),true);root.addEventListener('touchstart',e=>e.stopPropagation(),{capture:true,passive:true});root.addEventListener('keydown',e=>e.stopPropagation(),true)}return root}
function setMessage(text,type){message=card&&card.querySelector('.ka-msg');if(!message)return;message.textContent=text||'';message.className='ka-msg'+(type?' '+type:'')}
function values(){const q=s=>card.querySelector(s);return{name:q('[name="name"]')?.value||'',email:q('[name="email"]')?.value||'',password:q('[name="password"]')?.value||''}}
function reloadSoon(){setMessage('Entrando a Kelo World…','ok');setTimeout(()=>location.reload(),180)}
function errorText(error){const raw=String(error?.message||error||'Error');const map={EMAIL_AND_PASSWORD_REQUIRED:'Escribe un email y una contraseña de al menos 6 caracteres.',EMAIL_REQUIRED:'Escribe tu email.',PASSWORD_TOO_SHORT:'La contraseña debe tener al menos 6 caracteres.',GUEST_ACCOUNT_MUST_BE_PROTECTED_OR_SEPARATED:'Este invitado ya tiene progreso. Protégelo por email o entra a una cuenta existente para no mezclar identidades.',ANONYMOUS_SESSION_REQUIRED:'Esta sesión ya no es de invitado.'};return map[raw]||raw.replace(/_/g,' ').toLowerCase()}
async function run(fn){if(busy)return;busy=true;card.querySelectorAll('button').forEach(x=>x.disabled=true);setMessage('Procesando…');try{await fn()}catch(error){setMessage(errorText(error),'err')}finally{busy=false;card.querySelectorAll('button').forEach(x=>x.disabled=false)}}
function permanent(state){return !!(state?.authenticated&&!state?.isAnonymous)}
function showChip(state){let chip=document.getElementById('kelo-account-chip');if(!permanent(state)){chip?.remove();return}if(!chip){chip=document.createElement('button');chip.id='kelo-account-chip';chip.className='ka-account-chip';document.body.appendChild(chip);chip.addEventListener('click',()=>render('account',api().state()));}chip.textContent=state.characterName||'Cuenta'}
function guestIntro(state){return `<div class="ka-guest"><strong>Estás jugando como invitado</strong>Tu personaje existe, pero esta sesión no es una cuenta recuperable. Si cambias de teléfono o borras los datos del navegador podrías perder acceso.</div>`}
function shell(body,tabs=true){return `<div class="ka-mark">KW</div><div class="ka-title">KELO WORLD</div><div class="ka-sub">Tu cuenta guarda la identidad del personaje y permite recuperar tu progreso en otros dispositivos.</div>${tabs?`<div class="ka-tabs"><button class="ka-tab ${mode==='login'?'is-on':''}" data-mode="login">Entrar</button><button class="ka-tab ${mode==='register'?'is-on':''}" data-mode="register">Crear cuenta</button></div>`:''}${body}<div class="ka-msg" aria-live="polite"></div>`}
function loginBody(state){return `${state?.isAnonymous?guestIntro(state):''}<div class="ka-field"><label class="ka-label">Email</label><input class="ka-input" name="email" type="email" autocomplete="email" inputmode="email" placeholder="tu@email.com"></div><div class="ka-field"><label class="ka-label">Contraseña</label><input class="ka-input" name="password" type="password" autocomplete="current-password" placeholder="••••••••"></div><div class="ka-actions"><button class="ka-primary" data-action="login">Entrar</button><button class="ka-secondary" data-action="magic">Enviar enlace de acceso</button>${state?.isAnonymous?'<button class="ka-ghost" data-action="continue-guest">Continuar como invitado</button>':'<button class="ka-ghost" data-action="guest">Jugar como invitado</button>'}</div><button class="ka-ghost" data-action="reset">Olvidé mi contraseña</button><div class="ka-note">Una cuenta permanente carga el mismo personaje y sus datos durables desde Supabase. Entrar a una cuenta existente desde un invitado carga el progreso de esa cuenta; no fusiona ambos automáticamente.</div>`}
function registerBody(state){if(state?.isAnonymous)return `${guestIntro(state)}<div class="ka-field"><label class="ka-label">Nombre del personaje</label><input class="ka-input" name="name" maxlength="24" autocomplete="nickname" value="${esc(state.characterName||'Kelo')}"></div><div class="ka-field"><label class="ka-label">Email para proteger este invitado</label><input class="ka-input" name="email" type="email" autocomplete="email" inputmode="email" placeholder="tu@email.com"></div><div class="ka-actions"><button class="ka-primary" data-action="protect-guest">Proteger este progreso</button><button class="ka-secondary" data-action="new-account-warning">Crear una cuenta nueva separada</button><button class="ka-ghost" data-action="continue-guest">Seguir como invitado</button></div><div class="ka-note">“Proteger este progreso” intenta enlazar un email al mismo usuario invitado para conservar el mismo characterId. Si el proyecto aún no permite enlazado manual, no se borrará nada y te lo indicaremos.</div>`;
return `<div class="ka-field"><label class="ka-label">Nombre del personaje</label><input class="ka-input" name="name" maxlength="24" autocomplete="nickname" placeholder="Kelo"></div><div class="ka-field"><label class="ka-label">Email</label><input class="ka-input" name="email" type="email" autocomplete="email" inputmode="email" placeholder="tu@email.com"></div><div class="ka-field"><label class="ka-label">Contraseña</label><input class="ka-input" name="password" type="password" autocomplete="new-password" placeholder="Mínimo 6 caracteres"></div><div class="ka-actions"><button class="ka-primary" data-action="register">Crear cuenta</button><button class="ka-ghost" data-action="guest">Jugar como invitado</button></div><div class="ka-note">Si la confirmación de email está activa, recibirás un correo antes de entrar. La contraseña nunca se guarda en Kelo World: la gestiona Supabase Auth.</div>`}
function accountBody(state){return `<div class="ka-guest"><strong>${esc(state.characterName||'Personaje')}</strong>${esc(state.email||'Cuenta conectada')}<br>Character ID: ${esc(String(state.characterId||'').slice(0,8))}…</div><div class="ka-actions"><button class="ka-secondary" data-action="change-password">Cambiar contraseña</button><button class="ka-ghost" data-action="close">Volver al juego</button><button class="ka-ghost" data-action="logout">Cerrar sesión</button></div><div class="ka-note">Tu identidad de cuenta está separada del personaje. Los datos del juego se guardan por characterId con permisos RLS.</div>`}
function passwordBody(state){return `<div class="ka-guest"><strong>Protege tu cuenta</strong>${esc(state.email||'Email confirmado')}</div><div class="ka-field"><label class="ka-label">Nueva contraseña</label><input class="ka-input" name="password" type="password" autocomplete="new-password" placeholder="Mínimo 6 caracteres"></div><div class="ka-actions"><button class="ka-primary" data-action="set-password">Guardar contraseña</button><button class="ka-ghost" data-action="close">Ahora no</button></div>`}
function bind(state){card.querySelectorAll('[data-mode]').forEach(btn=>btn.addEventListener('click',()=>{mode=btn.dataset.mode;render(mode,state)}));card.querySelectorAll('[data-action]').forEach(btn=>btn.addEventListener('click',()=>handle(btn.dataset.action,state)))}
async function handle(action,state){const auth=api();if(!auth)return setMessage('Auth no está disponible.','err');const v=values();if(action==='close'){hide();return}if(action==='continue-guest'){enterLocalPlay();return}if(action==='login')return run(async()=>{await auth.signInWithPassword(v.email,v.password);reloadSoon()});if(action==='register')return run(async()=>{const result=await auth.signUp(v.email,v.password,v.name);if(result.confirmationRequired)setMessage('Cuenta creada. Revisa tu email para confirmar y luego vuelve a Kelo World.','ok');else reloadSoon()});if(action==='guest')return run(async()=>{try{await auth.signInAsGuest();reloadSoon()}catch(error){if(anonymousDisabled(error)){enterLocalPlay();return}throw error}});if(action==='magic')return run(async()=>{await auth.signInWithOtp(v.email);setMessage('Te enviamos un enlace de acceso. Revisa tu email.','ok')});if(action==='reset')return run(async()=>{await auth.resetPassword(v.email);setMessage('Te enviamos un enlace para recuperar la contraseña.','ok')});if(action==='protect-guest')return run(async()=>{await auth.protectGuestWithEmail(v.email,v.name);try{localStorage.setItem(UPGRADE_PENDING,String(v.email||'').trim())}catch(_){}setMessage('Revisa tu email. Al confirmar, volverás con el mismo personaje y podrás fijar una contraseña.','ok')});if(action==='new-account-warning'){setMessage('Para no perder este invitado, primero protégelo o abre Kelo World en otro navegador para crear una cuenta nueva.','err');return}if(action==='logout')return run(async()=>{await auth.signOut();location.reload()});if(action==='change-password'){render('password',state);return}if(action==='set-password')return run(async()=>{await auth.setPassword(v.password);try{localStorage.removeItem(UPGRADE_PENDING)}catch(_){}setMessage('Contraseña guardada. Tu cuenta ya es recuperable.','ok');setTimeout(()=>{hide();showChip(api().state())},350)})}
function render(nextMode,state){ensureRoot();lastState=state||api()?.state()||{};mode=nextMode==='register'?'register':nextMode==='account'?'account':nextMode==='password'?'password':'login';let body=mode==='login'?loginBody(lastState):mode==='register'?registerBody(lastState):mode==='account'?accountBody(lastState):passwordBody(lastState);card.innerHTML=shell(body,mode==='login'||mode==='register');root.hidden=false;bind(lastState);setTimeout(()=>card.querySelector('input')?.focus({preventScroll:true}),50)}
function hide(){try{var p=window.KeloEngineBoot&&window.KeloEngineBoot.start&&window.KeloEngineBoot.start();if(p&&typeof p.then==='function'){p.then(function(){if(root)root.hidden=true}).catch(function(){if(root)root.hidden=true});return}}catch(_){}if(root)root.hidden=true}
let painted=false;async function boot(){ensureRoot();if(explicitEditorMode()){hide();try{window.KeloGuestPlay?.sync?.()}catch(_){}return}if(!painted){painted=true;render('login',api()?.state()||{})}const auth=api();if(!auth){setTimeout(boot,80);return}try{await auth.ready(1800)}catch(_){}const state=auth.state()||{};lastState=state;showChip(state);if(explicitEditorMode()){hide();try{window.KeloGuestPlay?.sync?.()}catch(_){}return}let pending='';try{pending=localStorage.getItem(UPGRADE_PENDING)||''}catch(_){}if(permanent(state)&&pending){render('password',state);return}if(!state.authenticated){render('login',state);return}if(state.isAnonymous){render('login',state);return}hide()}
window.addEventListener('kelo:online-auth-required',()=>{if(explicitEditorMode()){hide();try{window.KeloGuestPlay?.sync?.()}catch(_){}return}const state=api()?.state();if(state)render('login',state)});
window.addEventListener('kelo:online-auth-state',event=>{const state=event.detail||api()?.state();if(state)showChip(state)});
window.KeloAccountAuthUI=Object.freeze({version:VERSION,open:()=>render('login',api()?.state()),close:hide,state:()=>({mode,open:!!root&&!root.hidden,busy})});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();