/* KELO-INDEX
 * area: UI / INVENTORY
 * owner: KeloBackpackUI; input lock owner KeloInputLocks
 * keys: BACKPACK EQUIPMENT INVENTORY INPUT LOCK FOUNDATION WEAPON Q W E LOADOUT
 * purpose: presenta equipo/mochila, selector de skills del arma y reclama input mediante token del owner Foundation
 * public-api: KeloBackpackUI, KeloInventoryViewModel, KeloSocialUI.openBag/closeBag
 * consumes: KeloBackpack, KeloEquipment, KELO_EQUIPMENT_ABILITY_DATA, KeloInputLocks, KeloMarketUI, KeloWarehouseUI
 * state-owned: estado efímero de selección/filtros UI + token de lock de esta superficie
 * extension-points: APIs de Backpack/Equipment; KeloInputLocks acquire/release
 * reuse: selector Q/W/E usa KeloEquipment.get/setWeaponAbilityLoadout; UI jamás escribe combatAbilityKeys
 * legacy: globals openInventory/closeInventory/toggleInventory se conservan como aliases de compatibilidad
 * do-not: NO escribir KELO_MODAL_INPUT_LOCK, gameplay state, combatAbilityKeys o internals de inventory directamente
 */
(function(){
'use strict';
const VERSION='backpack-ui-v2.2.0';
const BASE_PLAYER_STATS=Object.freeze({hp:1250,mana:420,attack:150,defense:120,speed:110,crit:12,resistance:8,equipmentLevel:1,weaponLevel:1});
const DEFAULT_CURRENCIES=Object.freeze({silver:9223,gold:0,eGold:0});
const EQUIP_LAYOUT={
 helmet:{actual:'helmet',label:'Casco',empty:'⛑'},
 chest:{actual:'chest',label:'Pecho',empty:'♜'},
 gloves:{actual:'gloves',label:'Guantes',empty:'✥'},
 boots:{actual:'boots',label:'Botas',empty:'♟'},
 weapon:{actual:'weapon',label:'Arma',empty:'⚔'},
 cape:{actual:'accessory',label:'Capa / Accesorio',empty:'◢'},
 ring:{actual:'ring',label:'Anillo',empty:'◉'},
 amulet:{actual:'necklace',label:'Amuleto',empty:'✦'}
};
const LEFT=['helmet','chest','gloves','boots'],RIGHT=['weapon','cape','ring','amulet'];
const FILTERS=[['all','TODO'],['consumables','CONSUMIBLES'],['materials','MATERIALES'],['missions','MISIONES'],['others','OTROS']];
const WEAPON_SLOT_LABELS=['Q','W','E'];
let topTab='equipment',filter='all',selectedBag=null,selectedEquip=null,moveMode=false,splitMode=false,splitAmount=1,discardConfirm=false,isOpen=false,inputLockToken=null;

function toast(t){if(typeof showToast==='function')showToast(t);}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function rarityClass(v){return String(v||'common').toLowerCase().replace(/[^a-z0-9_-]/g,'');}
function normalizeCategory(d){const v=String((d&&d.category)||'').toLowerCase();if(/consum|potion|food/.test(v))return'consumables';if(/material|resource|craft/.test(v))return'materials';if(/mission|quest/.test(v))return'missions';return'others';}
function isEquipped(item){return !!(item&&window.KeloEquipment&&typeof window.KeloEquipment.isEquipped==='function'&&window.KeloEquipment.isEquipped(item.id));}
function resetModes(){moveMode=false;splitMode=false;splitAmount=1;discardConfirm=false;}
function ensurePanel(){let root=document.getElementById('kelo-bag');if(!root){root=document.createElement('div');root.id='kelo-bag';document.body.appendChild(root);}root.className='kb-overlay';root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');root.setAttribute('aria-label','Equipo y Mochila');return root;}
function getSlots(){return window.KeloBackpack?window.KeloBackpack.getSlots():[];}
function getEquippedMap(){const out={};if(window.KeloEquipment){window.KeloEquipment.getEquipped().forEach(function(item){out[item.slot]=item;});}return out;}
function describe(item,index){if(!item)return null;if(window.KeloBackpack&&typeof window.KeloBackpack.describeItem==='function')return window.KeloBackpack.describeItem(item,index||0);return{name:item.name||'Objeto',icon:item.icon||'▪',quantity:Math.max(1,Number(item.quantity)||1),rarity:item.rarity||item.tier||'common',category:item.kind||'item',bound:!!item.bound,stackable:Number(item.maxStack)>1};}
function getStats(){const s=Object.assign({},BASE_PLAYER_STATS),items=window.KeloEquipment?window.KeloEquipment.getEquipped():[];items.forEach(function(item){const f=window.KeloEquipment.finalStats(item)||{};s.hp+=Number(f.hp)||0;s.attack+=Number(f.attack)||0;s.defense+=Number(f.defense)||0;});const weapon=items.find(function(x){return x.slot==='weapon';});s.weaponLevel=weapon?Math.max(1,Number(weapon.itemLevel)||1):1;s.equipmentLevel=items.length?Math.max.apply(null,items.map(function(x){return Math.max(1,Number(x.itemLevel)||1);})):1;return s;}
function getCurrencies(){const out=Object.assign({},DEFAULT_CURRENCIES);if(typeof STATE!=='undefined'){if(Number.isFinite(Number(STATE.silver)))out.silver=Number(STATE.silver);if(Number.isFinite(Number(STATE.gold)))out.gold=Number(STATE.gold);if(Number.isFinite(Number(STATE.eGold)))out.eGold=Number(STATE.eGold);}return out;}
function equipIcon(item,d){return (d&&d.icon)||(item&&item.icon)||'◆';}
function statRow(icon,label,value,suffix){return '<div class="kb-stat"><span class="kb-stat-icon">'+icon+'</span><span>'+label+'</span><span class="kb-stat-value">'+esc(value)+(suffix||'')+'</span></div>';}
function equipmentSlot(key,equipped){const meta=EQUIP_LAYOUT[key],item=equipped[meta.actual]||null,d=item?describe(item,0):null;return '<div class="kb-equip-slot-wrap"><button type="button" class="kb-equip-slot '+(item?'equipped':'empty')+(selectedEquip===key?' selected':'')+'" data-equip-key="'+key+'" aria-label="'+esc(meta.label+(item?': '+d.name:' vacío'))+'"><span class="kb-equip-icon">'+esc(item?equipIcon(item,d):meta.empty)+'</span></button><div class="kb-equip-label">'+esc(meta.label)+'</div></div>';}
function abilityDefinition(key){return window.KELO_EQUIPMENT_ABILITY_DATA?.getAbility?.(key)||null;}
function weaponSkillMeta(def){if(!def)return'';const bits=[];if(def.role)bits.push(String(def.role));if(Number.isFinite(Number(def.cooldown)))bits.push(Number(def.cooldown).toFixed(Number(def.cooldown)%1?1:0)+'s');return bits.join(' · ');}
function applyWeaponChoice(item,slotIndex,key){const equipment=window.KeloEquipment,loadout=equipment?.getWeaponAbilityLoadout?.(item.id);if(!loadout?.ok)return;const keys=loadout.abilityKeys.slice();keys[slotIndex]=key;const out=equipment.setWeaponAbilityLoadout(item.id,keys);if(out?.ok){toast('Habilidad '+WEAPON_SLOT_LABELS[slotIndex]+' actualizada');render();return;}if(out?.error==='ONLINE_AUTHORITY_REQUIRED')toast('Online: el servidor debe aprobar cambios de habilidades');else toast('No se pudo cambiar la habilidad');}
function appendWeaponSkillEditor(detail,item){
 if(!detail||!item||item.slot!=='weapon'||!window.KeloEquipment?.getWeaponAbilityLoadout)return;
 const loadout=window.KeloEquipment.getWeaponAbilityLoadout(item.id);if(!loadout?.ok)return;
 const data=window.KELO_EQUIPMENT_ABILITY_DATA,box=document.createElement('div');box.className='kb-inline kb-weapon-skills';box.setAttribute('data-weapon-skill-editor',item.id);
 const title=document.createElement('div');title.className='kb-card-title';title.textContent='HABILIDADES DEL ARMA · '+loadout.profileName;box.appendChild(title);
 const note=document.createElement('div');note.className='kb-move-note';note.textContent='Elige una opción permitida por slot. Tus 5 Stone no cambian.';box.appendChild(note);
 loadout.slotChoices.forEach(function(choices,slotIndex){const row=document.createElement('div');row.className='kb-inline';const label=document.createElement('div');label.innerHTML='<b>'+WEAPON_SLOT_LABELS[slotIndex]+'</b>';row.appendChild(label);const actions=document.createElement('div');actions.className='kb-actions';choices.forEach(function(key){const def=data?.getAbility?.(key)||abilityDefinition(key),button=document.createElement('button');button.type='button';button.className='kb-action'+(loadout.abilityKeys[slotIndex]===key?' primary':'');button.dataset.weaponSlot=WEAPON_SLOT_LABELS[slotIndex];button.dataset.abilityKey=key;button.setAttribute('aria-pressed',loadout.abilityKeys[slotIndex]===key?'true':'false');button.innerHTML=esc((def?.icon||'◆')+' '+(def?.name||key))+(weaponSkillMeta(def)?'<small> · '+esc(weaponSkillMeta(def))+'</small>':'');button.onclick=function(){applyWeaponChoice(item,slotIndex,key);};actions.appendChild(button);});row.appendChild(actions);box.appendChild(row);});
 if(loadout.customized){const reset=document.createElement('button');reset.type='button';reset.className='kb-action';reset.textContent='RESTABLECER HABILIDADES';reset.onclick=function(){const out=window.KeloEquipment.resetWeaponAbilityLoadout(item.id);if(out?.ok){toast('Habilidades restauradas');render();}else if(out?.error==='ONLINE_AUTHORITY_REQUIRED')toast('Online: el servidor debe aprobar cambios de habilidades');};box.appendChild(reset);}
 detail.appendChild(box);
}
function renderTop(){if(topTab==='appearance')return '<section class="kb-appearance"><div class="kb-card-title">APARIENCIA</div><div class="kb-appearance-copy">La apariencia es cosmética y está separada de Equipo. No modifica atributos.</div><div class="kb-appearance-grid">'+['Cabello','Rostro','Cuerpo','Ropa','Accesorios','Colores'].map(function(x){return '<button class="kb-look-option" disabled>'+x+' · próximamente</button>';}).join('')+'</div></section>';
 const eq=getEquippedMap(),st=getStats();return '<div class="kb-equipment-view"><section class="kb-character-zone"><div class="kb-equip-column">'+LEFT.map(function(k){return equipmentSlot(k,eq);}).join('')+'</div><div class="player-preview"><img src="assets/hero.PNG" alt="Vista del personaje"></div><div class="kb-equip-column">'+RIGHT.map(function(k){return equipmentSlot(k,eq);}).join('')+'</div></section><aside class="kb-stats-card"><div class="kb-card-title">ATRIBUTOS</div>'+statRow('♥','Vida',st.hp)+statRow('◆','Mana',st.mana)+statRow('⚔','Ataque',st.attack)+statRow('◈','Defensa',st.defense)+statRow('➤','Velocidad',st.speed)+statRow('✦','Crítico',st.crit,'%')+statRow('⬟','Resistencia',st.resistance,'%')+'<div class="kb-levels"><div class="kb-level"><span>Nivel de Equipo</span><b>'+esc(st.equipmentLevel)+'</b></div><div class="kb-level"><span>Nivel de Arma</span><b>'+esc(st.weaponLevel)+'</b></div></div></aside></div>';}
function renderDetail(root){const detail=root.querySelector('.kb-detail');if(!detail)return;
 if(selectedEquip){const meta=EQUIP_LAYOUT[selectedEquip],item=getEquippedMap()[meta.actual];if(!item){detail.innerHTML='<div class="kb-empty-detail">'+esc(meta.label)+' vacío.</div>';return;}const d=describe(item,0);detail.innerHTML='<div class="kb-name">'+esc(d.icon)+' '+esc(d.name)+'</div><div class="kb-meta">'+esc(d.rarity)+' · '+esc(meta.label)+' · Equipado</div><div class="kb-actions"><button type="button" class="kb-action primary kb-unequip-selected">DESEQUIPAR</button></div>';detail.querySelector('.kb-unequip-selected').onclick=function(){const out=window.KeloEquipment.unequipItem(meta.actual);if(out&&out.ok){selectedEquip=null;toast('Objeto desequipado');render();}};appendWeaponSkillEditor(detail,item);return;}
 const slots=getSlots(),slot=selectedBag==null?null:slots[selectedBag];if(!slot||!slot.item){detail.innerHTML='<div class="kb-empty-detail">Selecciona un objeto para ver sus datos.</div>';return;}const d=slot.descriptor||describe(slot.item,slot.index);detail.innerHTML='<div class="kb-name">'+esc(d.icon)+' '+esc(d.name)+'</div><div class="kb-meta">'+[d.rarity,d.category,d.quantity>1?'x'+d.quantity:null,d.bound?'Vinculado':'No vinculado',isEquipped(slot.item)?'Equipado':null].filter(Boolean).map(esc).join(' · ')+'</div><div class="kb-desc">'+esc(slot.item.description||'Objeto de Kelo World. Sus propiedades y acciones se leen del estado real del inventario.')+'</div><div class="kb-actions"></div>'+(moveMode?'<div class="kb-move-note">Toca otro slot para mover, intercambiar o combinar.</div>':'');const actions=detail.querySelector('.kb-actions');
 if(d.category==='equipment'&&window.KeloEquipment){const equipped=isEquipped(slot.item),b=document.createElement('button');b.className='kb-action primary';b.textContent=equipped?'DESEQUIPAR':'EQUIPAR';b.onclick=function(){const out=equipped?window.KeloEquipment.unequipItem(slot.item.slot):window.KeloEquipment.equipItem(slot.item.id);if(out&&out.ok){toast(equipped?'Objeto desequipado':'Objeto equipado');render();}};actions.appendChild(b);}
 const move=document.createElement('button');move.className='kb-action';move.textContent=moveMode?'CANCELAR MOVER':'MOVER';move.onclick=function(){moveMode=!moveMode;splitMode=false;discardConfirm=false;render();};actions.appendChild(move);
 if(d.stackable&&d.quantity>1){const split=document.createElement('button');split.className='kb-action';split.textContent=splitMode?'CANCELAR DIVIDIR':'DIVIDIR';split.onclick=function(){splitMode=!splitMode;moveMode=false;discardConfirm=false;splitAmount=Math.min(Math.max(1,splitAmount),d.quantity-1);render();};actions.appendChild(split);}
 if(d.category!=='equipment'&&!d.bound){const discard=document.createElement('button');discard.className='kb-action danger';discard.textContent=discardConfirm?'CANCELAR':'DESCARTAR';discard.onclick=function(){discardConfirm=!discardConfirm;moveMode=false;splitMode=false;render();};actions.appendChild(discard);}
 appendWeaponSkillEditor(detail,slot.item);
 if(splitMode&&d.stackable&&d.quantity>1){const box=document.createElement('div');box.className='kb-inline';box.innerHTML='<div>Dividir stack · se usará el primer espacio libre.</div><div class="kb-stepper"><button class="kb-minus">−</button><span class="kb-step-value">'+splitAmount+'</span><button class="kb-plus">+</button><button class="kb-action primary kb-split-go">SEPARAR</button></div>';box.querySelector('.kb-minus').onclick=function(){splitAmount=Math.max(1,splitAmount-1);render();};box.querySelector('.kb-plus').onclick=function(){splitAmount=Math.min(d.quantity-1,splitAmount+1);render();};box.querySelector('.kb-split-go').onclick=function(){const free=getSlots().find(function(s){return !s.item;});if(!free){toast('No hay espacio libre');return;}const out=window.KeloBackpack.splitStack(slot.index,free.index,splitAmount);if(out.ok){selectedBag=free.index;resetModes();toast('Stack dividido');render();}};detail.appendChild(box);}
 if(discardConfirm&&d.category!=='equipment'&&!d.bound){const box=document.createElement('div');box.className='kb-inline';box.innerHTML='<div>Esta acción elimina '+(d.quantity>1?'el stack completo x'+d.quantity:'este objeto')+'.</div><div class="kb-actions"><button class="kb-action danger kb-discard-go">CONFIRMAR DESCARTE</button></div>';box.querySelector('.kb-discard-go').onclick=function(){const out=window.KeloBackpack.discardSlot(slot.index);if(out.ok){selectedBag=null;resetModes();toast('Objeto descartado');render();}};detail.appendChild(box);}
}
function render(){const root=ensurePanel();if(!window.KeloBackpack){root.innerHTML='<div class="kb-shell"><div class="kb-empty-detail">Backpack cargando…</div></div>';return;}const slots=getSlots(),stats=window.KeloBackpack.getStats(),curr=getCurrencies();if(selectedBag!=null&&(selectedBag<0||selectedBag>=slots.length))selectedBag=null;
 root.innerHTML='<div class="kb-shell"><header class="kb-top"><button type="button" class="kb-main-tab '+(topTab==='equipment'?'active':'')+'" data-top="equipment">⚔ EQUIPO</button><button type="button" class="kb-main-tab '+(topTab==='appearance'?'active':'')+'" data-top="appearance">♟ APARIENCIA</button><button type="button" class="kb-close" aria-label="Cerrar">×</button></header><div class="kb-scroll">'+renderTop()+'<nav class="kb-category-tabs">'+FILTERS.map(function(x){return '<button type="button" class="kb-category '+(filter===x[0]?'active':'')+'" data-filter="'+x[0]+'">'+x[1]+'</button>';}).join('')+'</nav><div class="kb-grid" role="grid" aria-label="Mochila"></div><div class="kb-detail"></div><footer class="kb-bottom"><div class="kb-organize-row"><button type="button" class="kb-sort">☰ ORGANIZAR</button><div class="kb-count">Espacios&nbsp; <b>'+stats.used+' / '+stats.capacity+'</b></div><button type="button" class="kb-expand" disabled aria-label="Expansión futura">+</button></div><div class="kb-currencies"><div class="kb-currency"><span class="coin">◉</span>PLATA<b>'+Number(curr.silver).toLocaleString()+'</b></div><div class="kb-currency"><span class="coin">●</span>ORO<b>'+Number(curr.gold).toLocaleString()+'</b></div><div class="kb-currency"><span class="coin">♛</span>E-GOLD<b>'+Number(curr.eGold).toLocaleString()+'</b></div></div></footer></div></div>';
 root.querySelector('.kb-close').onclick=close;root.querySelectorAll('.kb-main-tab').forEach(function(b){b.onclick=function(){topTab=b.dataset.top;selectedEquip=null;render();};});root.querySelectorAll('.kb-category').forEach(function(b){b.onclick=function(){filter=b.dataset.filter;selectedBag=null;resetModes();render();};});root.querySelector('.kb-sort').onclick=function(){window.KeloBackpack.sortSlots();selectedBag=null;resetModes();toast('Mochila organizada');render();};
 root.querySelectorAll('.kb-equip-slot').forEach(function(b){b.onclick=function(){selectedEquip=b.dataset.equipKey;selectedBag=null;resetModes();render();};});
 const grid=root.querySelector('.kb-grid');slots.forEach(function(slot){const d=slot.descriptor,cat=d?normalizeCategory(d):null,visible=filter==='all'||cat===filter,btn=document.createElement('button');btn.type='button';btn.dataset.slot=String(slot.index);btn.className='kb-slot'+(selectedBag===slot.index?' selected':'')+(moveMode&&selectedBag!==slot.index?' move-target':'')+(slot.item&&isEquipped(slot.item)?' equipped':'')+(!visible?' filtered-empty':'');btn.setAttribute('aria-label',d&&visible?'Slot '+(slot.index+1)+': '+d.name:'Slot '+(slot.index+1)+' vacío');if(d&&visible){btn.innerHTML='<span class="kb-rarity '+rarityClass(d.rarity)+'"></span><span class="kb-icon">'+esc(d.icon)+'</span>'+(d.quantity>1?'<span class="kb-qty">'+esc(d.quantity)+'</span>':'');}btn.onclick=function(){onSlot(slot.index,visible);};grid.appendChild(btn);});renderDetail(root);if(window.KeloMarketUI&&typeof window.KeloMarketUI.decorateBackpack==='function')queueMicrotask(window.KeloMarketUI.decorateBackpack);}
function onSlot(index,visible){if(!visible&&filter!=='all')return;if(moveMode&&selectedBag!=null&&index!==selectedBag){const out=window.KeloBackpack.moveSlot(selectedBag,index);if(out.ok){selectedBag=out.merged?(out.sourceRemaining>0?selectedBag:index):index;moveMode=false;toast(out.merged?'Stacks combinados':'Objeto movido');render();}return;}if(moveMode&&index===selectedBag){moveMode=false;render();return;}const slot=getSlots()[index];selectedBag=slot&&slot.item?index:null;selectedEquip=null;resetModes();render();}
function acquireInputLock(){const locks=window.KeloInputLocks;if(!inputLockToken&&locks&&typeof locks.acquire==='function')inputLockToken=locks.acquire('backpack-ui',{surface:'inventory'});document.body.classList.add('kelo-inventory-open');return !!inputLockToken;}
function releaseInputLock(){const locks=window.KeloInputLocks;if(inputLockToken&&locks&&typeof locks.release==='function')locks.release(inputLockToken);inputLockToken=null;document.body.classList.remove('kelo-inventory-open');}
function open(){if(typeof closeMenu==='function')closeMenu();if(window.KeloWarehouseUI)window.KeloWarehouseUI.close();if(window.KeloMarketUI)window.KeloMarketUI.close();selectedBag=null;selectedEquip=null;resetModes();topTab='equipment';render();ensurePanel().style.display='block';isOpen=true;acquireInputLock();}
function close(){const root=document.getElementById('kelo-bag');if(root)root.style.display='none';selectedBag=null;selectedEquip=null;resetModes();isOpen=false;releaseInputLock();}
function toggle(){isOpen?close():open();}
function onKey(e){if(e.key==='Escape'&&isOpen){e.preventDefault();close();}}
if(!window.__KELO_INVENTORY_ESC_BOUND){window.addEventListener('keydown',onKey);window.__KELO_INVENTORY_ESC_BOUND=true;}
const previous=window.KeloSocialUI||{};window.KeloSocialUI=Object.freeze(Object.assign({},previous,{openBag:open,closeBag:close}));window.openInventory=open;window.closeInventory=close;window.toggleInventory=toggle;
window.KeloInventoryViewModel=Object.freeze({basePlayerStats:BASE_PLAYER_STATS,defaultCurrencies:DEFAULT_CURRENCIES,getPlayerStats:getStats,getCurrencies:getCurrencies,equipmentLayout:Object.freeze(Object.assign({},EQUIP_LAYOUT))});
window.KeloBackpackUI=Object.freeze({version:VERSION,open,close,toggle,render,isOpen:function(){return isOpen;}});
window.KELO_BACKPACK_UI_AUDIT=Object.freeze({version:VERSION,layout:'fantasy-equipment-inventory-v1',mobileFirst:true,mainTabs:['equipment','appearance'],visibleEquipmentSlots:8,inventoryFilters:5,slotTargetMinPx:48,tapFirst:true,dragDrop:false,inputLock:true,inputLockOwner:'KeloInputLocks',inputLockTokenized:true,directLegacyModalWrite:false,noSkillBar:true,realBackpackState:true,realEquipmentActions:true,appearanceCosmeticOnly:true,marketDecoratorCompatible:true,weaponSkillSelection:true,weaponSkillSelectionInsideDetail:true,equipmentOwnerForWeaponLoadout:true,directCombatAbilityWrites:false,onlineAuthorityFailureSurfaced:true,authorityBoundary:'ui-requests-existing-domain-operations'});
})();