/* KELO-INDEX
 * area: UI / MENU HUD CHAT
 * owner: Kelo Luxe Shell presentation
 * keys: MENU PREMIUM MOBILE NAVIGATION INPUT LOCK CHARACTER MOUNTS NOBILITY TITLES EMOTES
 * purpose: presenta el HUD Luxe y el menú principal premium consumiendo únicamente APIs públicas de owners existentes
 * public-api: KELO_LUXE.toggleMenu/closeMenu/isMenuOpen/closeChat/renderMenu
 * consumes: KeloInputLocks + Backpack/Abilities/Character/Mounts/Market/House/Nobility/Titles/Emotes owners + legacy profile/chat adapters
 * state-owned: apertura del menú/chat y tokens de input de estas superficies
 * extension-points: botones owner-backed; CREATORS conserva su launcher tardío sobre .lx-menu-grid
 * reuse: shell visible único del menú móvil actual
 * legacy: openSocialTool/inspectPlayer solo como adapters de compatibilidad donde todavía son el route LIVE
 * do-not: NO gameplay state, NO rutas fake, NO polling/setInterval, NO segundo menú
 * online: navegación solamente; autoridad permanece en cada owner (mounts/market/nobility/titles/property/etc.)
 */
(function(){
'use strict';
if(document.getElementById('kelo-luxe'))return;
const VERSION='luxe-shell-v4.0.4-mount-menu';
const locks=window.KeloInputLocks;
let menuLockToken=null,chatLockToken=null;
const MENU_ENTRIES=Object.freeze([
{id:'bag',label:'Mochila',sub:'Tu inventario',icon:'▣'},
{id:'abilities',label:'Habilidades',sub:'Mejora tu poder',icon:'✦'},
{id:'appearance',label:'Apariencia',sub:'Personaliza tu personaje',icon:'♙'},
{id:'mounts',label:'Monturas',sub:'Equipa · monta · M1/M2/M3',icon:'♞'},
{id:'profile',label:'Perfil',sub:'Tu información',icon:'◈'},
{id:'market',label:'Mercado',sub:'Compra y vende',icon:'⚖'},
{id:'chat',label:'Chat',sub:'Habla con la comunidad',icon:'●'},
{id:'properties',label:'Propiedades',sub:'Tu tierra y edificios',icon:'⌂'},
{id:'nobility',label:'Nobleza',sub:'Caballero · Rey',icon:'♛',accent:true},
{id:'titles',label:'Libro de títulos',sub:'Logros · identidad · prestigio',icon:'▤',accent:true},
{id:'emotes',label:'Burlas',sub:'Emotes y gestos',icon:'☻'},
{id:'missions',label:'Misiones',sub:'Aventuras y desafíos',icon:'✧',optional:true},
{id:'settings',label:'Ajustes',sub:'Configura tu experiencia',icon:'⚙',optional:true}
]);
function toast(m){if(typeof window.showToast==='function')window.showToast(m);else console.info('[Kelo Luxe]',m);}
function acquire(owner,meta){return locks&&typeof locks.acquire==='function'?locks.acquire(owner,meta):null;}
function release(token){if(token&&locks&&typeof locks.release==='function')locks.release(token);}
function claimMenuLock(){if(!menuLockToken)menuLockToken=acquire('luxe-main-menu',{surface:'main-menu'});return !!menuLockToken;}
function releaseMenuLock(){const t=menuLockToken;menuLockToken=null;release(t);}
function claimChatLock(){if(!chatLockToken)chatLockToken=acquire('luxe-chat',{surface:'chat'});return !!chatLockToken;}
function releaseChatLock(){const t=chatLockToken;chatLockToken=null;release(t);}
const style=document.createElement('style');style.id='kelo-luxe-v4-style';style.textContent=`
:root{--lx-ink:#071013;--lx-forest:#173f36;--lx-gold:#e7c56a;--lx-ivory:#fff4d6;--lx-muted:#96aaa2}
.top-bar,#kelo-chat,#kelo-stones-btn,#kelo-bag-btn,#kelo-online,.lx-mark,#kelo-minimap,.kelo-minimap,#minimap{display:none!important}
#kelo-luxe{position:absolute;inset:0;z-index:80;pointer-events:none;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:var(--lx-ivory)}#kelo-luxe *{box-sizing:border-box}#kelo-luxe button,#kelo-luxe input{font:inherit}#kelo-luxe button{touch-action:manipulation;-webkit-tap-highlight-color:transparent}
.lx-top{position:absolute;top:max(8px,env(safe-area-inset-top));left:max(8px,env(safe-area-inset-left));right:max(8px,env(safe-area-inset-right));height:44px;display:flex;align-items:center;gap:7px;pointer-events:auto}.lx-gold{height:40px;min-width:104px;padding:0 13px;border-radius:15px;display:flex;align-items:center;gap:8px;background:linear-gradient(145deg,rgba(15,28,29,.96),rgba(7,15,18,.97));border:1px solid rgba(231,197,106,.55);box-shadow:0 8px 25px rgba(0,0,0,.3),inset 0 0 0 1px rgba(255,255,255,.035);font-size:14px;font-weight:850}.lx-gold-dot{width:11px;height:11px;transform:rotate(45deg);background:linear-gradient(135deg,#ffe49a,#c7922e);box-shadow:0 0 12px rgba(231,197,106,.34)}.lx-presence{height:32px;padding:0 10px;border-radius:999px;display:flex;align-items:center;gap:6px;background:rgba(8,18,20,.86);border:1px solid rgba(255,255,255,.09);font-size:10px;font-weight:750;color:#d7eadc}.lx-presence i{width:7px;height:7px;border-radius:50%;background:#7dd475;box-shadow:0 0 9px rgba(125,212,117,.58)}.lx-spacer{flex:1}.lx-top-btn{height:40px;padding:0 15px;border-radius:15px;border:1px solid rgba(231,197,106,.58);background:linear-gradient(145deg,rgba(22,45,39,.96),rgba(8,18,20,.97));color:#f2d57f;font-family:Georgia,serif;font-size:13px;font-weight:800;box-shadow:0 8px 25px rgba(0,0,0,.28),inset 0 0 0 1px rgba(255,255,255,.04)}.lx-top-btn:active{transform:scale(.97)}
.lx-rail{position:absolute;top:max(62px,calc(env(safe-area-inset-top) + 54px));right:max(8px,env(safe-area-inset-right));pointer-events:auto;display:flex;flex-direction:column;align-items:center;gap:9px}.lx-side-menu,.lx-side-pvp{position:relative;isolation:isolate;width:66px;height:66px;padding:5px;border-radius:20px;border:1px solid rgba(231,197,106,.62);background:linear-gradient(145deg,rgba(24,37,33,.98),rgba(6,14,16,.99));color:var(--lx-ivory);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;box-shadow:0 12px 30px rgba(0,0,0,.38),inset 0 0 0 1px rgba(255,255,255,.04);font-size:8px;font-weight:900;letter-spacing:.13em;overflow:hidden}.lx-side-menu:before,.lx-side-pvp:before{content:"";position:absolute;inset:-35%;z-index:-1;background:radial-gradient(circle,rgba(231,197,106,.15),transparent 58%)}.lx-side-menu b{color:var(--lx-gold);font-size:26px;line-height:21px;font-family:Georgia,serif;text-shadow:0 0 14px rgba(231,197,106,.3)}.lx-side-pvp{height:60px}.lx-side-pvp b{font-size:25px;line-height:21px}.lx-side-pvp span{color:var(--lx-gold)}.lx-side-menu:active,.lx-side-pvp:active{transform:scale(.95);border-color:#e7c56a}
.lx-menu-panel{display:none;position:absolute;z-index:87;top:max(62px,calc(env(safe-area-inset-top) + 54px));left:max(10px,env(safe-area-inset-left));right:max(82px,calc(env(safe-area-inset-right) + 74px));max-height:calc(100% - max(76px,calc(env(safe-area-inset-top) + 68px)) - max(10px,env(safe-area-inset-bottom)));padding:13px;border-radius:23px;background:linear-gradient(155deg,rgba(9,22,23,.965),rgba(4,11,14,.985) 70%);border:1px solid rgba(231,197,106,.68);box-shadow:0 24px 70px rgba(0,0,0,.52),inset 0 0 0 1px rgba(255,255,255,.035),inset 0 0 35px rgba(23,63,54,.14);backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px);pointer-events:auto;overflow:hidden}.lx-menu-panel:before{content:"";position:absolute;inset:4px;border:1px solid rgba(231,197,106,.12);border-radius:19px;pointer-events:none}.lx-menu-panel.open{display:flex;flex-direction:column;animation:lxMenuIn .16s ease-out}@keyframes lxMenuIn{from{opacity:0;transform:translateY(-5px) scale(.99)}to{opacity:1;transform:none}}
.lx-menu-head{position:relative;display:flex;align-items:center;justify-content:center;min-height:48px;margin:0 0 10px;padding:0 48px;border-bottom:1px solid rgba(231,197,106,.18);color:#f0d27d;font-family:Georgia,serif;font-size:22px;font-weight:850;letter-spacing:.13em;text-shadow:0 0 18px rgba(231,197,106,.17)}.lx-menu-head:after{content:"◆";position:absolute;bottom:-7px;left:50%;transform:translateX(-50%) rotate(45deg);font-family:serif;font-size:8px;color:var(--lx-gold);background:#091516;padding:1px 5px}.lx-menu-close{position:absolute;right:0;top:2px;width:44px;height:44px;border-radius:13px;border:1px solid rgba(231,197,106,.43);background:linear-gradient(145deg,#182527,#0a1518);color:#f5df9e;font-size:23px;font-weight:800;box-shadow:inset 0 0 0 1px rgba(255,255,255,.035)}.lx-menu-close:active{transform:scale(.95)}.lx-menu-scroll{position:relative;min-height:0;overflow:auto;overscroll-behavior:contain;-webkit-overflow-scrolling:touch;padding:2px 1px 5px;scrollbar-width:none}.lx-menu-scroll::-webkit-scrollbar{display:none}.lx-menu-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}
.lx-menu-item{position:relative;min-width:0;min-height:78px;padding:10px 18px 10px 8px;border-radius:15px;border:1px solid rgba(231,197,106,.28);background:linear-gradient(145deg,rgba(20,50,43,.58),rgba(7,19,21,.9));color:var(--lx-ivory);display:grid;grid-template-columns:32px minmax(0,1fr);align-items:center;gap:7px;text-align:left;box-shadow:inset 0 0 0 1px rgba(255,255,255,.018),0 7px 18px rgba(0,0,0,.18);transition:transform .12s ease,border-color .15s ease,background .15s ease}.lx-menu-item:after{content:"›";position:absolute;right:7px;top:50%;transform:translateY(-52%);color:rgba(231,197,106,.8);font-size:20px;font-family:Georgia,serif}.lx-menu-item:active{transform:scale(.975);border-color:rgba(231,197,106,.82);background:linear-gradient(145deg,rgba(35,70,58,.76),rgba(9,24,25,.96))}.lx-menu-item[data-accent="true"]{border-color:rgba(231,197,106,.55);background:radial-gradient(circle at 28% 35%,rgba(231,197,106,.1),transparent 42%),linear-gradient(145deg,rgba(28,49,40,.74),rgba(8,18,20,.96))}.lx-menu-icon{width:32px;height:32px;display:grid;place-items:center;border-radius:10px;border:1px solid rgba(231,197,106,.28);background:rgba(6,15,17,.68);color:#edcf76;font-family:Georgia,serif;font-size:19px;text-shadow:0 0 12px rgba(231,197,106,.2)}.lx-menu-copy{min-width:0;display:flex;flex-direction:column;gap:3px}.lx-menu-copy b{display:block;min-width:0;color:#fff8e8;font-family:Georgia,serif;font-size:12px;line-height:1.08;white-space:normal;overflow:visible;text-overflow:clip;word-break:normal}.lx-menu-copy small{display:block;min-width:0;color:#91a39c;font-size:7.5px;line-height:1.25;white-space:normal}.lx-menu-item[data-accent="true"] .lx-menu-copy small{color:#e7c56a}
.lx-chat-drawer{display:none;position:absolute;left:max(8px,env(safe-area-inset-left));right:max(8px,env(safe-area-inset-right));bottom:max(70px,calc(env(safe-area-inset-bottom) + 62px));z-index:88;padding:10px;border-radius:16px;background:rgba(7,17,20,.97);border:1px solid rgba(231,197,106,.42);box-shadow:0 16px 40px rgba(0,0,0,.4);backdrop-filter:blur(12px);pointer-events:auto}.lx-chat-drawer.open{display:block}.lx-chat-head{display:flex;align-items:center;justify-content:space-between;padding:0 2px 7px;color:#e7c56a;font:900 10px/1 Georgia,serif;letter-spacing:.12em}.lx-chat-close{width:36px;height:36px;border-radius:10px;border:1px solid rgba(231,197,106,.35);background:#101d20;color:#f5df9e;font-size:20px}.lx-log{height:70px;overflow:auto;padding:3px 4px 8px;color:#e8ede8;font-size:11px;line-height:1.4}.lx-log:empty:before{content:'El chat aparecerá aquí';color:#789188}.lx-chat-form{display:flex;gap:6px}.lx-chat-form input{min-width:0;flex:1;height:40px;border-radius:11px;border:1px solid rgba(255,255,255,.1);background:#0b171a;color:#f6f2df;padding:0 11px;outline:none;user-select:text;-webkit-user-select:text}.lx-chat-form input:focus{border-color:rgba(231,197,106,.62)}.lx-chat-form button{height:40px;min-width:52px;border-radius:11px;border:1px solid rgba(231,197,106,.52);background:var(--lx-forest);color:var(--lx-gold);font-weight:900}
.action-bar{position:absolute!important;left:auto!important;right:max(10px,env(safe-area-inset-right))!important;bottom:max(10px,env(safe-area-inset-bottom))!important;transform:none!important;display:grid!important;grid-template-columns:repeat(5,44px)!important;grid-template-rows:44px!important;gap:6px!important;width:auto!important;height:44px!important;z-index:84!important;pointer-events:auto!important}.action-bar .stone-slot,.action-bar .stone-slot.ultimate{grid-column:auto!important;grid-row:auto!important;width:44px!important;height:44px!important;border-radius:13px!important;border:1px solid rgba(231,197,106,.56)!important;background:rgba(11,22,24,.92)!important;color:var(--lx-gold)!important;box-shadow:0 7px 18px rgba(0,0,0,.22),inset 0 0 0 1px rgba(255,255,255,.035)!important;font-size:7px!important}.action-bar .stone-slot.ultimate{border-color:rgba(231,197,106,.88)!important;background:linear-gradient(145deg,rgba(25,55,45,.96),rgba(11,22,24,.96))!important}#kelo-bag,#kelo-builder{border-color:rgba(231,197,106,.45)!important;background:rgba(9,18,21,.97)!important;box-shadow:0 16px 36px rgba(0,0,0,.34)!important;color:#e8ede8!important}
@media(max-width:360px){.lx-presence{display:none}.lx-top-btn{padding:0 10px}.lx-side-menu,.lx-side-pvp{width:58px}.lx-side-menu{height:58px}.lx-side-pvp{height:54px}.lx-menu-panel{right:max(70px,calc(env(safe-area-inset-right) + 64px));padding:10px}.lx-menu-item{min-height:72px;padding-left:6px;padding-right:15px;grid-template-columns:28px minmax(0,1fr);gap:5px}.lx-menu-icon{width:28px;height:28px;font-size:16px}.lx-menu-copy b{font-size:10.5px}.lx-menu-copy small{font-size:6.8px}.action-bar{grid-template-columns:repeat(5,41px)!important;gap:5px!important}.action-bar .stone-slot,.action-bar .stone-slot.ultimate{width:41px!important;height:41px!important}}
@media(max-height:520px) and (orientation:landscape){.lx-top{height:36px}.lx-gold,.lx-top-btn{height:34px}.lx-rail{top:max(48px,calc(env(safe-area-inset-top) + 42px));gap:6px}.lx-side-menu,.lx-side-pvp{width:54px;height:50px;border-radius:15px}.lx-menu-panel{top:max(48px,calc(env(safe-area-inset-top) + 42px));bottom:max(8px,env(safe-area-inset-bottom));left:max(8px,env(safe-area-inset-left));right:max(68px,calc(env(safe-area-inset-right) + 62px));max-height:none;padding:9px}.lx-menu-head{min-height:36px;margin-bottom:7px;font-size:17px}.lx-menu-close{width:36px;height:36px;top:0}.lx-menu-grid{gap:6px}.lx-menu-item{min-height:58px;padding-top:7px;padding-bottom:7px}.lx-menu-icon{width:30px;height:30px;font-size:17px}.lx-menu-copy b{font-size:11px}.lx-menu-copy small{font-size:7px}.lx-chat-drawer{bottom:max(8px,env(safe-area-inset-bottom));left:72px}.lx-log{height:48px}}
`;document.head.appendChild(style);
const root=document.createElement('div');root.id='kelo-luxe';root.innerHTML=`<div class="lx-top"><div class="lx-gold"><span class="lx-gold-dot"></span><span id="lx-gold">Oro 0</span></div><div class="lx-presence"><i></i><span>online</span></div><div class="lx-spacer"></div><button class="lx-top-btn" id="lx-shop">Boutique</button></div><div class="lx-rail"><button class="lx-side-menu" id="lx-side-menu" aria-label="Abrir menú" aria-expanded="false"><b>◆</b><span>MENÚ</span></button><button class="lx-side-pvp" id="lx-side-pvp" aria-label="Entrar al mundo PvP"><b>⚔</b><span>PVP</span></button></div><section class="lx-menu-panel" id="lx-menu-panel" role="dialog" aria-modal="true" aria-labelledby="lx-menu-title" aria-hidden="true"><div class="lx-menu-head"><span id="lx-menu-title">MENÚ</span><button class="lx-menu-close" id="lx-menu-close" aria-label="Cerrar menú">×</button></div><div class="lx-menu-scroll"><div class="lx-menu-grid" id="lx-menu-grid"></div></div></section><div class="lx-chat-drawer" id="lx-chat-drawer" role="dialog" aria-label="Chat"><div class="lx-chat-head"><span>CHAT</span><button type="button" class="lx-chat-close" id="lx-chat-close" aria-label="Cerrar chat">×</button></div><div class="lx-log" id="lx-log"></div><form class="lx-chat-form" id="lx-form"><input id="lx-in" maxlength="80" placeholder="Escribe un mensaje…" autocomplete="off"><button>OK</button></form></div>`;document.body.appendChild(root);
const menuPanel=document.getElementById('lx-menu-panel'),menuButton=document.getElementById('lx-side-menu'),menuGrid=document.getElementById('lx-menu-grid'),chatDrawer=document.getElementById('lx-chat-drawer');
function optionalOwnerReady(id){if(id==='missions')return !!(window.KeloMissionsUI&&typeof window.KeloMissionsUI.open==='function');if(id==='settings')return !!(window.KeloSettingsUI&&typeof window.KeloSettingsUI.open==='function');return true;}
function card(e){return '<button type="button" class="lx-menu-item" data-tool="'+e.id+'"'+(e.accent?' data-accent="true"':'')+'><span class="lx-menu-icon" aria-hidden="true">'+e.icon+'</span><span class="lx-menu-copy"><b>'+e.label+'</b><small>'+e.sub+'</small></span></button>';}
function renderMenu(){const creators=document.getElementById('lx-create-studio');if(creators&&creators.parentNode===menuGrid)creators.remove();menuGrid.innerHTML=MENU_ENTRIES.filter(e=>!e.optional||optionalOwnerReady(e.id)).map(card).join('');if(creators)menuGrid.appendChild(creators);}
function closeChat(){chatDrawer.classList.remove('open');releaseChatLock();}
function openChat(){closeLuxeMenu();chatDrawer.classList.add('open');claimChatLock();requestAnimationFrame(()=>document.getElementById('lx-in')?.focus({preventScroll:true}));}
function setMenuOpen(force){const open=typeof force==='boolean'?force:!menuPanel.classList.contains('open');if(open){closeChat();renderMenu();claimMenuLock();updateGold();}else releaseMenuLock();menuPanel.classList.toggle('open',open);menuPanel.setAttribute('aria-hidden',String(!open));menuButton.setAttribute('aria-expanded',String(open));return open;}
function closeLuxeMenu(){return setMenuOpen(false);}
function runToolOpen(tool){if(tool==='bag'){if(window.KeloBackpackUI?.open)return window.KeloBackpackUI.open();if(window.KeloSocialUI?.openBag)return window.KeloSocialUI.openBag();}if(tool==='abilities'&&window.KeloAbilities?.openStonePanel)return window.KeloAbilities.openStonePanel();if(tool==='appearance'){if(window.KeloCharacterCustomizer?.open)return window.KeloCharacterCustomizer.open();toast('Apariencia todavía cargando');return;}if(tool==='mounts'){if(window.KeloMountPanel?.open)return window.KeloMountPanel.open();toast('Monturas todavía cargando');return;}if(tool==='profile'){if(typeof inspectPlayer==='function'&&typeof localPlayer!=='undefined')return inspectPlayer(localPlayer,true);}if(tool==='market'&&window.KeloMarketUI?.open)return window.KeloMarketUI.open();if(tool==='chat'){openChat();return;}if(tool==='properties'){if(window.KELO_HOUSE_UI?.show)return window.KELO_HOUSE_UI.show();if(typeof openSocialTool==='function')return openSocialTool('properties');}if(tool==='nobility'&&window.KeloNobility?.open)return window.KeloNobility.open();if(tool==='titles'&&window.KeloTitles?.openBook)return window.KeloTitles.openBook();if(tool==='emotes'&&window.KeloSelfInteractionUI?.openEmotes)return window.KeloSelfInteractionUI.openEmotes();if(tool==='missions'&&window.KeloMissionsUI?.open)return window.KeloMissionsUI.open();if(tool==='settings'&&window.KeloSettingsUI?.open)return window.KeloSettingsUI.open();toast('Esta sección todavía no tiene una pantalla LIVE válida');}
function runTool(tool){
  closeLuxeMenu();
  const loader=window.KELO_MODULE_LOADER;
  if(loader&&typeof loader.ensure==='function'&&loader.needs(tool)){
    toast('Cargando…');
    loader.ensure(tool).then(function(){ runToolOpen(tool); }).catch(function(){ toast('No se pudo cargar'); });
    return;
  }
  runToolOpen(tool);
}

function suppressLegacyUI(){['kelo-chat','kelo-stones-btn','social-menu-toggle','kelo-online','kelo-minimap','minimap'].forEach(id=>{const el=document.getElementById(id);if(el)el.style.setProperty('display','none','important');});const top=document.querySelector('.top-bar');if(top)top.style.setProperty('display','none','important');Array.from(document.body.children).forEach(el=>{if(el.tagName==='BUTTON'&&(el.textContent||'').trim()==='Mochila'){if(!el.id)el.id='kelo-bag-btn';el.style.setProperty('display','none','important');}});}suppressLegacyUI();
function updateGold(){const el=document.getElementById('lx-gold');if(el&&typeof STATE!=='undefined')el.textContent='Oro '+(Number(STATE.gold)||0);}updateGold();const telemetry=document.getElementById('telemetry-bar');if(telemetry)new MutationObserver(updateGold).observe(telemetry,{childList:true,characterData:true,subtree:true});
menuButton.onclick=()=>setMenuOpen();document.getElementById('lx-menu-close').onclick=closeLuxeMenu;document.getElementById('lx-chat-close').onclick=closeChat;menuPanel.addEventListener('pointerdown',e=>e.stopPropagation());document.querySelector('.lx-top')?.addEventListener('pointerdown',e=>e.stopPropagation());document.querySelector('.lx-rail')?.addEventListener('pointerdown',e=>e.stopPropagation());chatDrawer.addEventListener('pointerdown',e=>e.stopPropagation());menuPanel.addEventListener('click',e=>{const b=e.target.closest('[data-tool]');if(b)runTool(b.dataset.tool);});
document.getElementById('lx-side-pvp').onclick=()=>{closeChat();closeLuxeMenu();const go=function(){if(typeof window.enterPvPWorld==='function')window.enterPvPWorld();else toast('PvP todavía cargando');};
  const loader=window.KELO_MODULE_LOADER;
  if(loader&&typeof loader.ensure==='function'&&loader.needs('pvp')){toast('Cargando PvP…');loader.ensure('pvp').then(go).catch(function(){toast('No se pudo cargar PvP');});}
  else go();};
function appendChat(who,text){const log=document.getElementById('lx-log');if(!log)return;const row=document.createElement('div');row.textContent=(who||'Tu')+': '+text;log.appendChild(row);log.scrollTop=log.scrollHeight;while(log.children.length>12)log.removeChild(log.firstChild);}const oldSay=window.keloSay;if(typeof oldSay==='function'&&!oldSay._luxeWrapped){const wrapped=function(who,text){oldSay(who,text);appendChat(who,text);};wrapped._luxeWrapped=true;window.keloSay=wrapped;}document.getElementById('lx-form').addEventListener('submit',e=>{e.preventDefault();const inp=document.getElementById('lx-in'),text=(inp.value||'').trim();if(!text)return;const who=(typeof localPlayer!=='undefined'&&localPlayer.name)||'Tu';if(typeof window.keloSay==='function')window.keloSay(who,text);else appendChat(who,text);inp.value='';});
window.addEventListener('keydown',e=>{if(e.key!=='Escape')return;if(menuPanel.classList.contains('open')){e.preventDefault();closeLuxeMenu();}else if(chatDrawer.classList.contains('open')){e.preventDefault();closeChat();}});window.addEventListener('kelo:character-customization-ready',renderMenu);
window.KELO_LUXE=Object.freeze({toggleMenu:setMenuOpen,closeMenu:closeLuxeMenu,isMenuOpen:()=>menuPanel.classList.contains('open'),closeChat,renderMenu});window.KELO_LUXE_AUDIT=Object.freeze({version:VERSION,palette:'premium-fantasy-forest-gold',mobileFirst:true,gridColumns:2,minTouchTargetPx:44,inputLockOwner:'KeloInputLocks',tokenLocks:true,directLegacyModalWrite:false,noPolling:true,routes:['bag','abilities','appearance','mounts','profile','market','chat','properties','nobility','titles','emotes'],optionalRoutes:['missions','settings'],legacyHudSuppressed:true,pvpRailButton:true});
})();