/* KELO-INDEX
 * area: UI / MOUNTS
 * owner: mount panel consumer
 * purpose: UI mobile-first para equipar/montar, equipo y outfit usando APIs de KeloMounts
 * public-api: KeloMountPanel.open/close/toggle/refresh
 * consumes: KeloMounts, KeloMountCatalog, KeloMountEquipmentCatalog, KeloAppearance; entrada visible desde KELO_LUXE
 * state-owned: DOM local únicamente
 * online: todas las mutaciones pasan por KeloMounts authority boundary
 * do-not: no escribir STATE, stats ni movement directamente; no crear launcher flotante paralelo al menú principal
 */
(function(root){'use strict';if(root.KeloMountPanel)return;const Mounts=root.KeloMounts,Catalog=root.KeloMountCatalog,Equip=root.KeloMountEquipmentCatalog,Appearance=root.KeloAppearance;if(!Mounts||!Catalog)return;
let panel=null,open=false,busy=false;
function toast(m){if(typeof showToast==='function')showToast(m);}
function el(tag,props={},children=[]){const n=document.createElement(tag);for(const[k,v]of Object.entries(props)){if(k==='class')n.className=v;else if(k==='text')n.textContent=v;else if(k==='html')n.innerHTML=v;else if(k==='style')n.style.cssText=v;else n.setAttribute(k,v);}for(const c of [].concat(children||[]))if(c)n.append(c);return n;}
async function act(fn){if(busy)return;busy=true;try{const r=await fn();if(r?.ok===false)toast(r.error||'No se pudo completar');else refresh();}catch(e){console.error(e);toast(e.message||'Error de montura');}finally{busy=false;}}
function ensure(){if(panel)return;panel=el('section',{id:'kelo-mount-panel',role:'dialog','aria-label':'Monturas',style:'display:none;position:fixed;inset:max(64px,env(safe-area-inset-top)) max(8px,env(safe-area-inset-right)) max(16px,env(safe-area-inset-bottom)) max(8px,env(safe-area-inset-left));z-index:2147481200;pointer-events:auto;background:rgba(8,10,14,.985);border:1px solid rgba(231,197,106,.45);border-radius:20px;color:#f4f1e8;overflow:auto;padding:14px;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;box-shadow:0 20px 80px rgba(0,0,0,.55)'});document.body.appendChild(panel);}
function mountCard(def){const equipped=Mounts.getEquippedMountId()===def.id,owned=Mounts.isOwned(def.id),mounted=equipped&&Mounts.isMounted();const card=el('div',{style:'border:1px solid rgba(255,255,255,.1);border-radius:16px;padding:12px;background:rgba(255,255,255,.035);margin-top:9px'});card.append(el('div',{html:'<b>'+def.displayName+'</b><div style="font-size:9px;color:#a8a8ab;margin-top:3px">'+def.rarity.toUpperCase()+' · '+def.speciesId+'</div>'}));const actions=el('div',{style:'display:flex;gap:7px;flex-wrap:wrap;margin-top:9px'});if(owned&&!equipped){const b=el('button',{text:'EQUIPAR',style:btnStyle()});b.onclick=()=>act(()=>Mounts.equipMount(def.id));actions.append(b);}if(equipped&&!mounted){const b=el('button',{text:'MONTAR',style:btnStyle(true)});b.onclick=()=>act(()=>Mounts.mount());actions.append(b);}if(mounted){const b=el('button',{text:'DESMONTAR',style:btnStyle()});b.onclick=()=>act(()=>Mounts.dismount());actions.append(b);}if(!owned)actions.append(el('span',{text:'BLOQUEADA',style:'font-size:9px;color:#777;padding:8px'}));card.append(actions);if(equipped)card.append(renderEquipment(def));return card;}
function btnStyle(accent){return'border:1px solid '+(accent?'#d7b66b':'rgba(255,255,255,.16)')+';background:'+(accent?'rgba(215,182,107,.16)':'rgba(255,255,255,.05)')+';color:#fff;border-radius:10px;padding:8px 10px;font-size:9px;font-weight:900';}
function renderEquipment(def){const wrap=el('div',{style:'margin-top:12px;padding-top:10px;border-top:1px solid rgba(255,255,255,.08)'}),profile=Catalog.getEquipmentProfile(def.equipmentSlotProfileId),equipped=Mounts.getEquipment(def.id);wrap.append(el('b',{text:'EQUIPO DE MONTURA',style:'font-size:10px;color:#d8bd7a'}));for(const slot of profile?.slots||[]){const row=el('div',{style:'display:grid;grid-template-columns:84px 1fr;gap:8px;align-items:center;margin-top:7px'});row.append(el('span',{text:slot,style:'font-size:9px;color:#999'}));const sel=el('select',{style:'width:100%;background:#11151c;color:#fff;border:1px solid rgba(255,255,255,.12);border-radius:9px;padding:7px;font-size:10px'});sel.append(el('option',{value:'',text:'— vacío —'}));for(const item of Equip?.list?.()||[]){if(item.slotId!==slot||!item.compatibleProfiles.includes(def.equipmentSlotProfileId))continue;const op=el('option',{value:item.id,text:item.displayName});if(equipped[slot]===item.id)op.selected=true;sel.append(op);}sel.onchange=()=>act(()=>sel.value?Mounts.equipItem(def.id,sel.value):Mounts.unequipItem(def.id,slot));row.append(sel);wrap.append(row);}const appearance=el('div',{style:'margin-top:12px'});appearance.append(el('b',{text:'ATUENDO',style:'font-size:10px;color:#d8bd7a'}));const aSel=el('select',{style:'width:100%;margin-top:7px;background:#11151c;color:#fff;border:1px solid rgba(255,255,255,.12);border-radius:9px;padding:8px;font-size:10px'});aSel.append(el('option',{value:'',text:'— sin atuendo —'}));const current=(Mounts.snapshot()?.appearanceByMountId?.[def.id]||{});for(const item of Appearance?.listItems?.()||[]){const profile=Appearance.getProfile(def.appearanceProfileId);if(!profile||!Appearance.compatible(item,profile))continue;const op=el('option',{value:item.id,text:item.displayName});if(current[item.slotId]===item.id)op.selected=true;aSel.append(op);}aSel.onchange=()=>act(()=>Mounts.setOutfitItem(def.id,aSel.value||null));appearance.append(aSel);wrap.append(appearance);const stats=Mounts.getMountStats(def.id)||{};wrap.append(el('div',{text:'Velocidad '+Math.round(stats.maxSpeed||0)+' · Aceleración '+Math.round(stats.acceleration||0)+' · Carga '+Math.round(stats.cargo||0),style:'font-size:9px;color:#8f9aa7;margin-top:9px'}));return wrap;}
function refresh(){ensure();if(!open)return;panel.replaceChildren();const head=el('div',{style:'display:flex;align-items:center;gap:10px;position:sticky;top:-14px;background:rgba(8,10,14,.98);padding:12px 0 9px;z-index:1'},[el('div',{html:'<b style="font-size:18px">MONTURAS</b><div style="font-size:9px;color:#999">Equipa una montura · M1/M2/M3 aparecen al montar</div>'}),el('button',{text:'✕',style:'margin-left:auto;'+btnStyle()})]);head.lastChild.onclick=close;panel.append(head);for(const def of Catalog.list())panel.append(mountCard(def));}
function show(){ensure();open=true;panel.style.display='block';refresh();}
function close(){ensure();open=false;panel.style.display='none';}
function toggle(){open?close():show();}
root.addEventListener?.('KELO_MOUNT_CHANGED',()=>{if(open)refresh();});ensure();root.KeloMountPanel=Object.freeze({version:'mount-panel-v1.0.2-menu-only',open:show,close,toggle,refresh});
})(typeof globalThis!=='undefined'?globalThis:window);
