'use strict';
/* KELO-INDEX
 * area: SERVER / PROGRESSION / TITLES
 * owner: server title authority
 * keys: TITLES STATS KILLS UNLOCK EQUIP AUTHORITY PERSISTENCE EDGE SNAPSHOT HYBRID
 * purpose: valida progreso/desbloqueos server-side y persiste cuando el playerKey ya es characterId; legacy conserva RAM durante transición
 * do-not: NO aceptar kills desde WebSocket cliente; NO usar visual:event DEATH como gameplay
 */
const catalog=require('../src/systems/title-catalog.js');
const {createServerStateBridge}=require('./server-state-bridge');
function clone(v){return JSON.parse(JSON.stringify(v));}
function cleanId(v){return String(v||'').replace(/[^a-zA-Z0-9_:\-.]/g,'').slice(0,96);}
function normalizeProgress(p){const out={};if(p&&typeof p==='object'&&!Array.isArray(p))Object.keys(p).forEach(k=>{out[k]=Math.max(0,Math.floor(Number(p[k])||0));});return out;}
function normalizeUnlocked(u){return Array.from(new Set((Array.isArray(u)?u:[]).filter(id=>!!catalog.get(id))));}
function makeRow(id){return{player_id:cleanId(id),progress:{},unlocked:[],equipped_title_id:null,kill_ledger:[],updated_at:Date.now()};}
function normalizeRow(id,raw){const r=raw&&typeof raw==='object'?clone(raw):makeRow(id);r.player_id=cleanId(id);r.progress=normalizeProgress(r.progress);r.unlocked=normalizeUnlocked(r.unlocked);r.equipped_title_id=r.equipped_title_id||null;r.kill_ledger=Array.isArray(r.kill_ledger)?r.kill_ledger.slice(-100):[];r.updated_at=Number(r.updated_at)||Date.now();return r;}
function createMemoryAdapter(){const players=new Map();return{mode:'ram-authoritative',async ensurePlayer(id){id=cleanId(id);if(!id)throw new Error('INVALID_PLAYER_ID');if(!players.has(id))players.set(id,makeRow(id));return clone(players.get(id));},async getPlayer(id){const r=players.get(cleanId(id));return r?clone(r):null;},async savePlayer(id,patch){id=cleanId(id);const r=players.get(id)||makeRow(id);if(patch.progress)r.progress=normalizeProgress(patch.progress);if(patch.unlocked)r.unlocked=normalizeUnlocked(patch.unlocked);if(Object.prototype.hasOwnProperty.call(patch,'equipped_title_id'))r.equipped_title_id=patch.equipped_title_id||null;if(patch.kill_ledger)r.kill_ledger=Array.isArray(patch.kill_ledger)?clone(patch.kill_ledger).slice(-100):[];r.updated_at=Date.now();players.set(id,r);return clone(r);},async _provision(id,patch){await this.ensurePlayer(id);return this.savePlayer(id,patch||{});}};}
function createSupabaseAdapter(url,key,tableName){const table=/^[a-zA-Z0-9_]+$/.test(String(tableName||''))?String(tableName):'title_players',base=String(url).replace(/\/$/,'')+'/rest/v1',headers={apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'};async function request(path,opts={}){const res=await fetch(base+path,{...opts,headers:{...headers,...(opts.headers||{})}}),text=await res.text();if(!res.ok)throw new Error(`SUPABASE_${res.status}:${text.slice(0,240)}`);return text?JSON.parse(text):null;}return{mode:'supabase-authoritative',async ensurePlayer(id){id=cleanId(id);if(!id)throw new Error('INVALID_PLAYER_ID');const rows=await request(`/${table}?player_id=eq.${encodeURIComponent(id)}&select=*`);if(rows&&rows[0])return rows[0];const created=await request(`/${table}`,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({player_id:id,progress:{},unlocked:[],kill_ledger:[]})});return created[0];},async getPlayer(id){const rows=await request(`/${table}?player_id=eq.${encodeURIComponent(cleanId(id))}&select=*`);return rows&&rows[0]?rows[0]:null;},async savePlayer(id,patch){const body={};if(patch.progress)body.progress=normalizeProgress(patch.progress);if(patch.unlocked)body.unlocked=normalizeUnlocked(patch.unlocked);if(Object.prototype.hasOwnProperty.call(patch,'equipped_title_id'))body.equipped_title_id=patch.equipped_title_id||null;if(patch.kill_ledger)body.kill_ledger=Array.isArray(patch.kill_ledger)?patch.kill_ledger.slice(-100):[];body.updated_at=new Date().toISOString();const rows=await request(`/${table}?player_id=eq.${encodeURIComponent(cleanId(id))}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(body)});if(!rows||!rows[0])throw new Error('TITLE_PERSISTENCE_EMPTY');return rows[0];}};}
function createEdgeAdapter(options={}){const bridge=options.persistenceBridge||createServerStateBridge(options);async function load(id){const s=await bridge.load(id);return s?.payload?.titles?normalizeRow(id,s.payload.titles):null;}async function save(id,row){const r=normalizeRow(id,row);r.updated_at=Date.now();await bridge.save(id,{titles:r});return clone(r);}return{mode:'supabase-edge-snapshot',async ensurePlayer(id){id=cleanId(id);if(!id)throw new Error('INVALID_PLAYER_ID');const r=await load(id);return r||save(id,makeRow(id));},async getPlayer(id){id=cleanId(id);if(!id)return null;return load(id);},async savePlayer(id,patch){id=cleanId(id);const r=await this.ensurePlayer(id);if(patch.progress)r.progress=normalizeProgress(patch.progress);if(patch.unlocked)r.unlocked=normalizeUnlocked(patch.unlocked);if(Object.prototype.hasOwnProperty.call(patch,'equipped_title_id'))r.equipped_title_id=patch.equipped_title_id||null;if(patch.kill_ledger)r.kill_ledger=Array.isArray(patch.kill_ledger)?clone(patch.kill_ledger).slice(-100):[];return save(id,r);},_bridge:bridge};}
function createHybridEdgeAdapter(options={}){const edge=createEdgeAdapter(options),memory=createMemoryAdapter(),persisted=new Set();async function choose(id){if(persisted.has(id))return edge;try{await edge.ensurePlayer(id);persisted.add(id);return edge;}catch(_){await memory.ensurePlayer(id);return memory;}}return{mode:'supabase-edge-hybrid',async ensurePlayer(id){const a=await choose(id);return a.ensurePlayer(id);},async getPlayer(id){return persisted.has(cleanId(id))?edge.getPlayer(id):memory.getPlayer(id);},async savePlayer(id,patch){id=cleanId(id);const a=persisted.has(id)?edge:await choose(id);return a.savePlayer(id,patch);},_edge:edge,_memory:memory,_persisted:persisted};}
function requirementMet(req,v){return!!req&&req.operator==='gte'&&Number(v)>=Number(req.value);}
function evaluateForStat(row,stat){const unlocked=new Set(normalizeUnlocked(row.unlocked)),added=[];catalog.byStat(stat).forEach(t=>{if(!unlocked.has(t.id)&&requirementMet(t.requirement,row.progress[stat])){unlocked.add(t.id);added.push(t.id);}});row.unlocked=Array.from(unlocked);return added;}
function evaluateAll(row){const added=[];catalog.list().forEach(t=>{const unlocked=new Set(row.unlocked||[]);if(!unlocked.has(t.id)&&requirementMet(t.requirement,row.progress[t.requirement.stat])){row.unlocked.push(t.id);added.push(t.id);}});row.unlocked=normalizeUnlocked(row.unlocked);return added;}
function validOpenWorldKill(k,v,c){k=cleanId(k);v=cleanId(v);c=c&&typeof c==='object'?c:{};if(!k||!v||k===v)return false;if(c.confirmed!==true||c.worldPvP!==true)return false;if(c.mode!=='open-world-pvp'&&c.combatType!=='open-world-pvp')return false;if(c.victimType!=='player'||c.npc===true||c.dummy===true||c.training===true||c.arena===true)return false;return true;}
function createTitleService(options={}){const bridge=options.persistenceBridge||createServerStateBridge(options);const adapter=options.adapter||(options.enableSupabase&&options.supabaseUrl&&options.supabaseServiceKey?createSupabaseAdapter(options.supabaseUrl,options.supabaseServiceKey,options.tableName||'title_players'):bridge.configured?createHybridEdgeAdapter({...options,persistenceBridge:bridge}):createMemoryAdapter());async function ensurePlayer(id){return adapter.ensurePlayer(id);}async function snapshot(id){let r=await adapter.ensurePlayer(id);r.progress=normalizeProgress(r.progress);r.unlocked=normalizeUnlocked(r.unlocked);const added=evaluateAll(r);if(r.equipped_title_id&&r.unlocked.indexOf(r.equipped_title_id)<0)r.equipped_title_id=null;if(added.length)r=await adapter.savePlayer(id,{progress:r.progress,unlocked:r.unlocked,equipped_title_id:r.equipped_title_id,kill_ledger:r.kill_ledger||[]});return{version:'server-titles-v1',source:adapter.mode,playerId:cleanId(id),equippedTitleId:r.equipped_title_id||null,unlocked:normalizeUnlocked(r.unlocked),progress:normalizeProgress(r.progress)};}async function equip(id,titleId){titleId=String(titleId||'');if(!catalog.get(titleId))throw new Error('UNKNOWN_TITLE');const s=await snapshot(id);if(s.unlocked.indexOf(titleId)<0)throw new Error('TITLE_LOCKED');await adapter.savePlayer(id,{progress:s.progress,unlocked:s.unlocked,equipped_title_id:titleId});return snapshot(id);}async function unequip(id){const s=await snapshot(id);await adapter.savePlayer(id,{progress:s.progress,unlocked:s.unlocked,equipped_title_id:null});return snapshot(id);}async function recordConfirmedKill(k,v,c){if(!validOpenWorldKill(k,v,c))return{counted:false,reason:'INVALID_OPEN_WORLD_KILL',snapshot:await snapshot(k),newUnlocks:[]};let r=await adapter.ensurePlayer(k);r.progress=normalizeProgress(r.progress);r.unlocked=normalizeUnlocked(r.unlocked);r.progress.openWorldPlayerKills=Math.min(Number.MAX_SAFE_INTEGER,(r.progress.openWorldPlayerKills||0)+1);const newUnlocks=evaluateForStat(r,'openWorldPlayerKills'),ledger=Array.isArray(r.kill_ledger)?r.kill_ledger.slice(-99):[];ledger.push({victimId:cleanId(v),at:Number(c.timestamp)||Date.now(),zone:cleanId(c.zone||''),mode:'open-world-pvp'});await adapter.savePlayer(k,{progress:r.progress,unlocked:r.unlocked,equipped_title_id:r.equipped_title_id||null,kill_ledger:ledger});return{counted:true,newUnlocks,snapshot:await snapshot(k)};}return Object.freeze({version:'server-titles-v1',source:adapter.mode,ensurePlayer,snapshot,equip,unequip,recordConfirmedKill,validOpenWorldKill,_adapter:adapter});}
module.exports={createMemoryAdapter,createSupabaseAdapter,createEdgeAdapter,createHybridEdgeAdapter,createTitleService,validOpenWorldKill};
