/* KELO-INDEX
 * area: PVP / ARENA
 * owner: KeloArena
 * keys: ARENA RANKED MATCHMAKING MMR RP BOTS CONTROL MOBA 1V1 OVERTIME CLUTCH REMATCH PERSONAL BEST COACH
 * purpose: Arena reusable con 3v3 Control y 1v1 MOBA, feedback post-match y rematch sin crear engines paralelos
 * public-api: joinQueue/joinMobaQueue/rematch/leaveQueue/finishMatch/abort/getHostileActors/getActorById/drawWorld/snapshot/getRank
 * consumes: KeloPvPWorld + KeloSimulation + KeloCombatEngine + KeloMeleeEngine + KeloEvents
 * state-owned: cola/match, roster fallback, objetivos Arena, rating fallback, records y decisiones bot
 * online: matchmaking/rating/resultado final deben migrar a server authority sin cambiar API
 * do-not: NO segundo combat engine, NO segundo loop, NO bots ocultos, NO rating desde UI
 */
(function(root){
'use strict';
if(root.KeloArena)return;
const VERSION='kelo-arena-v1.2.0-engagement';
const STORAGE='kelo_arena_profile_v1';
const WORLD=Object.freeze({x:2660,y:360,w:720,h:720,cx:3020,cy:720});
const RULESETS=Object.freeze({
 control:Object.freeze({id:'ranked_control_3v3_v1',label:'3v3 Control',teamSize:3,mode:'control',scoreToWin:100,duration:180,captureRadius:118,captureRate:11,respawnDelay:4,normalizedHp:100,normalizedMana:100,botAttackRange:145,botThinkInterval:.12,minimumRankedQuality:.2,overtimeGrace:4,clutchComeback:20}),
 moba:Object.freeze({id:'ranked_moba_1v1_v1',label:'1v1 MOBA',teamSize:1,mode:'moba',duration:300,respawnDelay:4,normalizedHp:100,normalizedMana:100,botAttackRange:145,botThinkInterval:.12,minimumRankedQuality:.35,towerHp:260,coreHp:420,towerRange:185,towerDamage:8,towerCooldown:1.15})
});
const TIERS=Object.freeze([{id:'bronze',label:'Bronce',min:0},{id:'silver',label:'Plata',min:900},{id:'gold',label:'Oro',min:1100},{id:'platinum',label:'Platino',min:1300},{id:'emerald',label:'Esmeralda',min:1500},{id:'diamond',label:'Diamante',min:1700},{id:'mithril',label:'Mithril',min:1900},{id:'adamantite',label:'Adamantita',min:2150},{id:'ethereal',label:'Etéreo',min:2400}].map(Object.freeze));
const PERSONALITIES=Object.freeze({aggressor:Object.freeze({aggression:1.25,objective:.72,retreat:.25}),guardian:Object.freeze({aggression:.78,objective:1.25,retreat:.58}),tactician:Object.freeze({aggression:.92,objective:1.08,retreat:.48}),assassin:Object.freeze({aggression:1.18,objective:.66,retreat:.62}),support:Object.freeze({aggression:.68,objective:1.18,retreat:.74})});
const BOT_NAMES=['Astra','Bram','Cyra','Doran','Eira','Fenn','Gala','Hiro','Iria','Juno'];
const state={status:'idle',selectedMode:'control',queueStartedAt:0,match:null,profile:readProfile(),savedPlayer:null,originalSimulated:null,lastResult:null,error:null};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));const now=()=>typeof performance!=='undefined'&&performance.now?performance.now():Date.now();
function freshBests(){return{currentStreak:0,longestWinStreak:0,fastestWinSeconds:null,highestComeback:0,overtimeWins:0,mobaCoreClutches:0};}
function readProfile(){let base={mmr:1000,wins:0,losses:0,matches:0,bests:freshBests()};try{const raw=JSON.parse(localStorage.getItem(STORAGE)||'null');if(raw&&Number.isFinite(raw.mmr))base={mmr:clamp(Math.round(raw.mmr),0,4000),wins:Math.max(0,raw.wins|0),losses:Math.max(0,raw.losses|0),matches:Math.max(0,raw.matches|0),bests:Object.assign(freshBests(),raw.bests||{})};}catch(_){}return base;}
function persistProfile(){try{localStorage.setItem(STORAGE,JSON.stringify(state.profile));}catch(_){}}
function rules(){return RULESETS[state.selectedMode]||RULESETS.control;}
function getRank(mmr){const value=Number.isFinite(Number(mmr))?Number(mmr):state.profile.mmr;let tier=TIERS[0],next=null;for(let i=0;i<TIERS.length;i++){if(value>=TIERS[i].min)tier=TIERS[i];else{next=TIERS[i];break;}}const floor=tier.min,ceil=next?next.min:Math.max(floor+300,2700),rp=Math.round(clamp((value-floor)/Math.max(1,ceil-floor),0,1)*100);return Object.freeze({id:tier.id,label:tier.label,mmr:Math.round(value),rp,next:next&&next.label||null});}
function isOnline(){return !!(root.KeloNetAuthority&&root.KeloNetAuthority.isOnline&&root.KeloNetAuthority.isOnline());}
function emit(name,detail){try{root.dispatchEvent(new CustomEvent('kelo:arena-'+name,{detail}));}catch(_){}try{root.KeloEvents&&root.KeloEvents.emit('arena:'+name,detail);}catch(_){}}
const teamOf=a=>a&&a._arenaTeam||null,alive=a=>!!(a&&Number(a.hp)>0&&!a._arenaRespawning),actorId=a=>String(a&&a.id||'');
function allActors(){return state.match?state.match.roster.map(r=>r.actor).filter(Boolean):[];}function activeStructures(){return state.match&&Array.isArray(state.match.structures)?state.match.structures.filter(s=>s.hp>0):[];}
function getActorById(id){const key=String(id||'');return allActors().concat(activeStructures()).find(a=>actorId(a)===key)||null;}
function getHostileActors(viewer){if(!state.match||state.status!=='active')return[];const team=teamOf(viewer)||'alpha',heroes=allActors().filter(a=>a!==viewer&&teamOf(a)!==team&&alive(a));if(state.match.ruleSet.mode!=='moba')return heroes;const tower=state.match.structures.find(s=>s.team!==team&&s.kind==='tower'),core=state.match.structures.find(s=>s.team!==team&&s.kind==='core');return heroes.concat(tower&&tower.hp>0?[tower]:core&&core.hp>0?[core]:[]);}
function normalizedSnapshot(a){return{maxHp:Number(a&&a.maxHp)||100,hp:Number(a&&a.hp)||100,maxMana:Number(a&&a.maxMana)||100,mana:Number(a&&a.mana)||100};}function applyNormalized(a,r){if(!a)return;a.maxHp=r.normalizedHp;a.hp=r.normalizedHp;a.maxMana=r.normalizedMana;a.mana=r.normalizedMana;}
function spawnFor(team,slot,r){const left=team==='alpha',baseX=left?WORLD.x+115:WORLD.x+WORLD.w-115,baseY=WORLD.cy+(r.teamSize===1?0:(slot-1)*92);return{x:baseX,y:baseY};}
function makeBot(index,team,spawn,r){const personalityKey=Object.keys(PERSONALITIES)[index%Object.keys(PERSONALITIES).length];return{id:'arena_bot_'+team+'_'+index,name:BOT_NAMES[index%BOT_NAMES.length]+' [Bot]',x:spawn.x,y:spawn.y,vx:0,vy:0,radius:20,hp:r.normalizedHp,maxHp:r.normalizedHp,mana:r.normalizedMana,maxMana:r.normalizedMana,gear:{bodyColor:team==='alpha'?'#5d84e8':'#d66d78',armorColor:'#e7c56a',weaponColor:'#fff'},_face:team==='alpha'?'right':'left',_gait:'idle',_arenaTeam:team,isArenaBot:true,botPersonality:personalityKey,_arenaAI:{think:0,attackCooldown:.2,targetId:null}};}
function makeStructures(r){if(r.mode!=='moba')return[];return[{id:'arena_tower_alpha',name:'Torre Azul',kind:'tower',team:'alpha',_arenaTeam:'alpha',x:WORLD.x+205,y:WORLD.cy,radius:30,hp:r.towerHp,maxHp:r.towerHp,isArenaStructure:true,_cooldown:0},{id:'arena_core_alpha',name:'Núcleo Azul',kind:'core',team:'alpha',_arenaTeam:'alpha',x:WORLD.x+82,y:WORLD.cy,radius:38,hp:r.coreHp,maxHp:r.coreHp,isArenaStructure:true},{id:'arena_tower_beta',name:'Torre Roja',kind:'tower',team:'beta',_arenaTeam:'beta',x:WORLD.x+WORLD.w-205,y:WORLD.cy,radius:30,hp:r.towerHp,maxHp:r.towerHp,isArenaStructure:true,_cooldown:0},{id:'arena_core_beta',name:'Núcleo Rojo',kind:'core',team:'beta',_arenaTeam:'beta',x:WORLD.x+WORLD.w-82,y:WORLD.cy,radius:38,hp:r.coreHp,maxHp:r.coreHp,isArenaStructure:true}];}
function buildLocalRoster(r){const player=typeof localPlayer!=='undefined'?localPlayer:null;if(!player)throw new Error('ARENA_PLAYER_UNAVAILABLE');state.savedPlayer=normalizedSnapshot(player);player._arenaTeam='alpha';applyNormalized(player,r);const roster=[{actor:player,type:'human',team:'alpha',slot:0,playerKey:root.keloNet&&root.keloNet.playerKey||'local'}];if(r.mode==='control'){for(let i=1;i<3;i++)roster.push({actor:makeBot(i,'alpha',spawnFor('alpha',i,r),r),type:'bot',team:'alpha',slot:i});for(let i=0;i<3;i++)roster.push({actor:makeBot(i+3,'beta',spawnFor('beta',i,r),r),type:'bot',team:'beta',slot:i});}else roster.push({actor:makeBot(7,'beta',spawnFor('beta',0,r),r),type:'bot',team:'beta',slot:0});return roster;}
function beginLocalMatch(){if(state.status!=='matching')return false;const r=rules();let roster;try{roster=buildLocalRoster(r);}catch(e){state.status='idle';state.error=String(e);return false;}state.originalSimulated=typeof simulatedPlayers!=='undefined'&&Array.isArray(simulatedPlayers)?simulatedPlayers.slice():null;if(typeof simulatedPlayers!=='undefined'&&Array.isArray(simulatedPlayers)){simulatedPlayers.length=0;roster.filter(x=>x.type==='bot').forEach(x=>simulatedPlayers.push(x.actor));}state.match={id:'local_'+Date.now().toString(36),ruleSet:r,source:'local-fallback',startedAt:now(),elapsed:0,humanCount:1,quality:r.minimumRankedQuality,score:{alpha:0,beta:0},captureTeam:null,structures:makeStructures(r),roster,winner:null,overtime:{active:false,grace:r.overtimeGrace||0},maxDeficit:{alpha:0,beta:0}};state.status='active';const p=typeof localPlayer!=='undefined'?localPlayer:null;if(p){const s=spawnFor('alpha',0,r);p.x=s.x;p.y=s.y;}emit('match-started',snapshot());return true;}
function restoreWorld(){if(typeof localPlayer!=='undefined'&&state.savedPlayer){localPlayer.maxHp=state.savedPlayer.maxHp;localPlayer.hp=Math.min(state.savedPlayer.hp,state.savedPlayer.maxHp);localPlayer.maxMana=state.savedPlayer.maxMana;localPlayer.mana=Math.min(state.savedPlayer.mana,state.savedPlayer.maxMana);delete localPlayer._arenaTeam;}if(typeof simulatedPlayers!=='undefined'&&Array.isArray(simulatedPlayers)&&state.originalSimulated){simulatedPlayers.length=0;state.originalSimulated.forEach(a=>simulatedPlayers.push(a));}state.originalSimulated=null;state.savedPlayer=null;}
function expectedScore(own,other){return 1/(1+Math.pow(10,(other-own)/400));}
function coachFor(result){if(result.won&&result.accolades.includes('REMONTADA'))return'Remontaste una desventaja grande: mantuviste presión cuando la partida todavía era recuperable.';if(result.won&&result.mode==='moba'&&result.accolades.includes('NÚCLEO AL LÍMITE'))return'Ganaste con tu núcleo crítico. Tu siguiente mejora es cerrar antes la partida cuando consigues ventaja.';if(!result.won&&result.mode==='control'&&result.score.alpha<result.score.beta)return'Perdiste por objetivo. Prioriza tiempo dentro de la zona cuando el combate no exige perseguir una baja.';if(!result.won&&result.mode==='moba')return'La partida se decide por estructuras: después de ganar un intercambio, convierte la ventaja en daño a torre o núcleo.';return result.won?'Buena partida. Busca repetir la decisión que creó tu mayor ventaja, no solo el resultado.':'Revisa el momento en que cediste la iniciativa y prueba una respuesta distinta en la revancha.';}
function applyResult(winner,reason){const won=winner==='alpha',old=state.profile.mmr,expected=expectedScore(old,1000),quality=state.match?state.match.quality:rules().minimumRankedQuality,delta=Math.round(30*((won?1:0)-expected)*quality),m=state.match,b=state.profile.bests,accolades=[];state.profile.mmr=clamp(old+delta,0,4000);state.profile.matches++;if(won){state.profile.wins++;b.currentStreak++;b.longestWinStreak=Math.max(b.longestWinStreak,b.currentStreak);if(b.fastestWinSeconds==null||m.elapsed<b.fastestWinSeconds)b.fastestWinSeconds=Math.round(m.elapsed);const comeback=Math.round(m.maxDeficit.alpha||0);if(comeback>=m.ruleSet.clutchComeback){accolades.push('REMONTADA');b.highestComeback=Math.max(b.highestComeback,comeback);}if(m.overtime.active){accolades.push('OVERTIME');b.overtimeWins++;}if(m.ruleSet.mode==='moba'){const ownCore=m.structures.find(s=>s.id==='arena_core_alpha');if(ownCore&&ownCore.hp/ownCore.maxHp<=.15){accolades.push('NÚCLEO AL LÍMITE');b.mobaCoreClutches++;}}const p=typeof localPlayer!=='undefined'?localPlayer:null;if(p&&p.hp>0&&p.hp/Math.max(1,p.maxHp)<=.1)accolades.push('ÚLTIMO ALIENTO');}else{state.profile.losses++;b.currentStreak=0;}persistProfile();const result={won,winner,reason,delta,quality,rank:getRank(state.profile.mmr),mode:m.ruleSet.mode,score:Object.freeze({...m.score}),duration:Math.round(m.elapsed),accolades:Object.freeze(accolades.slice()),bests:Object.freeze({...b})};result.coach=coachFor(result);return result;}
function finishMatch(winner,reason){if(!state.match||state.status!=='active')return null;winner=winner==='beta'?'beta':'alpha';state.match.winner=winner;state.lastResult=Object.freeze(applyResult(winner,reason||'objective'));state.status='finished';emit('match-finished',snapshot());return state.lastResult;}
function cleanupAfterFinish(){restoreWorld();state.match=null;state.status='idle';if(root.KeloPvPWorld&&root.KeloPvPWorld.state&&root.KeloPvPWorld.state.combatEnabled)root.KeloPvPWorld.leave();emit('idle',snapshot());}
function abort(reason){if(state.status==='idle')return false;restoreWorld();state.lastResult=Object.freeze({aborted:true,reason:reason||'cancelled'});state.match=null;state.status='idle';emit('aborted',snapshot());return true;}
function joinQueue(mode){if(state.status!=='idle')return Promise.resolve(snapshot());state.selectedMode=mode==='moba'?'moba':'control';state.status='queued';state.queueStartedAt=now();state.error=null;emit('queue-changed',snapshot());const r=rules();if(isOnline()&&root.KeloNetAuthority&&typeof root.KeloNetAuthority.requestArena==='function'){state.status='matching';return root.KeloNetAuthority.requestArena('join',{ruleSetId:r.id}).then(server=>{emit('server-queue',server);return snapshot();}).catch(()=>{state.status='queued';return startLocalFallback();});}return Promise.resolve(startLocalFallback());}
const joinMobaQueue=()=>joinQueue('moba');function rematch(){if(state.status!=='idle'||!state.lastResult||state.lastResult.aborted)return Promise.resolve(snapshot());return joinQueue(state.lastResult.mode);}
function startLocalFallback(){state.status='matching';if(!root.KeloPvPWorld||typeof root.KeloPvPWorld.enter!=='function'){state.status='idle';state.error='PVP_WORLD_UNAVAILABLE';return snapshot();}root.KeloPvPWorld.enter();emit('queue-changed',snapshot());return snapshot();}
function leaveQueue(){if(state.status==='queued'||state.status==='matching'){state.status='idle';state.queueStartedAt=0;emit('queue-changed',snapshot());return true;}return false;}
function moveToward(bot,point,speed,dt){const dx=point.x-bot.x,dy=point.y-bot.y,d=Math.hypot(dx,dy)||1;if(d<5){bot._gait='idle';return;}bot.x+=dx/d*speed*dt;bot.y+=dy/d*speed*dt;bot._face=Math.abs(dx)>Math.abs(dy)?(dx<0?'left':'right'):(dy<0?'up':'down');bot._gait='run';bot.x=clamp(bot.x,WORLD.x+24,WORLD.x+WORLD.w-24);bot.y=clamp(bot.y,WORLD.y+24,WORLD.y+WORLD.h-24);}
function botAttack(bot,target){if(!root.KeloCombatEngine||!root.KeloMeleeEngine||!target)return false;const profile=root.KeloMeleeEngine.getProfile&&root.KeloMeleeEngine.getProfile('sword_light_basic');if(!profile)return false;const dx=target.x-bot.x,dy=target.y-bot.y,l=Math.hypot(dx,dy)||1,dir={x:dx/l,y:dy/l};const result=root.KeloCombatEngine.attackSweep({attacker:bot,targets:[target],direction:dir,profile,profileId:profile.id,attackId:'arena_bot_'+Date.now().toString(36)+'_'+bot.id,startedAt:now(),source:'arena-bot',skipStart:false});return !!(result&&result.hits&&result.hits.length);}
function respawn(actor,row,dt){if(alive(actor))return false;actor._arenaRespawning=true;actor._arenaRespawnLeft=Number(actor._arenaRespawnLeft)||state.match.ruleSet.respawnDelay;actor._arenaRespawnLeft-=dt;if(actor._arenaRespawnLeft>0)return true;const s=spawnFor(row.team,row.slot,state.match.ruleSet);actor.x=s.x;actor.y=s.y;actor.hp=actor.maxHp=state.match.ruleSet.normalizedHp;actor.mana=actor.maxMana=state.match.ruleSet.normalizedMana;actor._arenaRespawning=false;actor._arenaRespawnLeft=0;if(actor._arenaAI)actor._arenaAI.attackCooldown=.5;return true;}
function nearestEnemy(bot){const list=allActors().filter(a=>a!==bot&&teamOf(a)!==teamOf(bot)&&alive(a));list.sort((a,b)=>Math.hypot(a.x-bot.x,a.y-bot.y)-Math.hypot(b.x-bot.x,b.y-bot.y));return list[0]||null;}function mobaObjective(bot){const enemy=teamOf(bot)==='alpha'?'beta':'alpha',tower=state.match.structures.find(s=>s.team===enemy&&s.kind==='tower'),core=state.match.structures.find(s=>s.team===enemy&&s.kind==='core');return tower&&tower.hp>0?tower:core;}
function updateBot(row,dt){const bot=row.actor,ai=bot._arenaAI;if(respawn(bot,row,dt))return;const r=state.match.ruleSet;ai.attackCooldown=Math.max(0,ai.attackCooldown-dt);ai.think-=dt;if(ai.think>0)return;ai.think=r.botThinkInterval;const p=PERSONALITIES[bot.botPersonality]||PERSONALITIES.tactician,enemy=nearestEnemy(bot);let target=enemy,destination={x:WORLD.cx,y:WORLD.cy};if(r.mode==='moba'){const objective=mobaObjective(bot);if(enemy&&Math.hypot(enemy.x-bot.x,enemy.y-bot.y)<210)target=enemy;else target=objective;destination=target||destination;}else if(enemy){const d=Math.hypot(enemy.x-bot.x,enemy.y-bot.y),hpRatio=bot.hp/Math.max(1,bot.maxHp);if(hpRatio<p.retreat*.35)destination={x:bot.x+(bot.x-enemy.x),y:bot.y+(bot.y-enemy.y)};else if(d<r.botAttackRange*1.35&&p.aggression>=p.objective*.72)destination=enemy;}if(!target)return;ai.targetId=target.id;const distance=Math.hypot(target.x-bot.x,target.y-bot.y);moveToward(bot,destination,118*(.88+p.aggression*.12),r.botThinkInterval);if(distance<=r.botAttackRange&&ai.attackCooldown<=0){botAttack(bot,target);ai.attackCooldown=.72+(1.15-p.aggression)*.18;}}
function controlPresence(){const r=state.match.ruleSet,inside={alpha:0,beta:0};state.match.roster.forEach(row=>{const a=row.actor;if(alive(a)&&Math.hypot(a.x-WORLD.cx,a.y-WORLD.cy)<=r.captureRadius)inside[row.team]++;});return inside;}
function updateControl(dt){const r=state.match.ruleSet,inside=controlPresence(),owner=inside.alpha>0&&inside.beta===0?'alpha':inside.beta>0&&inside.alpha===0?'beta':null;state.match.captureTeam=owner;if(owner){state.match.score[owner]=clamp(state.match.score[owner]+r.captureRate*dt,0,r.scoreToWin);if(state.match.score[owner]>=r.scoreToWin)return finishMatch(owner,'control-score');}state.match.maxDeficit.alpha=Math.max(state.match.maxDeficit.alpha,state.match.score.beta-state.match.score.alpha);state.match.maxDeficit.beta=Math.max(state.match.maxDeficit.beta,state.match.score.alpha-state.match.score.beta);if(state.match.overtime.active){if(inside.alpha>0&&inside.beta>0)state.match.overtime.grace=r.overtimeGrace;else state.match.overtime.grace-=dt;if(state.match.overtime.grace<=0)finishMatch(state.match.score.alpha===state.match.score.beta?(owner||'alpha'):state.match.score.alpha>state.match.score.beta?'alpha':'beta','overtime');}}
function towerTick(dt){const r=state.match.ruleSet;if(r.mode!=='moba')return;state.match.structures.filter(s=>s.kind==='tower'&&s.hp>0).forEach(t=>{t._cooldown=Math.max(0,(t._cooldown||0)-dt);if(t._cooldown>0)return;const enemies=allActors().filter(a=>teamOf(a)!==t.team&&alive(a)&&Math.hypot(a.x-t.x,a.y-t.y)<=r.towerRange);if(!enemies.length)return;enemies.sort((a,b)=>Math.hypot(a.x-t.x,a.y-t.y)-Math.hypot(b.x-t.x,b.y-t.y));const target=enemies[0];target.hp=Math.max(0,target.hp-r.towerDamage);t._cooldown=r.towerCooldown;emit('tower-hit',{towerId:t.id,targetId:target.id,amount:r.towerDamage});});state.match.structures.filter(s=>s.kind==='core').forEach(c=>{if(c.hp<=0&&state.status==='active')finishMatch(c.team==='alpha'?'beta':'alpha','core-destroyed');});}
function tick(ctx){const dt=clamp(Number(ctx&&ctx.dt)||0,0,.05);if(state.status==='matching'){if(root.KeloPvPWorld&&root.KeloPvPWorld.state&&root.KeloPvPWorld.state.combatEnabled)beginLocalMatch();return;}if(state.status==='finished'){cleanupAfterFinish();return;}if(state.status!=='active'||!state.match)return;if(!root.KeloPvPWorld||!root.KeloPvPWorld.state||!root.KeloPvPWorld.state.combatEnabled){abort('pvp-left');return;}state.match.elapsed+=dt;state.match.roster.filter(r=>r.type==='bot').forEach(r=>updateBot(r,dt));state.match.roster.filter(r=>r.type==='human').forEach(r=>respawn(r,r,dt));if(state.match.ruleSet.mode==='control')updateControl(dt);else towerTick(dt);if(state.status!=='active'||state.match.elapsed<state.match.ruleSet.duration)return;if(state.match.ruleSet.mode==='control'){const inside=controlPresence();if(inside.alpha>0&&inside.beta>0&&!state.match.overtime.active){state.match.overtime.active=true;state.match.overtime.grace=state.match.ruleSet.overtimeGrace;emit('overtime',snapshot());}else if(!state.match.overtime.active)finishMatch(state.match.score.alpha===state.match.score.beta?'alpha':state.match.score.alpha>state.match.score.beta?'alpha':'beta','time');}else{const ac=state.match.structures.find(s=>s.id==='arena_core_alpha'),bc=state.match.structures.find(s=>s.id==='arena_core_beta');finishMatch((bc&&bc.hp||0)<(ac&&ac.hp||0)?'alpha':'beta','time-core-hp');}}
function drawStructure(ctx,s){const ratio=clamp(s.hp/s.maxHp,0,1);ctx.save();ctx.translate(s.x,s.y);ctx.fillStyle=s.team==='alpha'?'rgba(74,139,255,.28)':'rgba(239,92,108,.28)';ctx.strokeStyle=s.team==='alpha'?'#6ba8ff':'#ff7d89';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,s.kind==='core'?30:22,0,Math.PI*2);ctx.fill();ctx.stroke();if(s.kind==='tower'){ctx.beginPath();ctx.moveTo(0,-30);ctx.lineTo(-13,10);ctx.lineTo(13,10);ctx.closePath();ctx.stroke();}else{ctx.beginPath();ctx.rect(-11,-11,22,22);ctx.stroke();}ctx.fillStyle='rgba(0,0,0,.75)';ctx.fillRect(-32,-44,64,6);ctx.fillStyle=s.team==='alpha'?'#6ba8ff':'#ff7d89';ctx.fillRect(-32,-44,64*ratio,6);ctx.restore();}
function drawWorld(ctx){if(state.status!=='active'||!state.match||!ctx)return false;ctx.save();const r=state.match.ruleSet;if(r.mode==='control'){ctx.fillStyle=state.match.overtime.active?'rgba(255,116,86,.12)':'rgba(55,169,213,.08)';ctx.strokeStyle=state.match.overtime.active?'rgba(255,126,86,.8)':'rgba(104,210,255,.42)';ctx.lineWidth=state.match.overtime.active?4:2;ctx.beginPath();ctx.arc(WORLD.cx,WORLD.cy,r.captureRadius,0,Math.PI*2);ctx.fill();ctx.stroke();}else{ctx.strokeStyle='rgba(231,197,106,.18)';ctx.lineWidth=18;ctx.beginPath();ctx.moveTo(WORLD.x+80,WORLD.cy);ctx.lineTo(WORLD.x+WORLD.w-80,WORLD.cy);ctx.stroke();state.match.structures.forEach(s=>{if(s.hp>0)drawStructure(ctx,s);});}state.match.roster.forEach(row=>{const a=row.actor;if(row.type==='human'||!a||a._arenaRespawning)return;if(typeof renderAvatar==='function')renderAvatar(a,false);ctx.fillStyle='rgba(0,0,0,.72)';ctx.fillRect(a.x-30,a.y-50,60,6);ctx.fillStyle=row.team==='alpha'?'#64a7ff':'#ef6d7a';ctx.fillRect(a.x-30,a.y-50,60*clamp(a.hp/a.maxHp,0,1),6);ctx.fillStyle='#fff';ctx.font='10px sans-serif';ctx.textAlign='center';ctx.fillText(a.name,a.x,a.y-57);});ctx.restore();return true;}
function snapshot(){const rank=getRank(),m=state.match,r=rules(),b=state.profile.bests;return Object.freeze({version:VERSION,status:state.status,selectedMode:state.selectedMode,ruleSet:r,ruleSets:RULESETS,rank,profile:Object.freeze({wins:state.profile.wins,losses:state.profile.losses,matches:state.profile.matches,bests:Object.freeze({...b})}),match:m?Object.freeze({id:m.id,source:m.source,elapsed:m.elapsed,humanCount:m.humanCount,quality:m.quality,score:Object.freeze({...m.score}),captureTeam:m.captureTeam,winner:m.winner,mode:m.ruleSet.mode,overtime:Object.freeze({...m.overtime}),structures:Object.freeze((m.structures||[]).map(s=>Object.freeze({id:s.id,name:s.name,kind:s.kind,team:s.team,hp:s.hp,maxHp:s.maxHp}))),roster:Object.freeze(m.roster.map(x=>Object.freeze({id:actorId(x.actor),name:x.actor.name,type:x.type,team:x.team,hp:Number(x.actor.hp)||0,maxHp:Number(x.actor.maxHp)||100}))) }):null,lastResult:state.lastResult,error:state.error});}
if(!root.KeloSimulation)throw new Error('KeloArena requires KeloSimulation');root.KeloSimulation.after('arena:match-runtime',tick,72);
root.KeloArena=Object.freeze({version:VERSION,rules:RULESETS.control,ruleSets:RULESETS,tiers:TIERS,joinQueue,joinMobaQueue,rematch,openQueue:joinQueue,leaveQueue,finishMatch,abort,getHostileActors,getActorById,drawWorld,snapshot,getRank,isActive:()=>state.status==='active'});
root.KELO_ARENA_AUDIT=Object.freeze({version:VERSION,owner:'KeloArena',modes:['control3v3','moba1v1'],transparentBots:true,botsUseCombatEngine:true,normalizedStats:true,hiddenMmr:true,visibleRank:true,matchQualityWeightedRp:true,mobaTowerCore:true,overtime:true,clutchAccolades:true,personalBests:true,coachCard:true,instantRematch:true,onlineAuthorityBoundary:true,localFallback:true,secondLoop:false});emit('ready',snapshot());
})(typeof globalThis!=='undefined'?globalThis:window);