/* KELO-INDEX
 * area: LOGISTICS / CARAVANS
 * owner: KeloCaravans
 * keys: CART CARAVAN INVENTORY OWNER CONTROLLER ATTACH DETACH CLAIM CARGO HIDDEN MOVEMENT RENDER AUTHORITY
 * purpose: owner de carretas persistentes físicas; reutiliza KeloContainers y separa owner de currentController
 * public-api: KeloCaravans.request/snapshot/getCart/inspectCart/canActorAttack/cartWeight/installAuthorityAdapter/dev
 * consumes: KeloContainers, KeloMovement, KeloRender, KeloCamera, KeloEvents, KeloFactions opcional, STATE/saveState
 * state-owned: STATE.caravans carts/claims/revisions; carga vive exclusivamente en KeloContainers
 * extension-points: CartType data-driven, ownership PLAYER/CLAN/FACTION, claim hooks, future scout/sealed/decoy metadata
 * reuse: convoy/clan/faction caravan debe extender este owner; no crear CartInventorySystem
 * legacy: combate actual debe consultar canActorAttack para respetar ATTACHED
 * do-not: NO revelar carga a viewer no autorizado; NPC raider solo consulta presencia de cart
 */
(function(root){
'use strict';
const VERSION='caravan-v1.0.0',SCHEMA=1;
const STATES=Object.freeze(['PARKED','ATTACHED','DROPPED','CLAIMING','DESTROYED']);
const CART_TYPES=Object.freeze([
  Object.freeze({id:'handcart',name:'Carreta de Comercio',capacitySlots:18,maxWeight:350,claimDurationMs:1800,attachRange:78,metadata:{futureOutfitSlot:true}}),
  Object.freeze({id:'heavy_cart',name:'Carreta Pesada',capacitySlots:28,maxWeight:700,claimDurationMs:2000,attachRange:82,metadata:{futureOutfitSlot:true}})
]);
const EVENTS=Object.freeze({attached:'caravans:cart-attached',detached:'caravans:cart-detached',claimed:'caravans:cart-claimed',abandoned:'caravans:cart-abandoned',claimStarted:'caravans:cart-claim-started',claimInterrupted:'caravans:cart-claim-interrupted',cargoChanged:'caravans:cart-cargo-changed'});
const typeById=new Map(CART_TYPES.map(t=>[t.id,t]));let injectedAuthority=null,lastServerSnapshot=null,seq=1;
function clone(v){return v==null?v:JSON.parse(JSON.stringify(v));}function now(){return Date.now();}function save(){if(typeof saveState==='function')saveState();}function emit(n,p){try{root.KeloEvents?.emit?.(n,p);}catch(_){}}function id(p){return p+'_'+now().toString(36)+'_'+(seq++).toString(36);}function actorId(){return String(root.keloNet?.playerKey||root.keloNet?.id||(typeof localPlayer!=='undefined'&&localPlayer&&localPlayer.id)||'local_pioneer');}
function normalizeOwner(owner){if(root.KeloFactions?.normalizeOwner)return root.KeloFactions.normalizeOwner(owner);const v=owner||{},type=['PLAYER','CLAN','FACTION'].includes(String(v.type))?String(v.type):'PLAYER',ownerId=String(v.id||v.ownerId||'').trim();return ownerId?{type:type,id:ownerId}:null;}
function defaultCart(){return{id:'cart_demo_1',typeId:'handcart',inventoryId:'cart_inv_cart_demo_1',worldId:'main',zoneId:'plaza',position:{x:1485,y:1645},owner:{type:'PLAYER',id:'local_pioneer'},currentControllerId:null,state:'PARKED',claim:null,metadata:{sealed:false,scoutingHook:null,decoyHook:null},revision:1};}
function ensureCartContainer(cart){const type=typeById.get(cart.typeId)||CART_TYPES[0];if(!root.KeloContainers?.registerContainer)return false;root.KeloContainers.registerContainer({id:cart.inventoryId,type:'cart',owner:cart.owner.type+':'+cart.owner.id,capacity:type.capacitySlots,permissions:{deposit:true,withdraw:true,merge:true,elastic:false}},{persist:false,update:true});return true;}
function ensure(){if(typeof STATE==='undefined')return null;let changed=false;if(!STATE.caravans||typeof STATE.caravans!=='object'){STATE.caravans={schemaVersion:SCHEMA,carts:{},revision:1};changed=true;}const s=STATE.caravans;if(!s.carts||typeof s.carts!=='object'){s.carts={};changed=true;}if(!s.carts.cart_demo_1){s.carts.cart_demo_1=defaultCart();changed=true;}Object.values(s.carts).forEach(function(cart){if(!cart||!cart.id)return;cart.owner=normalizeOwner(cart.owner)||{type:'PLAYER',id:'local_pioneer'};cart.currentControllerId=cart.currentControllerId==null?null:String(cart.currentControllerId);cart.state=STATES.includes(cart.state)?cart.state:'PARKED';cart.position=cart.position||{x:0,y:0};cart.revision=Math.max(1,Number(cart.revision)||1);ensureCartContainer(cart);});if(changed)save();return s;}
function bump(cart){cart.revision=(Number(cart.revision)||0)+1;const s=ensure();s.revision=(Number(s.revision)||0)+1;}function getCart(cartId){const c=ensure().carts[String(cartId)];return c?clone(c):null;}function rawCart(cartId){return ensure().carts[String(cartId)]||null;}function playerEntity(pid){if(typeof localPlayer!=='undefined'&&localPlayer&&String(localPlayer.id)===String(pid))return localPlayer;if(typeof simulatedPlayers!=='undefined'&&Array.isArray(simulatedPlayers))return simulatedPlayers.find(p=>p&&String(p.id)===String(pid))||null;return null;}function dist(a,b){return Math.hypot((Number(a?.x)||0)-(Number(b?.x)||0),(Number(a?.y)||0)-(Number(b?.y)||0));}
function cartWeight(cartId){const cart=rawCart(cartId);if(!cart)return 0;return(root.KeloContainers?.getSlots?.(cart.inventoryId)||[]).reduce((sum,slot)=>{const item=slot.item;return sum+(item?Math.max(1,Number(item.quantity)||1)*Math.max(0,Number(item.weight)||0):0);},0);}
function canInspect(cart,viewerId){const viewer=String(viewerId||actorId());if(!cart)return false;if(cart.owner.type==='PLAYER')return cart.owner.id===viewer;if(cart.owner.type==='CLAN'){const clan=root.KeloFactions?.getPlayerClan?.(viewer);return !!(clan&&clan.id===cart.owner.id);}if(cart.owner.type==='FACTION'){const m=root.KeloFactions?.getMembership?.(viewer);return !!(m&&m.factionId===cart.owner.id);}return false;}
function inspectCart(cartId,viewerId){const cart=rawCart(cartId);if(!cart)return null;const base={id:cart.id,typeId:cart.typeId,state:cart.state,owner:clone(cart.owner),currentControllerId:cart.currentControllerId,position:clone(cart.position),revision:cart.revision};if(!canInspect(cart,viewerId))return Object.freeze(Object.assign(base,{cargo:'UNKNOWN',cargoVisible:false}));const slots=root.KeloContainers?.getSlots?.(cart.inventoryId)||[];return Object.freeze(Object.assign(base,{cargoVisible:true,cargo:slots.filter(s=>s.item).map(s=>({key:s.key,item:clone(s.item)})),weight:cartWeight(cart.id),capacity:root.KeloContainers?.getStats?.(cart.inventoryId)||null}));}
function canActorAttack(pid){return !Object.values(ensure().carts).some(c=>c&&c.state==='ATTACHED'&&String(c.currentControllerId)===String(pid||actorId()));}
function attachedCartFor(pid){return Object.values(ensure().carts).find(c=>c&&c.state==='ATTACHED'&&String(c.currentControllerId)===String(pid||actorId()))||null;}
function validateNear(cart,pid,range){const entity=playerEntity(pid);if(!entity)return true;return dist(entity,cart.position)<=range;}
function attach(data){const cart=rawCart(data.cartId),pid=String(data.actorId||actorId());if(!cart)return{ok:false,error:'CART_NOT_FOUND'};if(cart.state==='DESTROYED')return{ok:false,error:'CART_DESTROYED'};if(attachedCartFor(pid))return{ok:false,error:'ACTOR_ALREADY_HAS_CART'};if(cart.state==='ATTACHED'&&cart.currentControllerId!==pid)return{ok:false,error:'CART_PROTECTED_BY_LIVING_CARRIER'};if(cart.state==='CLAIMING'&&cart.claim?.actorId!==pid)return{ok:false,error:'CART_BEING_CLAIMED'};const type=typeById.get(cart.typeId)||CART_TYPES[0];if(!validateNear(cart,pid,type.attachRange))return{ok:false,error:'OUT_OF_RANGE'};cart.state='ATTACHED';cart.currentControllerId=pid;cart.claim=null;bump(cart);save();emit(EVENTS.attached,{cartId:cart.id,controllerId:pid,revision:cart.revision});return{ok:true,cart:getCart(cart.id)};}
function detach(data,abandoned){const cart=rawCart(data.cartId),pid=String(data.actorId||actorId());if(!cart)return{ok:false,error:'CART_NOT_FOUND'};if(cart.state!=='ATTACHED'||String(cart.currentControllerId)!==pid)return{ok:false,error:'NOT_CART_CONTROLLER'};const entity=playerEntity(pid);if(entity)cart.position={x:Number(entity.x)||cart.position.x,y:(Number(entity.y)||cart.position.y)+38};cart.currentControllerId=null;cart.state='DROPPED';cart.claim=null;bump(cart);save();emit(abandoned?EVENTS.abandoned:EVENTS.detached,{cartId:cart.id,previousControllerId:pid,position:clone(cart.position),revision:cart.revision});return{ok:true,cart:getCart(cart.id)};}
function beginClaim(data){const cart=rawCart(data.cartId),pid=String(data.actorId||actorId());if(!cart)return{ok:false,error:'CART_NOT_FOUND'};if(cart.state==='ATTACHED')return{ok:false,error:'CART_ATTACHED_PROTECTED'};if(cart.state==='DESTROYED')return{ok:false,error:'CART_DESTROYED'};const type=typeById.get(cart.typeId)||CART_TYPES[0];if(!validateNear(cart,pid,type.attachRange))return{ok:false,error:'OUT_OF_RANGE'};cart.state='CLAIMING';cart.claim={actorId:pid,startedAt:now(),durationMs:type.claimDurationMs,interrupted:false};bump(cart);save();emit(EVENTS.claimStarted,{cartId:cart.id,actorId:pid,durationMs:type.claimDurationMs,revision:cart.revision});return{ok:true,cart:getCart(cart.id),claimDurationMs:type.claimDurationMs};}
function completeClaim(data){const cart=rawCart(data.cartId),pid=String(data.actorId||actorId());if(!cart||cart.state!=='CLAIMING'||!cart.claim)return{ok:false,error:'NO_ACTIVE_CLAIM'};if(cart.claim.actorId!==pid)return{ok:false,error:'CLAIM_OWNER_MISMATCH'};if(cart.claim.interrupted)return{ok:false,error:'CLAIM_INTERRUPTED'};const elapsed=now()-Number(cart.claim.startedAt||0);if(elapsed<Number(cart.claim.durationMs||0))return{ok:false,error:'CLAIM_IN_PROGRESS',remainingMs:Number(cart.claim.durationMs)-elapsed};cart.claim=null;cart.state='ATTACHED';cart.currentControllerId=pid;bump(cart);save();emit(EVENTS.claimed,{cartId:cart.id,controllerId:pid,owner:clone(cart.owner),revision:cart.revision});return{ok:true,cart:getCart(cart.id)};}
function interruptClaimsFor(pid,reason){let count=0;Object.values(ensure().carts).forEach(function(cart){if(cart&&cart.state==='CLAIMING'&&cart.claim&&String(cart.claim.actorId)===String(pid)){cart.claim.interrupted=true;cart.claim=null;cart.state='DROPPED';bump(cart);count++;emit(EVENTS.claimInterrupted,{cartId:cart.id,actorId:String(pid),reason:reason||'damage',revision:cart.revision});}});if(count)save();return count;}
function loadCart(data){const cart=rawCart(data.cartId);if(!cart)return{ok:false,error:'CART_NOT_FOUND'};if(cart.state==='ATTACHED'&&String(cart.currentControllerId)!==String(data.actorId||actorId()))return{ok:false,error:'NOT_CART_CONTROLLER'};const cp=root.KeloContainers?.checkpoint?.();if(!cp)return{ok:false,error:'CONTAINER_TRANSACTION_API_UNAVAILABLE'};const before=cartWeight(cart.id),r=root.KeloContainers.transferItem('backpack',cart.inventoryId,String(data.itemKey||''),data.quantity,{persist:false});if(!r.ok)return r;const type=typeById.get(cart.typeId)||CART_TYPES[0],after=cartWeight(cart.id);if(after>type.maxWeight+.0001){root.KeloContainers.restoreCheckpoint(cp,{persist:false});return{ok:false,error:'CART_OVERWEIGHT',maxWeight:type.maxWeight,weight:before};}bump(cart);save();emit(EVENTS.cargoChanged,{cartId:cart.id,reason:'load',weight:after,revision:cart.revision});return{ok:true,transfer:r,weight:after,maxWeight:type.maxWeight};}
function unloadCart(data){const cart=rawCart(data.cartId);if(!cart)return{ok:false,error:'CART_NOT_FOUND'};if(!canInspect(cart,data.actorId||actorId())&&String(cart.currentControllerId)!==String(data.actorId||actorId()))return{ok:false,error:'CARGO_ACCESS_DENIED'};const r=root.KeloContainers?.transferItem?.(cart.inventoryId,'backpack',String(data.itemKey||''),data.quantity,{persist:false});if(!r||!r.ok)return r||{ok:false,error:'CONTAINER_UNAVAILABLE'};bump(cart);save();emit(EVENTS.cargoChanged,{cartId:cart.id,reason:'unload',weight:cartWeight(cart.id),revision:cart.revision});return{ok:true,transfer:r,weight:cartWeight(cart.id)};}
function localRequest(type,payload){if(type==='AttachCart')return attach(payload||{});if(type==='DetachCart')return detach(payload||{},false);if(type==='BeginClaimCart'||type==='ClaimCart')return beginClaim(payload||{});if(type==='CompleteClaimCart')return completeClaim(payload||{});if(type==='LoadCart')return loadCart(payload||{});if(type==='UnloadCart')return unloadCart(payload||{});if(type==='Snapshot')return{ok:true,snapshot:snapshot()};return{ok:false,error:'UNKNOWN_COMMAND',command:String(type)};}
function mode(){if(injectedAuthority)return'injected-authority';if(root.KeloNetAuthority?.isOnline?.())return'server-authoritative';return'local-offline';}async function request(type,payload){try{if(injectedAuthority)return await injectedAuthority.request(type,payload||{});if(root.KeloNetAuthority?.isOnline?.()){if(typeof root.KeloNetAuthority.requestCaravan!=='function')return{ok:false,error:'CARAVAN_SERVER_BRIDGE_UNAVAILABLE'};const r=await root.KeloNetAuthority.requestCaravan(type,payload||{});if(r&&r.snapshot)lastServerSnapshot=clone(r.snapshot);return r;}return localRequest(String(type),payload||{});}catch(e){return{ok:false,error:String(e&&e.message||e)}}}function installAuthorityAdapter(a){if(a&&typeof a.request!=='function')throw new Error('INVALID_CARAVAN_ADAPTER');injectedAuthority=a||null;return mode();}
function snapshot(){if(mode()==='server-authoritative'&&lastServerSnapshot)return clone(lastServerSnapshot);return{version:VERSION,mode:mode(),states:STATES.slice(),types:clone(CART_TYPES),state:clone(ensure())};}
function updateAttached(){Object.values(ensure().carts).forEach(function(cart){if(!cart||cart.state!=='ATTACHED'||!cart.currentControllerId)return;const actor=playerEntity(cart.currentControllerId);if(!actor)return;let dx=Number(actor.vx)||0,dy=Number(actor.vy)||0,len=Math.hypot(dx,dy);if(len<1&&typeof input!=='undefined'){dx=Number(input.normX)||0;dy=Number(input.normY)||0;len=Math.hypot(dx,dy);}if(len<.01){dx=0;dy=1;len=1;}cart.position.x=(Number(actor.x)||0)-dx/len*44;cart.position.y=(Number(actor.y)||0)-dy/len*44;});}
function draw(){if(!root.KeloCamera||typeof ctx==='undefined')return;Object.values(ensure().carts).forEach(function(cart){if(!cart||cart.state==='DESTROYED')return;const p=root.KeloCamera.worldToScreen(cart.position.x,cart.position.y),z=root.KeloCamera.getEffectiveZoom?root.KeloCamera.getEffectiveZoom():1;if(p.x<-80||p.y<-80||p.x>innerWidth+80||p.y>innerHeight+80)return;ctx.save();ctx.translate(p.x,p.y);ctx.scale(Math.max(.65,z),Math.max(.65,z));ctx.fillStyle='rgba(28,20,12,.96)';ctx.strokeStyle='#c99b4d';ctx.lineWidth=2;ctx.fillRect(-22,-13,44,26);ctx.strokeRect(-22,-13,44,26);ctx.fillStyle='#6d4b2b';ctx.beginPath();ctx.arc(-16,16,7,0,Math.PI*2);ctx.arc(16,16,7,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#d7b36a';ctx.beginPath();ctx.moveTo(22,-3);ctx.lineTo(42,-3);ctx.stroke();if(cart.state==='CLAIMING'){ctx.strokeStyle='#f0cf72';ctx.beginPath();ctx.arc(0,0,31,0,Math.PI*2);ctx.stroke();}ctx.restore();});}
function abandonOnDeath(payload){const dead=String(payload&&payload.targetActorId||payload&&payload.target&&payload.target.id||'');if(!dead)return;const cart=attachedCartFor(dead);if(cart)detach({cartId:cart.id,actorId:dead},true);interruptClaimsFor(dead,'death');}
function damageInterrupt(payload){const target=String(payload&&payload.targetActorId||payload&&payload.target&&payload.target.id||'');if(target)interruptClaimsFor(target,'damage');}
ensure();if(root.KeloMovement?.after)root.KeloMovement.after('caravans:attached-follow',updateAttached,220);if(root.KeloRender?.afterFrame)root.KeloRender.afterFrame('caravans:physical-carts',draw,240);root.KeloEvents?.on?.('combat:damage_applied',damageInterrupt);root.KeloEvents?.on?.('combat:entity_killed',abandonOnDeath);
const dev=Object.freeze({killCarrier:function(cartId){const cart=rawCart(cartId);if(!cart||cart.state!=='ATTACHED')return{ok:false,error:'NO_CARRIER'};return detach({cartId:cart.id,actorId:cart.currentControllerId},true);},finishClaim:function(cartId,actor){const cart=rawCart(cartId);if(!cart||!cart.claim)return{ok:false,error:'NO_ACTIVE_CLAIM'};cart.claim.startedAt=now()-cart.claim.durationMs-1;return completeClaim({cartId:cartId,actorId:actor||cart.claim.actorId});},interruptClaimsFor:interruptClaimsFor});
root.KeloCaravans=Object.freeze({version:VERSION,events:EVENTS,states:STATES,types:CART_TYPES,getMode:mode,request:request,installAuthorityAdapter:installAuthorityAdapter,snapshot:snapshot,getCart:getCart,inspectCart:inspectCart,cartWeight:cartWeight,canActorAttack:canActorAttack,hasAttachedCart:function(pid){return!!attachedCartFor(pid);},raiderShouldAggro:function(entity){return!!(entity&&entity.hasCart===true)||!!attachedCartFor(entity&&entity.id);},dev:dev});root.KELO_CARAVAN_AUDIT=Object.freeze({version:VERSION,persistentWorldEntity:true,reusesContainers:true,ownerSeparatedFromController:true,attachedProtected:true,droppedClaimable:true,claimInterruptible:true,deathAbandons:true,cargoHidden:true,npcCargoBlind:true,physicalRender:true,movementHook:true,serverReplaceable:true});
})(typeof globalThis!=='undefined'?globalThis:window);
