/* KELO-INDEX
 * area: INVENTORY / CONTAINERS
 * owner: KeloContainers
 * keys: BACKPACK WAREHOUSE MARKET ESCROW TRADE TRANSACTION CHECKPOINT IDENTITY DYNAMIC CART
 * purpose: movimiento físico único de items entre contenedores con rollback, identidad estable y contenedores arbitrarios registrados
 * public-api: KeloContainers.transferItem/receiveItem/extractItem/checkpoint/restoreCheckpoint/registerContainer/removeContainer/getContainer
 * consumes: KeloBackpack, KeloEquipment, STATE/saveState
 * state-owned: warehouse, marketEscrow, tradeEscrow, emoteLoadout, dynamicContainers; backpack adapta STATE.inventory
 * extension-points: registerContainer para carts/almacenes futuros sin crear otro inventory engine
 * reuse: todo sistema que reserve, mueva, reciba o extraiga items debe pasar por este owner
 * online: el servidor puede replicar la misma semántica transaccional; este owner local no decide autoridad compartida
 * do-not: NO mutar arrays desde UI; NO duplicar identidad; NO crear CartInventorySystem; NO reutilizar market_escrow para trade
 */
(function(root){
'use strict';
const VERSION='container-v1.4.0',SCHEMA_VERSION=1,WAREHOUSE_CAPACITY=30,ESCROW_BASE_CAPACITY=20,TRADE_ESCROW_CAPACITY=12,EMOTE_LOADOUT_CAPACITY=4,OWNER='local_pioneer';
let ensuring=false;
function save(){if(typeof saveState==='function')saveState();}function cloneJson(v){return v==null?v:JSON.parse(JSON.stringify(v));}
function keyForItem(item,index){if(!item||typeof item!=='object')return null;if(item.id)return'id:'+String(item.id);if(item.uid)return'uid:'+String(item.uid);if(!item._backpackId)item._backpackId='bp_'+Date.now().toString(36)+'_'+String(index||0)+'_'+Math.random().toString(36).slice(2,8);return'bp:'+item._backpackId;}
function normalizeSlots(slots,n){const out=Array.isArray(slots)?slots.slice(0,n):[];while(out.length<n)out.push(null);return out;}function itemMap(items){const m=new Map();(items||[]).forEach((item,i)=>{const k=keyForItem(item,i);if(k&&!m.has(k))m.set(k,item);});return m;}function rebuildSlots(slots,items,capacity){const valid=itemMap(items),out=new Array(capacity).fill(null),placed=new Set();normalizeSlots(slots,capacity).forEach((k,i)=>{if(k&&valid.has(k)&&!placed.has(k)){out[i]=k;placed.add(k);}});valid.forEach((item,k)=>{if(placed.has(k))return;const i=out.indexOf(null);if(i>=0){out[i]=k;placed.add(k);}});return out;}
function ensureContainerState(current,defaults,minCapacity){let c=current,changed=false;if(!c||typeof c!=='object'){c=Object.assign({},defaults,{slots:[],items:[],permissions:Object.assign({},defaults.permissions)});changed=true;}c.schemaVersion=SCHEMA_VERSION;c.id=String(defaults.id);c.type=String(defaults.type||defaults.id);c.owner=c.owner||defaults.owner||OWNER;c.capacity=Math.max(minCapacity||1,Math.floor(Number(c.capacity)||minCapacity||1));if(!Array.isArray(c.items)){c.items=[];changed=true;}c.permissions=Object.assign({},defaults.permissions||{},c.permissions||{});const slots=rebuildSlots(c.slots,c.items,c.capacity);if(JSON.stringify(c.slots)!==JSON.stringify(slots)){c.slots=slots;changed=true;}return{container:c,changed};}
function ensure(){if(typeof STATE==='undefined')return null;if(ensuring)return STATE.warehouse||null;ensuring=true;let changed=false;try{if(!Array.isArray(STATE.inventory)){STATE.inventory=[];changed=true;}if(root.KeloBackpack?.ensure)root.KeloBackpack.ensure();const defs=[['warehouse','warehouse',{id:'warehouse_main',type:'warehouse',owner:OWNER,capacity:WAREHOUSE_CAPACITY,permissions:{deposit:true,withdraw:true,merge:true}},WAREHOUSE_CAPACITY],['marketEscrow','market_escrow',{id:'market_escrow',type:'market_escrow',owner:OWNER,capacity:ESCROW_BASE_CAPACITY,permissions:{deposit:true,withdraw:true,merge:false,elastic:true}},ESCROW_BASE_CAPACITY],['tradeEscrow','trade_escrow',{id:'trade_escrow',type:'trade_escrow',owner:OWNER,capacity:TRADE_ESCROW_CAPACITY,permissions:{deposit:true,withdraw:true,merge:false,elastic:false}},TRADE_ESCROW_CAPACITY],['emoteLoadout','emote_loadout',{id:'emote_loadout',type:'emote_loadout',owner:OWNER,capacity:EMOTE_LOADOUT_CAPACITY,permissions:{deposit:true,withdraw:true,merge:false,elastic:false}},EMOTE_LOADOUT_CAPACITY]];defs.forEach(row=>{const n=ensureContainerState(STATE[row[0]],row[2],row[3]);STATE[row[0]]=n.container;changed=changed||n.changed;});if(!STATE.dynamicContainers||typeof STATE.dynamicContainers!=='object'||Array.isArray(STATE.dynamicContainers)){STATE.dynamicContainers={};changed=true;}Object.keys(STATE.dynamicContainers).forEach(id=>{const raw=STATE.dynamicContainers[id];if(!raw||typeof raw!=='object'){delete STATE.dynamicContainers[id];changed=true;return;}const min=Math.max(1,Math.floor(Number(raw.capacity)||1)),n=ensureContainerState(raw,{id,type:raw.type||'generic',owner:raw.owner||OWNER,capacity:min,permissions:Object.assign({deposit:true,withdraw:true,merge:true,elastic:false},raw.permissions||{})},min);STATE.dynamicContainers[id]=n.container;changed=changed||n.changed;});}finally{ensuring=false;}if(changed)save();return STATE.warehouse;}
function source(type){ensure();const key=String(type||'');if(key==='backpack'){if(root.KeloBackpack?.ensure)root.KeloBackpack.ensure();return{type:'backpack',id:'backpack',owner:OWNER,items:STATE.inventory,slots:STATE.backpack.slots,capacity:STATE.backpack.capacity,permissions:{deposit:true,withdraw:true,merge:true}};}if(key==='warehouse'||key==='warehouse_main')return STATE.warehouse;if(key==='market_escrow')return STATE.marketEscrow;if(key==='trade_escrow')return STATE.tradeEscrow;if(key==='emote_loadout')return STATE.emoteLoadout;return STATE.dynamicContainers&&STATE.dynamicContainers[key]||null;}
function registerContainer(definition,options){ensure();const def=definition||{},id=String(def.id||'').trim();if(!id)return{ok:false,error:'INVALID_CONTAINER_ID'};const current=STATE.dynamicContainers[id];if(current&&!(options&&options.update))return{ok:true,created:false,container:current};const min=Math.max(1,Math.floor(Number(def.capacity)||(current&&current.capacity)||1)),n=ensureContainerState(current,Object.assign({id,type:def.type||'generic',owner:def.owner||OWNER,capacity:min,permissions:{deposit:true,withdraw:true,merge:true,elastic:false}},def),min);STATE.dynamicContainers[id]=n.container;if(!options||options.persist!==false)save();return{ok:true,created:!current,container:n.container};}
function removeContainer(id,options){ensure();const key=String(id||''),c=STATE.dynamicContainers[key];if(!c)return{ok:false,error:'CONTAINER_NOT_FOUND'};if(!(options&&options.force)&&((c.items&&c.items.length)||(c.slots||[]).some(Boolean)))return{ok:false,error:'CONTAINER_NOT_EMPTY'};delete STATE.dynamicContainers[key];if(!options||options.persist!==false)save();return{ok:true,id:key};}
function quantity(item){return Math.max(1,Math.floor(Number(item&&item.quantity)||1));}function stackLimit(item){return Math.max(1,Math.floor(Number(item&&item.maxStack)||1));}function stackSignature(item){if(!item||item.kind==='equipment'||item.kind==='emote'||stackLimit(item)<=1)return null;if(item.stackKey)return'stack:'+String(item.stackKey);if(item.templateId)return'template:'+String(item.templateId);if(item.resourceId)return'resource:'+String(item.resourceId)+':tier:'+String(item.tier||'T1');if(item.typeId)return'type:'+String(item.typeId)+':tier:'+String(item.tier||'')+':quality:'+String(item.quality||'');return null;}function canStack(a,b){const x=stackSignature(a),y=stackSignature(b);return!!(x&&y&&x===y);}
function getSlots(type){const c=source(type);if(!c)return[];const m=itemMap(c.items);return c.slots.map((key,index)=>({index,key:key||null,item:key?m.get(key)||null:null}));}function getStats(type){const c=source(type);if(!c)return{capacity:0,used:0,free:0};const used=c.slots.filter(Boolean).length;return{id:c.id,type:c.type,owner:c.owner,capacity:c.capacity,used,free:c.capacity-used};}function getContainer(type){return source(type);}
function newIdentity(item,prefix){const id=(prefix||'stack')+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,9);if(Object.prototype.hasOwnProperty.call(item,'id'))item.id=id;else if(Object.prototype.hasOwnProperty.call(item,'uid'))item.uid=id;else item._backpackId=id;return item;}
function allContainerSources(){ensure();const out=[source('backpack'),STATE.warehouse,STATE.marketEscrow,STATE.tradeEscrow,STATE.emoteLoadout];Object.keys(STATE.dynamicContainers||{}).forEach(id=>out.push(STATE.dynamicContainers[id]));return out.filter(Boolean);}function identityExists(key){if(!key)return false;return allContainerSources().some(c=>c.slots.includes(key)||itemMap(c.items).has(key));}
function cloneState(){ensure();return{inventory:cloneJson(STATE.inventory),backpack:cloneJson(STATE.backpack),warehouse:cloneJson(STATE.warehouse),marketEscrow:cloneJson(STATE.marketEscrow),tradeEscrow:cloneJson(STATE.tradeEscrow),emoteLoadout:cloneJson(STATE.emoteLoadout),dynamicContainers:cloneJson(STATE.dynamicContainers)};}function restore(s){if(!s)return false;STATE.inventory=s.inventory;STATE.backpack=s.backpack;STATE.warehouse=s.warehouse;STATE.marketEscrow=s.marketEscrow;STATE.tradeEscrow=s.tradeEscrow;STATE.emoteLoadout=s.emoteLoadout;STATE.dynamicContainers=s.dynamicContainers||{};return true;}function checkpoint(){return cloneState();}function restoreCheckpoint(s,options){const ok=restore(cloneJson(s));if(ok&&(!options||options.persist!==false))save();return{ok};}
function ensureElasticRoom(dst,item,amount){if(!dst?.permissions||dst.permissions.elastic!==true)return;const needed=Math.max(1,Math.ceil(amount/stackLimit(item))),free=dst.slots.filter(k=>!k).length;if(free>=needed)return;for(let i=0;i<needed-free;i++)dst.slots.push(null);dst.capacity=dst.slots.length;}
function compatibleTargets(dst,item,allowMerge){const out=[];let room=0;if(allowMerge!==false&&dst.permissions.merge!==false&&stackSignature(item)){const m=itemMap(dst.items);dst.slots.forEach(k=>{const target=k?m.get(k):null;if(target&&canStack(item,target)){const r=Math.max(0,stackLimit(target)-quantity(target));if(r){out.push({item:target,room:r});room+=r;}}});}return{targets:out,room};}function availableRoom(dst,item,allowMerge){const c=compatibleTargets(dst,item,allowMerge);return c.room+dst.slots.filter(k=>!k).length*stackLimit(item);}function sourceGuard(type,item){if(type==='backpack'&&item.kind==='equipment'&&root.KeloEquipment?.isEquipped?.(item.id))return'EQUIPPED_ITEM_PROTECTED';return null;}
function transferItem(sourceType,destType,itemKey,amount,options){options=options||{};const src=source(sourceType),dst=source(destType);if(!src||!dst||src.id===dst.id)return{ok:false,error:'INVALID_CONTAINER'};const m=itemMap(src.items),item=m.get(String(itemKey));if(!item)return{ok:false,error:'ITEM_NOT_FOUND'};const index=src.slots.indexOf(String(itemKey));if(index<0)return{ok:false,error:'INVALID_SOURCE'};const guard=sourceGuard(sourceType,item);if(guard)return{ok:false,error:guard};const current=quantity(item);amount=amount==null?current:Math.floor(Number(amount));if(!Number.isInteger(amount)||amount<1||amount>current)return{ok:false,error:'INVALID_AMOUNT'};if(destType==='emote_loadout'&&item.kind!=='emote')return{ok:false,error:'EMOTE_ONLY_CONTAINER'};ensureElasticRoom(dst,item,amount);const capacity=availableRoom(dst,item,options.allowMerge);if(capacity<amount)return{ok:false,error:'DESTINATION_FULL',requested:amount,available:capacity};const snap=cloneState();let remaining=amount,merged=0,movedItemKey=null,createdKeys=[];try{for(const t of compatibleTargets(dst,item,options.allowMerge).targets){if(!remaining)break;const n=Math.min(t.room,remaining);t.item.quantity=quantity(t.item)+n;remaining-=n;merged+=n;}if(amount===current){if(remaining>0){item.quantity=current-merged;src.slots[index]=null;const pos=src.items.indexOf(item);if(pos>=0)src.items.splice(pos,1);const free=dst.slots.indexOf(null);if(free<0)throw Error('DESTINATION_FULL');dst.items.push(item);dst.slots[free]=String(itemKey);movedItemKey=String(itemKey);remaining=0;}else{src.slots[index]=null;const pos=src.items.indexOf(item);if(pos>=0)src.items.splice(pos,1);}}else{item.quantity=current-amount;while(remaining>0){const free=dst.slots.indexOf(null);if(free<0)throw Error('DESTINATION_FULL');const n=Math.min(stackLimit(item),remaining),piece=newIdentity(Object.assign({},item,{quantity:n,createdAt:Date.now(),splitFrom:item.id||item.uid||item._backpackId||null}),'stack');const key=keyForItem(piece,dst.items.length);dst.items.push(piece);dst.slots[free]=key;createdKeys.push(key);if(!movedItemKey)movedItemKey=key;remaining-=n;}}if(options.persist!==false)save();return{ok:true,source:sourceType,destination:destType,itemKey:String(itemKey),requested:amount,moved:amount,merged,createdKeys,preservedIdentity:amount===current&&!!movedItemKey,movedItemKey,sourceRemaining:amount===current?0:quantity(item)};}catch(err){restore(snap);if(options.persist!==false)save();return{ok:false,error:'ROLLBACK',reason:String(err&&err.message||err)};}}
function receiveItem(destType,item,options){options=options||{};const dst=source(destType);if(!dst)return{ok:false,error:'INVALID_CONTAINER'};if(!item||typeof item!=='object')return{ok:false,error:'INVALID_ITEM'};if(destType==='emote_loadout'&&item.kind!=='emote')return{ok:false,error:'EMOTE_ONLY_CONTAINER'};const originalQty=quantity(item),template=cloneJson(item);template.quantity=originalQty;ensureElasticRoom(dst,template,originalQty);const capacity=availableRoom(dst,template,options.allowMerge);if(capacity<originalQty)return{ok:false,error:'DESTINATION_FULL',requested:originalQty,available:capacity};const originalKey=options.preserveIdentity===true?keyForItem(template,dst.items.length):null;if(originalKey&&identityExists(originalKey))return{ok:false,error:'DUPLICATE_IDENTITY',itemKey:originalKey};const snap=cloneState();let remaining=originalQty,merged=0,firstItem=null,firstKey=null;try{for(const t of compatibleTargets(dst,template,options.allowMerge).targets){if(!remaining)break;const n=Math.min(t.room,remaining);t.item.quantity=quantity(t.item)+n;remaining-=n;merged+=n;if(!firstItem){firstItem=t.item;firstKey=keyForItem(t.item);}}let pieceIndex=0;while(remaining>0){const free=dst.slots.indexOf(null);if(free<0)throw Error('DESTINATION_FULL');const n=Math.min(stackLimit(template),remaining),piece=Object.assign({},template,{quantity:n});if(!(options.preserveIdentity===true&&pieceIndex===0))newIdentity(piece,'recv');let key=keyForItem(piece,dst.items.length);if(identityExists(key)){newIdentity(piece,'recv');key=keyForItem(piece,dst.items.length);}dst.items.push(piece);dst.slots[free]=key;if(!firstItem){firstItem=piece;firstKey=key;}pieceIndex++;remaining-=n;}if(options.persist!==false)save();return{ok:true,destination:destType,item:firstItem,itemKey:firstKey,moved:originalQty,merged,preservedIdentity:options.preserveIdentity===true};}catch(err){restore(snap);if(options.persist!==false)save();return{ok:false,error:'ROLLBACK',reason:String(err&&err.message||err)};}}
function extractItem(sourceType,itemKey,options){options=options||{};const src=source(sourceType);if(!src)return{ok:false,error:'INVALID_CONTAINER'};const m=itemMap(src.items),item=m.get(String(itemKey));if(!item)return{ok:false,error:'ITEM_NOT_FOUND'};const slot=src.slots.indexOf(String(itemKey));if(slot<0)return{ok:false,error:'INVALID_SOURCE'};const guard=sourceGuard(sourceType,item);if(guard)return{ok:false,error:guard};const current=quantity(item),amount=options.amount==null?current:Math.floor(Number(options.amount));if(!Number.isInteger(amount)||amount<1||amount>current)return{ok:false,error:'INVALID_AMOUNT'};const snap=cloneState();try{let out;if(amount===current){out=item;src.slots[slot]=null;const i=src.items.indexOf(item);if(i<0)throw Error('ITEM_NOT_FOUND');src.items.splice(i,1);}else{item.quantity=current-amount;out=newIdentity(Object.assign({},item,{quantity:amount,splitFrom:item.id||item.uid||item._backpackId||null}),'extract');}if(options.persist!==false)save();return{ok:true,source:sourceType,item:out,itemKey:String(itemKey),quantity:amount,sourceRemaining:amount===current?0:quantity(item)};}catch(err){restore(snap);if(options.persist!==false)save();return{ok:false,error:'ROLLBACK',reason:String(err&&err.message||err)};}}
function auditIdentities(){const seen=new Map(),errors=[];allContainerSources().forEach(c=>(c.items||[]).forEach((item,index)=>{const key=keyForItem(item,index);if(!key){errors.push({code:'MISSING_IDENTITY',container:c.id,index});return;}if(seen.has(key))errors.push({code:'DUPLICATE_IDENTITY',key,containers:[seen.get(key),c.id]});else seen.set(key,c.id);}));return{ok:errors.length===0,errors,uniqueIdentities:seen.size,containers:allContainerSources().length};}
ensure();
root.KeloContainers=Object.freeze({version:VERSION,schemaVersion:SCHEMA_VERSION,warehouseCapacity:WAREHOUSE_CAPACITY,marketEscrowBaseCapacity:ESCROW_BASE_CAPACITY,tradeEscrowCapacity:TRADE_ESCROW_CAPACITY,emoteLoadoutCapacity:EMOTE_LOADOUT_CAPACITY,ensure,keyForItem,getSlots,getStats,getContainer,registerContainer,removeContainer,transferItem,receiveItem,extractItem,checkpoint,restoreCheckpoint,auditIdentities,canStack,stackSignature});
root.KELO_CONTAINER_AUDIT=Object.freeze({version:VERSION,schemaVersion:SCHEMA_VERSION,identityRule:'one-item-one-container',containerModel:'static-plus-dynamic-shared-contract-v5',transferMode:'validate-prepare-execute-persist-rollback-v4',strictDestinationCapacity:true,warehouseImplemented:true,marketEscrowImplemented:true,tradeEscrowImplemented:true,emoteLoadoutImplemented:true,dynamicContainers:true,arbitraryContainerRegistration:true,checkpointTransactions:true,detachedReceiveExtract:true,partialExtract:true,deferredPersistSupported:true,serverAuthoritative:false});
})(typeof globalThis!=='undefined'?globalThis:window);
