/* KELO-INDEX
 * area: GUARDIAN
 * owner: KeloGuardian
 * keys: GUARDIAN DONATION IDLE IOS HOST HEARTBEAT CAPABILITY WEBRTC DATACHANNEL SIGNAL P2P MASTER
 * purpose: posee preferencia de donación, disponibilidad y el data plane WebRTC directo entre nodos Guardian y el Master activo
 * online: Supabase coordina identidad/lease/signaling; WebRTC transporta bytes directos; gameplay autoritativo sigue fuera hasta migración explícita
 * do-not: NO prometer background continuo en iOS; NO calcular recompensas autoritativas; NO segundo loop; NO declarar WebRTC como autoridad gameplay
 */
(function(root){
'use strict';
if(root.KeloGuardian)return;
const VERSION='kelo-guardian-v2-webrtc',PREF_KEY='kelo.guardian.preferences.v1',NODE_KEY='kelo.guardian.node.v1';
const HEARTBEAT_MS=8000,SIGNAL_POLL_MS=900,PING_MS=5000,MAX_DATA_BYTES=64*1024;
const defaults=Object.freeze({enabled:false,idleDonation:true,wifiOnly:true,chargingOnly:false,allowAssets:true,allowRelay:true,allowCompute:false,maxUploadMbps:10,storageMb:512});
let prefs=loadPrefs(),serverState=null,lastError=null,lastHeartbeatAt=0,inFlight=false,wasOnline=false;
let signalInFlight=false,lastSignalPollAt=0,lastPingAt=0,observedMasterEpoch=0,observedMasterNodeId=null;
const peers=new Map();
const transportStats={bytesSent:0,bytesReceived:0,signalsSent:0,signalsReceived:0,peerOpens:0,peerCloses:0,lastRttMs:null,lastDirectAt:null,lastTransportError:null};
function uuid(){if(root.crypto&&typeof root.crypto.randomUUID==='function')return root.crypto.randomUUID();return'guardian-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,14);}
function resolveNodeId(){try{let id=localStorage.getItem(NODE_KEY);if(!id){id='g_'+uuid().replace(/[^A-Za-z0-9_-]/g,'').slice(0,80);localStorage.setItem(NODE_KEY,id);}return id;}catch(_){return'g_'+uuid().replace(/[^A-Za-z0-9_-]/g,'').slice(0,80);}}
const LOCAL_NODE_ID=resolveNodeId();
function nodeId(){return LOCAL_NODE_ID;}
function loadPrefs(){try{return Object.assign({},defaults,JSON.parse(localStorage.getItem(PREF_KEY)||'null')||{});}catch(_){return{...defaults};}}
function savePrefs(){try{localStorage.setItem(PREF_KEY,JSON.stringify(prefs));}catch(_){} }
function isIOS(){const ua=String(navigator.userAgent||'');return /iPad|iPhone|iPod/i.test(ua)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);}
function platform(){if(isIOS())return'ios';if(/Android/i.test(String(navigator.userAgent||'')))return'android';if(/Windows|Macintosh|Linux/i.test(String(navigator.userAgent||'')))return'desktop';return'web';}
function deviceClass(){const min=Math.min(screen.width||0,screen.height||0),touch=(navigator.maxTouchPoints||0)>0;if(touch&&min&&min<600)return'phone';if(touch&&min<1000)return'tablet';if(!touch)return'desktop';return'unknown';}
function screenClass(){const w=Math.round(innerWidth||screen.width||0),h=Math.round(innerHeight||screen.height||0);if(!w||!h)return'unknown';const m=Math.min(w,h);return m<600?'small':m<900?'medium':'large';}
function capabilitySnapshot(){const c=navigator.connection||navigator.mozConnection||navigator.webkitConnection||null;return{platform:platform(),deviceClass:deviceClass(),visibility:document.visibilityState||'unknown',online:navigator.onLine!==false,webrtc:typeof root.RTCPeerConnection==='function',serviceWorker:'serviceWorker'in navigator,saveData:!!c?.saveData,touch:(navigator.maxTouchPoints||0)>0,cores:Number(navigator.hardwareConcurrency)||1,memoryGb:Number(navigator.deviceMemory)||0,batteryLevel:null,charging:null,networkType:String(c?.type||'unknown'),effectiveType:String(c?.effectiveType||'unknown'),screenClass:screenClass()};}
async function enrichBattery(snapshot){try{if(typeof navigator.getBattery==='function'){const b=await navigator.getBattery();snapshot.batteryLevel=Number.isFinite(b.level)?b.level:null;snapshot.charging=!!b.charging;}}catch(_){}return snapshot;}
function masterDescriptor(){const m=serverState?.master;if(m?.nodeId)return{nodeId:String(m.nodeId),epoch:Number(m.epoch)||0,expiresAt:Number(m.expiresAt)||0};const n=serverState?.network||{};return n.masterNodeId?{nodeId:String(n.masterNodeId),epoch:Number(n.masterEpoch)||0,expiresAt:0}:null;}
function byteLength(value){try{return new Blob([typeof value==='string'?value:JSON.stringify(value)]).size;}catch(_){return String(value||'').length;}}
function rtcConfig(){const custom=root.KELO_GUARDIAN_ICE_SERVERS;return{iceServers:Array.isArray(custom)&&custom.length?custom:[{urls:'stun:stun.cloudflare.com:3478'}]};}
function transportSnapshot(){const m=masterDescriptor(),rows=[...peers.values()],open=rows.filter(p=>p.channel?.readyState==='open'),masterPeer=m&&peers.get(m.nodeId);return Object.freeze({mode:'webrtc-direct-v1',supported:typeof root.RTCPeerConnection==='function',masterNodeId:m?.nodeId||null,masterEpoch:m?.epoch||0,peerCount:rows.length,openPeerCount:open.length,connectedToMaster:!!(masterPeer&&masterPeer.channel?.readyState==='open'),rttMs:masterPeer?.lastRttMs??transportStats.lastRttMs,bytesSent:transportStats.bytesSent,bytesReceived:transportStats.bytesReceived,signalsSent:transportStats.signalsSent,signalsReceived:transportStats.signalsReceived,lastDirectAt:transportStats.lastDirectAt,lastError:transportStats.lastTransportError});}
function emit(){const detail=state();try{root.dispatchEvent(new CustomEvent('kelo:guardian-state',{detail}));}catch(_){}return detail;}
function state(){const node=serverState?.node||null,network=serverState?.network||null;return Object.freeze({version:VERSION,nodeId:nodeId(),enabled:!!prefs.enabled,preferences:Object.freeze({...prefs}),platform:platform(),ios:isIOS(),connected:!!node,role:node?.role||'off',recommendedRoles:Object.freeze([...(node?.recommendedRoles||[])]),masterEligible:!!serverState?.masterEligible,masterActive:node?.role==='master-host',masterLeaseExpiresAt:node?.masterLeaseExpiresAt||null,network,master:masterDescriptor(),dataPlane:transportSnapshot(),lastError,backgroundContinuousGuaranteed:false});}
async function payload(){return{nodeId:nodeId(),capabilities:await enrichBattery(capabilitySnapshot()),preferences:{...prefs}};}
function closePeer(remoteNodeId,reason){const key=String(remoteNodeId||''),peer=peers.get(key);if(!peer)return false;peers.delete(key);try{peer.channel?.close();}catch(_){}try{peer.pc?.close();}catch(_){}transportStats.peerCloses++;try{root.dispatchEvent(new CustomEvent('kelo:guardian-peer-close',{detail:{nodeId:key,reason:reason||'closed'}}));}catch(_){}return true;}
function closeAllPeers(reason){[...peers.keys()].forEach(id=>closePeer(id,reason));observedMasterNodeId=null;observedMasterEpoch=0;emit();}
function sendPeer(peer,message){if(!peer||peer.channel?.readyState!=='open')return false;let raw;try{raw=JSON.stringify(message);}catch(_){return false;}const size=byteLength(raw);if(size>MAX_DATA_BYTES)return false;try{peer.channel.send(raw);transportStats.bytesSent+=size;transportStats.lastDirectAt=Date.now();return true;}catch(error){transportStats.lastTransportError=String(error&&error.message||error);return false;}}
function emitGuardianData(fromNodeId,payload){try{root.dispatchEvent(new CustomEvent('kelo:guardian-data',{detail:{fromNodeId,payload,authoritative:false,transport:'webrtc'}}));}catch(_){} }
function onPeerMessage(peer,event){const raw=event?.data,size=byteLength(raw);transportStats.bytesReceived+=size;transportStats.lastDirectAt=Date.now();peer.lastMessageAt=Date.now();let msg=null;try{msg=typeof raw==='string'?JSON.parse(raw):null;}catch(_){return;}if(!msg||typeof msg!=='object')return;
  if(msg.t==='guardian:ping'){sendPeer(peer,{t:'guardian:pong',nonce:String(msg.nonce||''),sentAt:Number(msg.sentAt)||0,at:Date.now()});return;}
  if(msg.t==='guardian:pong'){const sent=peer.pendingPings.get(String(msg.nonce||''));if(sent){peer.pendingPings.delete(String(msg.nonce||''));peer.lastRttMs=Math.max(0,Date.now()-sent);transportStats.lastRttMs=peer.lastRttMs;emit();}return;}
  if(msg.t==='guardian:hello'){peer.remoteEpoch=Number(msg.epoch)||0;sendPeer(peer,{t:'guardian:hello_ack',nodeId:nodeId(),epoch:masterDescriptor()?.epoch||0,at:Date.now()});return;}
  if(msg.t==='guardian:hello_ack'){peer.remoteEpoch=Number(msg.epoch)||0;return;}
  emitGuardianData(peer.nodeId,msg);
}
function attachChannel(peer,channel){if(!peer||!channel)return;peer.channel=channel;channel.binaryType='arraybuffer';channel.onopen=()=>{peer.connectedAt=Date.now();peer.lastMessageAt=peer.connectedAt;transportStats.peerOpens++;sendPeer(peer,{t:'guardian:hello',nodeId:nodeId(),epoch:masterDescriptor()?.epoch||0,role:state().masterActive?'master-host':'donor-ready',at:Date.now()});try{root.dispatchEvent(new CustomEvent('kelo:guardian-peer-open',{detail:{nodeId:peer.nodeId,master:state().masterActive}}));}catch(_){}emit();};channel.onmessage=event=>onPeerMessage(peer,event);channel.onclose=()=>{if(peers.get(peer.nodeId)===peer)closePeer(peer.nodeId,'datachannel-closed');emit();};channel.onerror=()=>{transportStats.lastTransportError='GUARDIAN_DATACHANNEL_ERROR';emit();};}
async function sendSignal(remoteNodeId,type,data){if(!root.KeloGuardianAuthority?.sendSignal)return false;try{await root.KeloGuardianAuthority.sendSignal({nodeId:nodeId(),toNodeId:String(remoteNodeId),type:String(type),data:data||{}});transportStats.signalsSent++;return true;}catch(error){transportStats.lastTransportError=String(error&&error.message||error);emit();return false;}}
function createPeer(remoteNodeId,initiator){const id=String(remoteNodeId||'');if(!id||id===nodeId()||typeof root.RTCPeerConnection!=='function')return null;const current=peers.get(id);if(current&&current.pc?.connectionState!=='closed'&&current.pc?.connectionState!=='failed')return current;if(current)closePeer(id,'recreate');const pc=new root.RTCPeerConnection(rtcConfig()),peer={nodeId:id,pc,channel:null,initiator:!!initiator,pendingIce:[],pendingPings:new Map(),lastRttMs:null,connectedAt:null,lastMessageAt:null,offerStarted:false};peers.set(id,peer);
  pc.onicecandidate=event=>{if(event.candidate)sendSignal(id,'ice',{epoch:masterDescriptor()?.epoch||0,candidate:event.candidate.toJSON?event.candidate.toJSON():event.candidate});};
  pc.ondatachannel=event=>attachChannel(peer,event.channel);
  pc.onconnectionstatechange=()=>{const cs=pc.connectionState;if(cs==='failed'||cs==='closed')closePeer(id,'rtc-'+cs);emit();};
  if(initiator){const channel=pc.createDataChannel('kelo-guardian',{ordered:true});attachChannel(peer,channel);peer.offerStarted=true;Promise.resolve().then(async()=>{try{const offer=await pc.createOffer();await pc.setLocalDescription(offer);await sendSignal(id,'offer',{epoch:masterDescriptor()?.epoch||0,description:{type:pc.localDescription.type,sdp:pc.localDescription.sdp}});}catch(error){transportStats.lastTransportError=String(error&&error.message||error);closePeer(id,'offer-failed');emit();}});}
  return peer;
}
async function flushIce(peer){if(!peer||!peer.pc?.remoteDescription)return;const queued=peer.pendingIce.splice(0);for(const candidate of queued){try{await peer.pc.addIceCandidate(candidate);}catch(_){} }}
async function handleSignal(signal){if(!signal||!signal.fromNodeId||!signal.type)return;const from=String(signal.fromNodeId),type=String(signal.type),data=signal.data||{},master=masterDescriptor();if(!master)return;if(!state().masterActive&&from!==master.nodeId)return;if(data.epoch&&Number(data.epoch)!==Number(master.epoch))return;transportStats.signalsReceived++;
  if(type==='bye'){closePeer(from,'remote-bye');return;}
  if(type==='offer'){
    if(!state().masterActive)return;let peer=peers.get(from);if(peer)closePeer(from,'new-offer');peer=createPeer(from,false);if(!peer)return;try{await peer.pc.setRemoteDescription(data.description);await flushIce(peer);const answer=await peer.pc.createAnswer();await peer.pc.setLocalDescription(answer);await sendSignal(from,'answer',{epoch:master.epoch,description:{type:peer.pc.localDescription.type,sdp:peer.pc.localDescription.sdp}});}catch(error){transportStats.lastTransportError=String(error&&error.message||error);closePeer(from,'answer-failed');}return;
  }
  const peer=peers.get(from);if(!peer)return;
  if(type==='answer'){try{await peer.pc.setRemoteDescription(data.description);await flushIce(peer);}catch(error){transportStats.lastTransportError=String(error&&error.message||error);}return;}
  if(type==='ice'&&data.candidate){if(peer.pc.remoteDescription){try{await peer.pc.addIceCandidate(data.candidate);}catch(_){}}else peer.pendingIce.push(data.candidate);}
}
async function pollSignals(){if(signalInFlight||!prefs.enabled||!serverState?.node||!root.KeloGuardianAuthority?.pollSignals)return;const now=Date.now(),master=masterDescriptor(),masterPeer=master&&peers.get(master.nodeId),fast=state().masterActive||!masterPeer||masterPeer.channel?.readyState!=='open',interval=fast?SIGNAL_POLL_MS:10000;if(now-lastSignalPollAt<interval)return;lastSignalPollAt=now;signalInFlight=true;try{const result=await root.KeloGuardianAuthority.pollSignals(nodeId()),list=Array.isArray(result?.signals)?result.signals:[];for(const signal of list)await handleSignal(signal);}catch(error){transportStats.lastTransportError=String(error&&error.message||error);}finally{signalInFlight=false;}}
function reconcileTransport(){const master=masterDescriptor(),enabled=prefs.enabled&&!!serverState?.node&&typeof root.RTCPeerConnection==='function';if(!enabled||!master){if(peers.size)closeAllPeers('no-master');return;}const epochChanged=observedMasterEpoch&&Number(master.epoch)!==Number(observedMasterEpoch),masterChanged=observedMasterNodeId&&master.nodeId!==observedMasterNodeId;if(epochChanged||masterChanged)closeAllPeers('master-changed');observedMasterEpoch=Number(master.epoch)||0;observedMasterNodeId=master.nodeId;
  if(state().masterActive){for(const [id,peer] of peers)if(peer.initiator)closePeer(id,'master-does-not-initiate');return;}
  for(const id of [...peers.keys()])if(id!==master.nodeId)closePeer(id,'not-current-master');if(!peers.has(master.nodeId))createPeer(master.nodeId,true);
}
function pingPeers(now){if(now-lastPingAt<PING_MS)return;lastPingAt=now;for(const peer of peers.values()){if(peer.channel?.readyState!=='open')continue;const nonce=Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7);peer.pendingPings.set(nonce,Date.now());while(peer.pendingPings.size>4)peer.pendingPings.delete(peer.pendingPings.keys().next().value);sendPeer(peer,{t:'guardian:ping',nonce,sentAt:Date.now()});}}
function transportTick(){if(!prefs.enabled)return;if(navigator.onLine===false)return;reconcileTransport();pollSignals();pingPeers(Date.now());}
function apply(result){serverState=result||null;lastError=null;reconcileTransport();emit();return state();}
async function refresh(){if(!root.KeloGuardianAuthority)throw new Error('GUARDIAN_AUTHORITY_UNAVAILABLE');try{return apply(await root.KeloGuardianAuthority.status(nodeId()));}catch(error){lastError=String(error&&error.message||error);emit();throw error;}}
async function activate(){prefs.enabled=true;savePrefs();try{return apply(await root.KeloGuardianAuthority.enable(await payload()));}catch(error){lastError=String(error&&error.message||error);emit();throw error;}}
async function deactivate(){prefs.enabled=false;savePrefs();closeAllPeers('guardian-off');try{if(root.KeloGuardianAuthority)return apply(await root.KeloGuardianAuthority.disable({nodeId:nodeId()}));}catch(error){lastError=String(error&&error.message||error);}serverState=null;emit();return state();}
async function startMasterHost(){if(!prefs.enabled)await activate();else await heartbeat(true);try{return apply(await root.KeloGuardianAuthority.startMaster(await payload()));}catch(error){lastError=String(error&&error.message||error);emit();throw error;}}
async function stopMasterHost(){try{return apply(await root.KeloGuardianAuthority.stopMaster({nodeId:nodeId()}));}catch(error){lastError=String(error&&error.message||error);emit();throw error;}}
async function heartbeat(force){if(!prefs.enabled||inFlight||!root.KeloGuardianAuthority)return state();const now=Date.now();if(!force&&now-lastHeartbeatAt<HEARTBEAT_MS)return state();inFlight=true;try{const result=serverState?.node?await root.KeloGuardianAuthority.heartbeat(await payload()):await root.KeloGuardianAuthority.enable(await payload());lastHeartbeatAt=now;wasOnline=true;return apply(result);}catch(error){lastError=String(error&&error.message||error);wasOnline=false;emit();return state();}finally{inFlight=false;}}
function updatePreferences(next){prefs=Object.assign({},prefs,next||{});savePrefs();emit();if(prefs.enabled)heartbeat(true);return state();}
function sendToMaster(message){const master=masterDescriptor();if(!master||state().masterActive)return false;return sendPeer(peers.get(master.nodeId),message);}
function broadcast(message){if(!state().masterActive)return 0;let sent=0;for(const peer of peers.values())if(sendPeer(peer,message))sent++;return sent;}
function tick(){if(!prefs.enabled)return;const online=navigator.onLine!==false;if(online&&!wasOnline){wasOnline=true;heartbeat(true);}else if(!online){wasOnline=false;return;}else heartbeat(false);transportTick();}
function boot(){emit();if(root.KeloSimulation&&typeof root.KeloSimulation.after==='function')root.KeloSimulation.after('guardian:runtime',tick,360);if(prefs.enabled)setTimeout(()=>heartbeat(true),0);else setTimeout(()=>refresh().catch(()=>{}),0);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&prefs.enabled)heartbeat(true);else emit();},{passive:true});root.addEventListener('online',()=>heartbeat(true),{passive:true});root.addEventListener('offline',()=>{wasOnline=false;closeAllPeers('offline');emit();},{passive:true});root.addEventListener('beforeunload',()=>{for(const peer of peers.values())sendSignal(peer.nodeId,'bye',{epoch:masterDescriptor()?.epoch||0});closeAllPeers('unload');},{once:true});}
root.KeloGuardian=Object.freeze({version:VERSION,state,activate,deactivate,toggle:()=>prefs.enabled?deactivate():activate(),refresh,heartbeat:()=>heartbeat(true),startMasterHost,stopMasterHost,updatePreferences,capabilities:capabilitySnapshot,transport:transportSnapshot,sendToMaster,broadcast});
root.KELO_GUARDIAN_AUDIT=Object.freeze({version:VERSION,owner:'KeloGuardian',authority:'KeloGuardianAuthority',secondLoop:false,simulationHook:true,iosBackgroundClaim:false,serverLease:true,supabaseControlPlane:true,webrtcDataPlane:true,dtlsEncrypted:true,clientGameplayAuthority:false,clientRewardAuthority:false});
boot();
})(typeof globalThis!=='undefined'?globalThis:window);
