(function(){
'use strict';
const VERSION='illumination-v1.1';
const MIN_GIVER_LEVEL=90, LEVEL_GAP=20, MAX_RECEIVED_PER_DAY=5, CLAIM_MS=20*60*1000;
function today(){return new Date().toISOString().slice(0,10)}
function xpNeed(lvl){return 1000+Math.max(1,lvl)*250}
function ensure(){
 if(typeof STATE==='undefined')return null;
 if(!STATE.progression)STATE.progression={level:100,xp:0};
 if(!STATE.illumination)STATE.illumination={day:'',points:0,receivedToday:0,merit:0,bankXp:0,lastClaimAt:Date.now(),history:[]};
 const s=STATE.illumination;
 if(s.day!==today()){s.day=today();s.receivedToday=0;s.points=dailyPoints();s.lastClaimAt=Date.now();}
 STATE.progression.level=Math.max(1,Math.floor(Number(STATE.progression.level)||100));
 STATE.progression.xp=Math.max(0,Math.floor(Number(STATE.progression.xp)||0));
 localPlayer.level=STATE.progression.level;
 return s;
}
function dailyPoints(){
 let p=(STATE?.progression?.level||100)>=MIN_GIVER_LEVEL?1:0;
 const r=window.KeloNobility?.getRank?.()?.id||'none';
 if(r==='knight'||r==='baron')p+=1;
 else if(r==='earl'||r==='duke')p+=2;
 else if(r==='prince')p+=3;
 else if(r==='king')p+=4;
 return p;
}
function grantXp(amount){ensure();let left=Math.max(0,Math.floor(Number(amount)||0));while(left>0){const need=xpNeed(STATE.progression.level)-STATE.progression.xp;const add=Math.min(left,need);STATE.progression.xp+=add;left-=add;if(STATE.progression.xp>=xpNeed(STATE.progression.level)){STATE.progression.xp=0;STATE.progression.level++;localPlayer.level=STATE.progression.level;if(typeof showToast==='function')showToast('Subiste a nivel '+STATE.progression.level);}}if(typeof saveState==='function')saveState();}
function claimTick(force){const s=ensure();if(!s||s.bankXp<=0)return 0;const now=Date.now();if(!force&&now-s.lastClaimAt<CLAIM_MS)return 0;const amount=Math.max(1,Math.floor(s.bankXp*0.2));s.bankXp=Math.max(0,s.bankXp-amount);s.lastClaimAt=now;grantXp(amount);return amount;}
function levelOf(p){if(!p)return 1;if(Number.isFinite(p.level))return Math.floor(p.level);if(p.id==='p1')return 72;if(p.id==='p2')return 125;return 80;}
function eligibility(target){const s=ensure();const me=STATE.progression.level,t=levelOf(target);if(me<MIN_GIVER_LEVEL)return{ok:false,reason:'Necesitas nivel 90 para iluminar.'};if(me<t+LEVEL_GAP)return{ok:false,reason:'Debes tener al menos 20 niveles más.'};if((s.points||0)<1)return{ok:false,reason:'No tienes Puntos de Iluminación hoy.'};return{ok:true,reason:'Elegible'};}
function enlighten(target){const e=eligibility(target);if(!e.ok)return{ok:false,error:e.reason};const s=ensure();s.points-=1;s.merit+=1;s.history.unshift({at:Date.now(),target:target.name||'Jugador',targetLevel:levelOf(target)});s.history=s.history.slice(0,20);target.enlightened=true;target.enlightenedBy=(localPlayer.name||'Kelo').replace(' (Tu)','');target.enlightenedAt=Date.now();target.enlightenedXp=Math.floor(xpNeed(levelOf(target))*0.25);if(typeof saveState==='function')saveState();if(typeof showToast==='function')showToast('Iluminaste a '+target.name+' · +1 Mérito');renderCard(target);return{ok:true,targetXp:target.enlightenedXp};}
function receive(from){const s=ensure();const fromLevel=levelOf(from),me=STATE.progression.level;if(fromLevel<MIN_GIVER_LEVEL||fromLevel<me+LEVEL_GAP)return{ok:false,error:'El iluminador debe ser nivel 90+ y tener 20 niveles más.'};if(s.receivedToday>=MAX_RECEIVED_PER_DAY)return{ok:false,error:'Ya recibiste 5 iluminaciones hoy.'};const bonus=Math.floor(xpNeed(me)*0.25);s.receivedToday++;s.bankXp+=bonus;s.lastClaimAt=Date.now();s.history.unshift({at:Date.now(),from:from.name||'Jugador',received:bonus});s.history=s.history.slice(0,20);if(typeof saveState==='function')saveState();return{ok:true,bonus,bankXp:s.bankXp};}
function installStyle(){if(document.getElementById('kelo-illumination-style'))return;const st=document.createElement('style');st.id='kelo-illumination-style';st.textContent=`#kelo-player-card{position:fixed;left:50%;top:50%;transform:translate(-50%,-50%);width:min(330px,calc(100vw - 24px));max-height:82vh;overflow-y:auto;z-index:190;background:linear-gradient(180deg,#18232d,#0b1117);border:2px solid #b78a36;border-radius:18px;padding:0;color:#edf1f5;box-shadow:0 18px 60px rgba(0,0,0,.6);pointer-events:auto}.ipc-head{display:flex;justify-content:space-between;align-items:center;padding:12px;border-bottom:1px solid rgba(231,197,106,.2)}.ipc-head b{font:700 20px Georgia,serif;color:#f2ce70}.ipc-close{width:38px;height:38px;border-radius:10px;border:1px solid #6c5428;background:#251b10;color:#f2ce70;font-size:24px}.ipc-body{padding:14px}.ipc-avatar{width:74px;height:74px;margin:auto;border-radius:16px;border:1px solid #7a6334;background:radial-gradient(circle,#315a67,#15232c);display:grid;place-items:center;font-size:34px}.ipc-name{text-align:center;font-size:18px;font-weight:800;margin-top:8px}.ipc-meta{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:12px 0}.ipc-stat{padding:9px;border:1px solid #33414c;border-radius:10px;background:rgba(255,255,255,.03)}.ipc-stat span{display:block;color:#8fa0ae;font-size:9px}.ipc-stat b{color:#e9cb73;font-size:13px}.ipc-armor{border:1px solid rgba(231,197,106,.24);border-radius:12px;padding:10px;margin:0 0 12px;background:rgba(231,197,106,.055)}.ipc-armor-title{display:flex;justify-content:space-between;color:#f2ce70;font-weight:900}.ipc-armor-sub{font-size:10px;color:#aeb8c2;margin-top:5px;display:grid;grid-template-columns:1fr 1fr;gap:4px}.ipc-enlighten{width:100%;min-height:48px;border-radius:11px;border:1px solid #c89c43;background:linear-gradient(#654c1f,#34250f);color:#ffe18e;font-weight:900;font-size:14px}.ipc-enlighten:disabled{opacity:.42}.ipc-note{font-size:10px;line-height:1.4;color:#9eabb5;margin-top:9px}.ipc-badge{display:inline-block;padding:4px 7px;border-radius:999px;background:rgba(231,197,106,.1);color:#e7c56a;font-size:9px}`;document.head.appendChild(st)}
function root(){let r=document.getElementById('kelo-player-card');if(!r){r=document.createElement('div');r.id='kelo-player-card';r.className='app-panel';r.style.display='none';document.body.appendChild(r)}return r}
function armorMeta(player){const isMe=player===localPlayer;let score=Number(player.armorScore)||0,rank=Number(player.auraRank)||0,aq=Number(player.averageQuality)||0,ag=Number(player.averageGrade)||0;if(window.KeloEquipment&&isMe){score=window.KeloEquipment.getArmorScore();rank=window.KeloEquipment.getAuraRank(score);aq=window.KeloEquipment.getAverageQuality();ag=window.KeloEquipment.getAverageGrade();}const next=window.KeloEquipment&&window.KeloEquipment.nextAura?window.KeloEquipment.nextAura(score):null;const qName=window.KeloEquipment&&aq?window.KeloEquipment.qualityName(Math.round(aq)):'Normal';return{score,rank,aq,ag,qName,next};}
function renderCard(player){installStyle();ensure();activeSocialTarget=player;const r=root(),e=eligibility(player),lvl=levelOf(player),rank=player.nobilityTitle||player.nobilityRank||'Sin título',armor=armorMeta(player);const targetText=armor.next?(armor.score.toLocaleString()+' / '+armor.next.threshold.toLocaleString()):armor.score.toLocaleString()+' / MAX';r.innerHTML=`<div class="ipc-head"><span class="ipc-badge">Ficha de jugador</span><button class="ipc-close" type="button">×</button></div><div class="ipc-body"><div class="ipc-avatar">♙</div><div class="ipc-name">${String(player.name||'Jugador').replace(/[<>&]/g,'')}</div><div class="ipc-meta"><div class="ipc-stat"><span>Nivel</span><b>${lvl}</b></div><div class="ipc-stat"><span>Nobleza</span><b>${String(rank)}</b></div><div class="ipc-stat"><span>HP</span><b>${Math.max(0,Math.floor(player.hp||100))}/${Math.max(1,Math.floor(player.maxHp||100))}</b></div><div class="ipc-stat"><span>Tus puntos hoy</span><b>${ensure().points}</b></div></div><div class="ipc-armor"><div class="ipc-armor-title"><span>AURA ${armor.rank}</span><span>${targetText}</span></div><div class="ipc-armor-sub"><span>Quality: <b>${armor.qName} ${armor.aq?armor.aq.toFixed(1):'1.0'}</b></span><span>Grade: <b>${armor.ag?armor.ag.toFixed(1):'1.0'}</b></span></div></div><button class="ipc-enlighten" type="button" ${e.ok?'':'disabled'}>Iluminar</button><div class="ipc-note">${e.ok?'Puedes iluminarlo: tienes 20+ niveles de ventaja.':e.reason}<br>El receptor puede recibir hasta 5 iluminaciones al día y acumula EXP iluminada.</div></div>`;r.style.display='block';r.querySelector('.ipc-close').addEventListener('click',close);r.querySelector('.ipc-enlighten').addEventListener('click',()=>enlighten(player));}
function close(){const r=root();r.style.display='none';activeSocialTarget=null;const old=document.getElementById('social-modal');if(old)old.style.display='none'}
const oldOpen=typeof openSocialModal==='function'?openSocialModal:null;openSocialModal=function(player){renderCard(player)};const oldClose=typeof closeSocialModal==='function'?closeSocialModal:null;closeSocialModal=function(){close();if(oldClose)try{oldClose()}catch(e){}};
ensure();if(typeof simulatedPlayers!=='undefined'){simulatedPlayers.forEach(p=>{if(!Number.isFinite(p.level))p.level=levelOf(p)})}
setInterval(()=>claimTick(false),30000);
window.KeloIllumination=Object.freeze({version:VERSION,open:renderCard,close,enlighten,receive,eligibility,claimNow:()=>claimTick(true),getState:()=>({...ensure()}),getLevel:()=>STATE.progression.level,grantXp});
window.KELO_ILLUMINATION_AUDIT={version:VERSION,ready:true,minGiverLevel:MIN_GIVER_LEVEL,levelGap:LEVEL_GAP,maxReceivedPerDay:MAX_RECEIVED_PER_DAY,claimMinutes:20,nobilityDailyBonus:true,armorCard:true};
})();