/* KELO-INDEX
 * area: PVP / WORLD
 * owner: KeloPvPWorld; input→KeloInput, resolution→Combat/Melee/Abilities, movement→KeloMovement, online→KeloNetAuthority
 * keys: PVP AIM BUFFER CHARGES COMBO SPECIAL DODGE ASSIST TELEGRAPH MOBILE GAMEPAD PREDICTION RECONCILIATION ARENA
 * purpose: contexto/orquestación action-combat; nunca reemplaza engines Foundation
 * public-api: enter/leave/startBasicAttack/quickCastSlot/setAimWorld/reconcileAuthority/state
 * online: predice presentation/timeline local; servidor reconcilia resource/HP/cooldowns y decide daño/CC/death; Arena local declara explícitamente su fallback
 * do-not: NO target lock, NO HP remoto local, NO segundo input/combat/render/simulation owner
 */
(function(){
'use strict';
const VERSION='pvp-world-v3.2.0-arena-actors',TRANSITION_MS=650;
const WORLD=Object.freeze({x:2660,y:360,w:720,h:720,spawnX:2790,spawnY:720,dummyX:3190,dummyY:720});
const TUNING=Object.freeze({mobileCombatSplit:.55,inputBufferMs:125,comboGraceMs:20,aimIndicator:Object.freeze({min:52,max:88,start:32,idleAlpha:.10,activeAlpha:.62,fadeMs:900}),aimAssist:Object.freeze({touch:Object.freeze({maxAngleDeg:12,maxDistance:360,strength:.18,hysteresis:1.55}),controller:Object.freeze({maxAngleDeg:15,maxDistance:390,strength:.23,hysteresis:1.55}),mouse:Object.freeze({maxAngleDeg:5,maxDistance:320,strength:0,hysteresis:1.4})}),dodge:Object.freeze({distance:112,duration:.16,iFrames:.105,recovery:0,cooldown:.85,directionSource:'move'})});
const cameraOwner=window.KeloCamera,inputOwner=window.KeloInput;
if(!cameraOwner||!inputOwner||!inputOwner.combat)throw new Error('PvP Foundation input/camera unavailable');
inputOwner.combat.configure({bufferMs:TUNING.inputBufferMs,aimDeadzone:.18,moveDeadzone:.14});
const state={mode:'social',combatEnabled:false,transitioning:false,pendingEnter:false,armedSlot:-1,aim:{x:1,y:0,rawX:1,rawY:0,worldX:WORLD.spawnX+80,worldY:WORLD.spawnY,source:'default',magnitude:1},assistTargetId:null,lastAimActivity:0,basicRootId:'sword_light_basic',basicResource:null,specialResource:null,basicAttack:null,comboStep:0,comboExpiresAt:0,specialHold:null,dodge:null,dodgeCooldown:0,saved:null,floats:[],impacts:[],misses:[],hitStopVisual:0,dummy:null,transitionTimer:null,transitionStartedAt:0,transitionKind:null,lastError:null,combatPointerId:null,abilityPointerId:null,abilityPointerSlot:-1,lastPointerType:null,gamepadButtons:[],commandSeq:1,lastAuthorityTick:0};
window.KELO_COMBAT_ENABLED=false;
const now=()=>performance&&performance.now?performance.now():Date.now(),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function toast(m){if(typeof showToast==='function')showToast(m);}function dist(a,b){return Math.hypot((Number(a&&a.x)||0)-(Number(b&&b.x)||0),(Number(a&&a.y)||0)-(Number(b&&b.y)||0));}
function norm(x,y,f){x=Number(x)||0;y=Number(y)||0;if(Math.hypot(x,y)<1e-7&&f){x=Number(f.x)||1;y=Number(f.y)||0;}const l=Math.hypot(x,y)||1;return{x:x/l,y:y/l};}
function angleDeg(a,b){const x=norm(a.x,a.y),y=norm(b.x,b.y);return Math.acos(clamp(x.x*y.x+x.y*y.y,-1,1))*180/Math.PI;}function blend(a,b,t){return norm(a.x*(1-t)+b.x*t,a.y*(1-t)+b.y*t,a);}function face(d){return Math.abs(d.x)>Math.abs(d.y)?(d.x<0?'left':'right'):(d.y<0?'up':'down');}
function ready(){return typeof localPlayer!=='undefined'&&!!localPlayer;}function combatReady(){return !!(window.KeloMeleeEngine&&window.KeloCombatEngine&&window.KeloHitResolver&&window.KeloCombatSchema&&window.KeloEvents&&window.KeloAbilities);}function localArenaAuthority(){try{if(!window.KeloArena)return false;const s=window.KeloArena.snapshot&&window.KeloArena.snapshot();return !!(s&&s.status!=='idle'&&(!s.match||s.match.source==='local-fallback'));}catch(_){return false;}}function online(){if(localArenaAuthority())return false;return !!(window.KeloNetAuthority&&window.KeloNetAuthority.isOnline&&window.KeloNetAuthority.isOnline()&&window.KeloNetAuthority.sendCombatIntent);}
function dummy(){if(state.dummy)return state.dummy;if(typeof simulatedPlayers==='undefined'||!simulatedPlayers||!simulatedPlayers.length)return null;return state.dummy=simulatedPlayers[0];}function screenWorld(x,y){return cameraOwner.screenToWorld(x,y);}function hotbar(slot){return window.KeloAbilities&&window.KeloAbilities.hotbar&&window.KeloAbilities.hotbar.slots[slot]||null;}
function emit(name,p){try{if(name&&window.KeloEvents)window.KeloEvents.emit(name,p);}catch(_){}}function send(action,extra){if(!online())return null;try{return window.KeloNetAuthority.sendCombatIntent(Object.assign({action,moveX:typeof input!=='undefined'?Number(input.normX)||0:0,moveY:typeof input!=='undefined'?Number(input.normY)||0:0,aimX:state.aim.x,aimY:state.aim.y,clientTime:Date.now()},extra||{}));}catch(e){state.lastError=String(e);return null;}}
function arenaActive(){return !!(window.KeloArena&&window.KeloArena.isActive&&window.KeloArena.isActive());}function actors(){if(arenaActive()&&window.KeloArena.getHostileActors)return window.KeloArena.getHostileActors(localPlayer);if(online()&&window.keloNet&&window.keloNet.peers)return Object.values(window.keloNet.peers).filter(p=>p&&p.zone==='pvp'&&(p.hp==null||p.hp>0));const d=dummy();return d&&d.hp>0?[d]:[];}function actorById(id){if(arenaActive()&&window.KeloArena.getActorById){const a=window.KeloArena.getActorById(id);if(a)return a;}const d=dummy();if(d&&String(d.id)===String(id))return d;return window.keloNet&&window.keloNet.peers&&window.keloNet.peers[id]||null;}
function assistConfig(source){return source==='touch'?TUNING.aimAssist.touch:(source==='gamepad'||source==='controller')?TUNING.aimAssist.controller:TUNING.aimAssist.mouse;}
function assisted(raw,source){const cfg=assistConfig(source);if(!cfg.strength||!ready())return{dir:raw,target:null};function info(a){if(!a||a.hp<=0)return null;const d=dist(localPlayer,a);if(d>cfg.maxDistance)return null;const dir=norm(a.x-localPlayer.x,a.y-localPlayer.y),ang=angleDeg(raw,dir);return{a,d,dir,ang,score:(ang/cfg.maxAngleDeg)*.72+(d/cfg.maxDistance)*.28};}const current=info(actorById(state.assistTargetId));if(current&&current.ang<=cfg.maxAngleDeg*cfg.hysteresis)return{dir:blend(raw,current.dir,cfg.strength),target:current.a};const best=actors().map(info).filter(Boolean).filter(x=>x.ang<=cfg.maxAngleDeg).sort((a,b)=>a.score-b.score)[0];return best?{dir:blend(raw,best.dir,cfg.strength),target:best.a}:{dir:raw,target:null};}
function setAimVector(raw,world,source,magnitude){if(!ready())return state.aim;raw=norm(raw.x,raw.y,state.aim);const a=assisted(raw,source),d=a.dir;state.assistTargetId=a.target?String(a.target.id||''):null;state.aim={x:d.x,y:d.y,rawX:raw.x,rawY:raw.y,worldX:world&&Number.isFinite(Number(world.x))?Number(world.x):localPlayer.x+d.x*80,worldY:world&&Number.isFinite(Number(world.y))?Number(world.y):localPlayer.y+d.y*80,source:String(source||'world'),magnitude:Number.isFinite(Number(magnitude))?clamp(Number(magnitude),0,1):1};state.lastAimActivity=now();localPlayer._face=face(d);inputOwner.combat.setAxes({source:source||'world',rawAim:{x:raw.x,y:raw.y,magnitude:state.aim.magnitude,source},aim:{x:d.x,y:d.y,magnitude:state.aim.magnitude,source}});return state.aim;}
function setAimWorld(w,source,magnitude){return ready()&&w?setAimVector(norm(w.x-localPlayer.x,w.y-localPlayer.y,state.aim),w,source||'world',magnitude):state.aim;}function setAimScreen(x,y,source){return setAimWorld(screenWorld(x,y),source||'pointer',1);}
function syncGamepad(){const pad=inputOwner.pollGamepad&&inputOwner.pollGamepad();if(!pad)return;if(pad.aim&&pad.aim.magnitude>0)setAimVector(pad.aim,null,'gamepad',pad.aim.magnitude);const b=Array.from(pad.buttons||[]).map(x=>!!(x&&x.pressed));const edge=(i,t)=>{if(b[i]&&!state.gamepadButtons[i])inputOwner.combat.push(t,{source:'gamepad'});};edge(0,'BASIC_PRESS');edge(1,'DODGE_PRESS');edge(2,'SPECIAL_PRESS');if(!b[2]&&state.gamepadButtons[2])inputOwner.combat.push('SPECIAL_RELEASE',{source:'gamepad'});state.gamepadButtons=b;}
function rootProfile(){return window.KeloMeleeEngine&&window.KeloMeleeEngine.getProfile(state.basicRootId);}function syncResources(reset){const p=rootProfile();if(!p)return;if(reset||!state.basicResource)state.basicResource=window.KeloMeleeEngine.createResource(p);else window.KeloMeleeEngine.syncResource(state.basicResource,p);const sp=p.specialAttackProfileId&&window.KeloMeleeEngine.getProfile(p.specialAttackProfileId);if(sp){if(reset||!state.specialResource)state.specialResource=window.KeloMeleeEngine.createResource(sp);else window.KeloMeleeEngine.syncResource(state.specialResource,sp);}}
function copyResource(dst,src){if(!dst||!src)return;dst.current=clamp(Math.floor(Number(src.current)||0),0,Math.max(1,Number(src.max)||dst.max||1));dst.max=Math.max(1,Math.floor(Number(src.max)||dst.max||1));dst.rechargeElapsed=Math.max(0,Number(src.rechargeElapsed)||0);}
function reconcileAuthority(actor){if(!actor||!ready())return false;state.lastAuthorityTick=Math.max(state.lastAuthorityTick,Number(actor.serverTick)||0);if(Number.isFinite(Number(actor.hp)))localPlayer.hp=Number(actor.hp);if(Number.isFinite(Number(actor.mana)))localPlayer.mana=Number(actor.mana);syncResources(false);copyResource(state.basicResource,actor.basicResource);copyResource(state.specialResource,actor.specialResource);if(Number.isFinite(Number(actor.comboStep)))state.comboStep=Math.max(0,Math.floor(Number(actor.comboStep)));if(Number.isFinite(Number(actor.dodgeCooldown)))state.dodgeCooldown=Math.max(0,Number(actor.dodgeCooldown));if(actor.cooldowns&&window.KeloAbilities){window.KeloAbilities.hotbar.slots.forEach(slot=>{if(slot&&slot.definition&&Number.isFinite(Number(actor.cooldowns[slot.definition.key])))slot.cooldown=Math.max(0,Number(actor.cooldowns[slot.definition.key]));});}return true;}
function canAttack(){return state.combatEnabled&&!state.transitioning&&!state.basicAttack&&!state.dodge&&!(window.KeloStatusEffects&&window.KeloStatusEffects.isActionBlocked(localPlayer,'attack'));}
function scaledSpecial(profile,charge){const q=charge&&charge.charge01||0;return Object.freeze(Object.assign({},profile,{damage:profile.damage*(1+.55*q),range:profile.range*(1+.14*q),knockback:profile.knockback*(1+.55*q)}));}
function startAttack(profile,kind,source,charge,networkIntent){if(!profile||!canAttack())return false;const resource=kind==='special'?state.specialResource:state.basicResource,spent=window.KeloMeleeEngine.consumeResource(resource,kind==='special'?profile:rootProfile(),1);if(!spent.ok)return false;const id=(kind==='special'?'special_':'basic_')+(state.commandSeq++).toString(36),runtime=kind==='special'?scaledSpecial(profile,charge):profile,begun=window.KeloMeleeEngine.beginAttack({attacker:localPlayer,direction:{x:state.aim.x,y:state.aim.y},profileId:profile.id,attackId:id,startedAt:now(),source:'pvp-'+kind,visual:{charge01:charge&&charge.charge01||0}});if(!begun.ok){resource.current=Math.min(resource.max,resource.current+1);return false;}state.basicAttack={id,kind,phase:'windup',phaseTime:0,direction:{x:state.aim.x,y:state.aim.y},profile:runtime,profileId:profile.id,resolved:false,startedAt:now(),charge:charge||null};localPlayer._face=face(state.basicAttack.direction);emit(window.KeloCombatSchema.events.ATTACK_REQUESTED,Object.assign({},begun.payload,{kind}));if(kind==='basic'){state.comboStep=window.KeloMeleeEngine.nextComboStep(rootProfile(),state.comboStep);if(networkIntent!==false)send('basic_attack',{phase:'pressed',attackId:id,profileId:profile.id});}return true;}
function tryBasic(){if(!canAttack())return false;const root=rootProfile();if(!root)return false;if(state.comboExpiresAt&&now()>state.comboExpiresAt+TUNING.comboGraceMs)state.comboStep=0;return startAttack(window.KeloMeleeEngine.comboProfile(root,state.comboStep),'basic','buffer',null,true);}
function knockback(target,d,amount){if(!target||!amount)return;const from={x:target.x,y:target.y},to={x:target.x+d.x*amount,y:target.y+d.y*amount};let t=1;if(window.KELO_COLLISION&&typeof obstacles!=='undefined')for(const box of obstacles){if(!box||box.blocksMovement===false)continue;const q=window.KELO_COLLISION.segmentAabbHitT(from.x,from.y,to.x,to.y,box,target.radius||20);if(q!=null)t=Math.min(t,Math.max(0,q-1e-4));}target.x=clamp(from.x+(to.x-from.x)*t,WORLD.x+(target.radius||20),WORLD.x+WORLD.w-(target.radius||20));target.y=clamp(from.y+(to.y-from.y)*t,WORLD.y+(target.radius||20),WORLD.y+WORLD.h-(target.radius||20));}
function resolveActive(){const a=state.basicAttack;if(!a||a.resolved)return;a.resolved=true;emit(window.KeloCombatSchema.events.ATTACK_ACTIVE,{attackId:a.id,actor:localPlayer,actorId:String(localPlayer.id||'local'),direction:a.direction,profileId:a.profileId,kind:a.kind,charge:a.charge});if(online()){const predicted=actors().filter(t=>window.KeloHitResolver.resolveMelee(localPlayer,t,a.direction,a.profile).hit);predicted.forEach(t=>state.impacts.push({x:t.x,y:t.y-14,life:.11,max:.11,predicted:true}));if(!predicted.length)state.misses.push({x:localPlayer.x+a.direction.x*a.profile.range*.78,y:localPlayer.y+a.direction.y*a.profile.range*.78,life:.15,max:.15});return;}const result=window.KeloCombatEngine.attackSweep({attacker:localPlayer,targets:actors(),direction:a.direction,profile:a.profile,profileId:a.profileId,kind:a.kind,attackId:a.id,startedAt:a.startedAt,source:'pvp-offline',skipStart:true}),hits=result&&result.hits||[];hits.forEach(h=>{const t=h.target;state.floats.push({x:t.x,y:t.y-42,text:h.blocked?'BLOCK':'-'+Math.round(h.amount),life:.7});state.impacts.push({x:t.x,y:t.y-16,life:.15,max:.15});if(window.KeloStatusEffects&&a.profile.stagger>0)window.KeloStatusEffects.apply(t,{type:'stagger',duration:a.profile.stagger,magnitude:1,refreshPolicy:'refresh',visualProfileId:'cc_stagger_default'},{source:localPlayer,target:t});knockback(t,a.direction,a.profile.knockback);});if(hits.length)state.hitStopVisual=.026;else state.misses.push({x:localPlayer.x+a.direction.x*a.profile.range*.78,y:localPlayer.y+a.direction.y*a.profile.range*.78,life:.15,max:.15});}
function updateAttack(dt){const a=state.basicAttack;if(!a||state.hitStopVisual>0)return;a.phaseTime+=dt;if(a.phase==='windup'&&a.phaseTime>=a.profile.windup){a.phase='active';a.phaseTime=0;resolveActive();}else if(a.phase==='active'&&a.phaseTime>=a.profile.active){a.phase='recovery';a.phaseTime=0;}else if(a.phase==='recovery'&&a.phaseTime>=a.profile.recovery){if(a.kind==='basic')state.comboExpiresAt=now()+Math.max(0,Number(rootProfile()&&rootProfile().comboTimeout)||0)*1000;else{state.comboStep=0;state.comboExpiresAt=0;}state.basicAttack=null;}}
function processBasic(t){if(!canAttack())return;const q=inputOwner.combat.peek('BASIC_PRESS',t);if(!q||!state.basicResource||state.basicResource.current<=0)return;inputOwner.combat.consume('BASIC_PRESS',t);tryBasic();}
function beginSpecial(t){const root=rootProfile(),p=root&&root.specialAttackProfileId&&window.KeloMeleeEngine.getProfile(root.specialAttackProfileId);if(!p)return;state.specialHold={profile:p,pressedAt:t};send('special_attack',{phase:'pressed',profileId:p.id});}
function releaseSpecial(t){const s=state.specialHold;if(!s)return;const charge=window.KeloMeleeEngine.chargeValue(s.profile,Math.max(0,(t-s.pressedAt)/1000));state.specialHold=null;send('special_attack',{phase:'released',profileId:s.profile.id});if(!charge.ready)return;if(state.basicAttack){const allow=state.basicAttack.profile.canCancelInto&&state.basicAttack.profile.canCancelInto.includes('special'),remaining=state.basicAttack.profile.recovery-state.basicAttack.phaseTime;if(!(allow&&state.basicAttack.phase==='recovery'&&remaining<=state.basicAttack.profile.cancelWindow))return;state.basicAttack=null;}startAttack(s.profile,'special','release',charge,false);}
function startDodge(){if(!state.combatEnabled||state.dodge||state.dodgeCooldown>0||!ready()||window.KeloStatusEffects&&window.KeloStatusEffects.isActionBlocked(localPlayer,'move'))return false;if(state.basicAttack){const allow=state.basicAttack.profile.canCancelInto&&state.basicAttack.profile.canCancelInto.includes('dodge');if(!allow)return false;state.basicAttack=null;state.comboStep=0;state.comboExpiresAt=0;}const m=inputOwner.combat.snapshot().move,d=norm(TUNING.dodge.directionSource==='move'&&m.magnitude>.05?m.x:state.aim.x,TUNING.dodge.directionSource==='move'&&m.magnitude>.05?m.y:state.aim.y,state.aim),cfg=TUNING.dodge;state.dodge={direction:d,time:0,duration:cfg.duration};state.dodgeCooldown=cfg.cooldown;if(window.KeloStatusEffects)window.KeloStatusEffects.apply(localPlayer,{type:'invulnerable',duration:cfg.iFrames,magnitude:1,refreshPolicy:'refresh',visualProfileId:'cc_invulnerable_dodge'},{source:localPlayer,target:localPlayer});localPlayer._dash={sx:localPlayer.x,sy:localPlayer.y,tx:localPlayer.x+d.x*cfg.distance,ty:localPlayer.y+d.y*cfg.distance,time:cfg.duration,max:cfg.duration,abilityKey:'__dodge__'};emit(window.KeloCombatSchema.events.DODGE_STARTED,{actor:localPlayer,actorId:String(localPlayer.id||'local'),direction:d,duration:cfg.duration});send('dodge',{phase:'pressed',direction:d});return true;}
function updateDodge(dt){if(!state.dodge)return;state.dodge.time+=dt;if(state.dodge.time>=state.dodge.duration+TUNING.dodge.recovery){emit(window.KeloCombatSchema.events.DODGE_ENDED,{actor:localPlayer,actorId:String(localPlayer.id||'local')});state.dodge=null;}}
function armAbility(slot){if(!state.combatEnabled||state.transitioning||!window.KeloAbilities)return false;const i=hotbar(slot);if(!i){toast('Slot vacío');return false;}state.armedSlot=slot;return true;}
function castArmed(){const slot=state.armedSlot;if(slot<0||!window.KeloAbilities)return false;const i=hotbar(slot);if(!i||!i.definition){state.armedSlot=-1;return false;}const d=i.definition,t=d.targeting||{},delivery=d.delivery||{},range=t.range||delivery.maxDistance||delivery.distance||300,q={slotIndex:slot,direction:{x:state.aim.x,y:state.aim.y}};if(t.type==='position')q.position={x:localPlayer.x+state.aim.x*range,y:localPlayer.y+state.aim.y*range};else if(t.type==='target'){const target=actors().filter(a=>dist(localPlayer,a)<=range).sort((a,b)=>angleDeg(state.aim,norm(a.x-localPlayer.x,a.y-localPlayer.y))-angleDeg(state.aim,norm(b.x-localPlayer.x,b.y-localPlayer.y)))[0];if(!target){toast('Apunta a un enemigo');return false;}q.targetId=target.id;q.target=target;}if(d.key==='swap_sword'&&window.KeloSwordSwapRuntime&&typeof window.KeloSwordSwapRuntime.castIntent==='function'){const r=window.KeloSwordSwapRuntime.castIntent(q);state.armedSlot=-1;return !!(r&&r.valid!==false);}const result=online()&&window.KeloAbilities.engine.predict?window.KeloAbilities.engine.predict(q):window.KeloAbilities.engine.cast(q);state.armedSlot=-1;if(result&&result.valid){send('ability',{abilityKey:d.key,slot,phase:'cast',direction:q.direction,position:q.position||null,targetId:q.targetId||null});return true;}toast('No se pudo usar la habilidad');return false;}
function processIntents(t){let q;while((q=inputOwner.combat.consume('DODGE_PRESS',t)))startDodge();while((q=inputOwner.combat.consume('SPECIAL_PRESS',t)))beginSpecial(q.at);while((q=inputOwner.combat.consume('SPECIAL_RELEASE',t)))releaseSpecial(q.at);while((q=inputOwner.combat.consume('ABILITY_PRESS',t)))if(Number.isInteger(Number(q.payload.slot)))armAbility(Number(q.payload.slot));while((q=inputOwner.combat.consume('ABILITY_RELEASE',t)))if(state.armedSlot>=0)castArmed();while(inputOwner.combat.consume('CANCEL_CAST',t))state.armedSlot=-1;processBasic(t);}
function movementHook(c){if(!state.combatEnabled||!c||!c.input)return;let s=state.dodge?0:state.basicAttack?window.KeloMeleeEngine.movementScaleFor(state.basicAttack.profile,state.basicAttack.phase):1;if(window.KeloStatusEffects)s*=window.KeloStatusEffects.movementMultiplier(localPlayer);c.input.normX=(Number(c.input.normX)||0)*s;c.input.normY=(Number(c.input.normY)||0)*s;}function facingHook(){if(state.combatEnabled&&ready())localPlayer._face=face(state.basicAttack?state.basicAttack.direction:state.aim);}
function freezeMovement(){if(ready()){localPlayer.vx=0;localPlayer.vy=0;}if(typeof input!=='undefined'){input.normX=0;input.normY=0;}}function progress(){return state.transitioning?clamp((now()-state.transitionStartedAt)/TRANSITION_MS,0,1):0;}function transition(kind){state.transitioning=true;state.transitionKind=kind;state.transitionStartedAt=now();freezeMovement();}function finishTransition(){state.transitioning=false;state.transitionKind=null;state.transitionStartedAt=0;}function resetTransient(){state.armedSlot=-1;state.basicAttack=null;state.comboStep=0;state.comboExpiresAt=0;state.specialHold=null;state.dodge=null;state.dodgeCooldown=0;state.assistTargetId=null;inputOwner.combat.clear();syncResources(true);if(window.KeloStatusEffects&&ready())window.KeloStatusEffects.clear(localPlayer,'pvp-reset');}
function setExit(v){const x=document.getElementById('lx-side-pvp-exit');if(x)x.style.display=v?'flex':'none';const y=document.getElementById('kelo-pvp-exit');if(y)y.style.display=v&&!x?'block':'none';}function ensureExit(){if(document.getElementById('lx-side-pvp-exit'))return;let e=document.getElementById('kelo-pvp-exit');if(!e){e=document.createElement('button');e.id='kelo-pvp-exit';e.type='button';e.textContent='Salir PvP';e.style.cssText='display:none;position:absolute;top:max(198px,calc(env(safe-area-inset-top) + 190px));right:max(12px,env(safe-area-inset-right));z-index:140;pointer-events:auto;background:rgba(18,20,27,.95);color:#ffd6d6;border:1px solid rgba(255,90,90,.7);border-radius:12px;padding:9px 12px;font-size:11px;font-weight:850';e.addEventListener('pointerdown',a=>{a.preventDefault();a.stopPropagation();leave();});document.body.appendChild(e);}}
function enter(){if(state.mode!=='social'||state.transitioning)return;if(!ready())return toast('PvP todavía cargando');if(!combatReady()){state.pendingEnter=true;toast('Preparando combate…');return;}state.pendingEnter=false;const d=dummy();state.saved={x:localPlayer.x,y:localPlayer.y,camera:cameraOwner.snapshot(),dummyX:d&&d.x,dummyY:d&&d.y,dummyHp:d&&d.hp,dummyMaxHp:d&&d.maxHp};state.mode='entering';state.combatEnabled=false;resetTransient();window.KELO_COMBAT_ENABLED=false;if(typeof closeMenu==='function')closeMenu();transition('enter');clearTimeout(state.transitionTimer);state.transitionTimer=setTimeout(()=>{if(d&&!online()){d.x=WORLD.dummyX;d.y=WORLD.dummyY;d.hp=d.maxHp=100;}localPlayer.x=WORLD.spawnX;localPlayer.y=WORLD.spawnY;localPlayer.vx=localPlayer.vy=0;setAimWorld({x:WORLD.dummyX,y:WORLD.dummyY},'enter');cameraOwner.setTarget(localPlayer.x,localPlayer.y,{snap:true,source:'pvp-world:enter'});document.body.classList.remove('social-mode');state.mode='pvp';state.combatEnabled=true;window.KELO_COMBAT_ENABLED=true;finishTransition();setExit(true);send('enter_pvp');toast('Mundo PvP · action combat');audit('entered');},TRANSITION_MS);}
function leave(){if(state.mode!=='pvp'||state.transitioning)return;state.mode='leaving';send('leave_pvp');transition('leave');clearTimeout(state.transitionTimer);state.transitionTimer=setTimeout(()=>{state.combatEnabled=false;window.KELO_COMBAT_ENABLED=false;resetTransient();if(state.saved){localPlayer.x=state.saved.x;localPlayer.y=state.saved.y;localPlayer.vx=localPlayer.vy=0;if(state.saved.camera)cameraOwner.restoreState(state.saved.camera,{source:'pvp-world:leave'});const d=dummy();if(d&&state.saved.dummyX!=null){d.x=state.saved.dummyX;d.y=state.saved.dummyY;d.hp=state.saved.dummyHp;d.maxHp=state.saved.dummyMaxHp;}}document.body.classList.add('social-mode');state.mode='social';finishTransition();setExit(false);toast('Volviste al mundo social');audit('left');},TRANSITION_MS);}
function drawArc(origin,d,range,degrees,alpha,width){const a=Math.atan2(d.y,d.x),h=degrees*Math.PI/360;ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle='#f5cd70';ctx.lineWidth=width||2;ctx.beginPath();ctx.arc(origin.x,origin.y,range,a-h,a+h);ctx.stroke();ctx.restore();}
function drawAim(){if(!state.combatEnabled||!ready()||state.armedSlot>=0)return;const age=now()-state.lastAimActivity,base=age<TUNING.aimIndicator.fadeMs?TUNING.aimIndicator.activeAlpha:TUNING.aimIndicator.idleAlpha,len=TUNING.aimIndicator.min+(TUNING.aimIndicator.max-TUNING.aimIndicator.min)*clamp(state.aim.magnitude||1,.35,1),start=TUNING.aimIndicator.start,x1=localPlayer.x+state.aim.x*start,y1=localPlayer.y+state.aim.y*start,x2=localPlayer.x+state.aim.x*len,y2=localPlayer.y+state.aim.y*len;ctx.save();const g=ctx.createLinearGradient(x1,y1,x2,y2);g.addColorStop(0,'rgba(118,214,255,0)');g.addColorStop(.45,'rgba(118,214,255,'+(base*.28)+')');g.addColorStop(1,'rgba(170,236,255,'+base+')');ctx.strokeStyle=g;ctx.lineWidth=1.35;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.translate(x2,y2);ctx.strokeStyle='rgba(178,239,255,'+base+')';ctx.fillStyle='rgba(83,188,230,'+(base*.08)+')';ctx.lineWidth=1.2;ctx.beginPath();ctx.arc(0,0,5,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.globalAlpha=base*.8;ctx.beginPath();ctx.moveTo(-8,0);ctx.lineTo(-5,0);ctx.moveTo(5,0);ctx.lineTo(8,0);ctx.moveTo(0,-8);ctx.lineTo(0,-5);ctx.moveTo(0,5);ctx.lineTo(0,8);ctx.stroke();ctx.restore();}
function drawTelegraph(){if(!state.combatEnabled||!ready())return;const a=state.basicAttack;if(a)drawArc(localPlayer,a.direction,a.profile.range,a.profile.arcDegrees,a.phase==='active'?.58:a.phase==='windup'?.16:.09,a.phase==='active'?3:1.4);if(state.specialHold){const c=window.KeloMeleeEngine.chargeValue(state.specialHold.profile,(now()-state.specialHold.pressedAt)/1000);drawArc(localPlayer,state.aim,state.specialHold.profile.range*(1+.14*c.charge01),state.specialHold.profile.arcDegrees,.15+.44*c.charge01,2.2);}if(state.armedSlot<0)return;const i=hotbar(state.armedSlot);if(!i)return;const d=i.definition,t=d.targeting||{},delivery=d.delivery||{},range=t.range||delivery.maxDistance||delivery.distance||300,p={x:localPlayer.x+state.aim.x*range,y:localPlayer.y+state.aim.y*range};ctx.save();ctx.globalCompositeOperation='lighter';ctx.setLineDash([9,7]);ctx.strokeStyle='rgba(112,220,255,.72)';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(localPlayer.x+state.aim.x*30,localPlayer.y+state.aim.y*30);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='rgba(103,216,255,.06)';if(t.type==='position'){const r=delivery.radius||delivery.activationRadius||24;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();ctx.stroke();}else{ctx.beginPath();ctx.arc(p.x,p.y,delivery.type==='dash'||delivery.type==='blink'?14:5,0,Math.PI*2);ctx.fill();ctx.stroke();}ctx.restore();}
function drawArena(){if(typeof ctx==='undefined'||!ready())return;ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle='#070b12';ctx.fillRect(0,0,canvas.width||screenW,canvas.height||screenH);ctx.restore();const z=typeof CONFIG!=='undefined'&&CONFIG.zoom||1;ctx.save();ctx.translate(screenW/2,screenH/2);ctx.scale(z,z);ctx.translate(-camera.x,-camera.y);ctx.fillStyle='#101722';ctx.fillRect(WORLD.x,WORLD.y,WORLD.w,WORLD.h);ctx.fillStyle='#162231';ctx.fillRect(WORLD.x+24,WORLD.y+24,WORLD.w-48,WORLD.h-48);ctx.strokeStyle='rgba(231,197,106,.72)';ctx.lineWidth=5;ctx.strokeRect(WORLD.x+18,WORLD.y+18,WORLD.w-36,WORLD.h-36);if(window.KeloVisualSystem){window.KeloVisualSystem.renderWorldLayer('groundFX',ctx);window.KeloVisualSystem.renderWorldLayer('belowActor',ctx);}drawTelegraph();drawAim();const ranked=arenaActive();if(ranked&&window.KeloArena.drawWorld)window.KeloArena.drawWorld(ctx);else{const d=dummy();if(!online()&&d&&d.hp>0&&typeof renderAvatar==='function'){renderAvatar(d,false);ctx.fillStyle='rgba(0,0,0,.72)';ctx.fillRect(d.x-34,d.y-58,68,7);ctx.fillStyle='#ef476f';ctx.fillRect(d.x-34,d.y-58,68*clamp(d.hp/d.maxHp,0,1),7);}}if(!ranked&&window.keloNet&&window.keloNet.peers&&typeof renderAvatar==='function')Object.values(window.keloNet.peers).forEach(p=>{if(p&&p.zone==='pvp')renderAvatar(p,false);});if(typeof renderAvatar==='function')renderAvatar(localPlayer,true);if(window.KeloVisualSystem){window.KeloVisualSystem.renderWorldLayer('worldFX',ctx);window.KeloVisualSystem.renderWorldLayer('foregroundFX',ctx);}state.impacts.forEach(f=>{const k=clamp(f.life/f.max,0,1);ctx.globalAlpha=k*(f.predicted?.42:1);ctx.strokeStyle=f.predicted?'#8edbff':'#fff3b0';ctx.lineWidth=2.2;ctx.beginPath();ctx.arc(f.x,f.y,(1-k)*18+5,0,Math.PI*2);ctx.stroke();});state.misses.forEach(f=>{ctx.globalAlpha=clamp(f.life/f.max,0,1)*.55;ctx.strokeStyle='#8795a8';ctx.beginPath();ctx.moveTo(f.x-4,f.y-4);ctx.lineTo(f.x+4,f.y+4);ctx.moveTo(f.x+4,f.y-4);ctx.lineTo(f.x-4,f.y+4);ctx.stroke();});state.floats.forEach(f=>{ctx.globalAlpha=clamp(f.life/.7,0,1);ctx.fillStyle='#fff';ctx.font='bold 15px sans-serif';ctx.textAlign='center';ctx.fillText(f.text,f.x,f.y);});ctx.restore();if(window.KeloVisualSystem)window.KeloVisualSystem.renderScreenLayer('screenFX',ctx);}
function renderIntercept(){if(state.combatEnabled||state.mode==='leaving'){drawArena();return true;}return false;}function updateFx(dt){for(let i=state.floats.length-1;i>=0;i--){state.floats[i].life-=dt;state.floats[i].y-=18*dt;if(state.floats[i].life<=0)state.floats.splice(i,1);}for(const list of [state.impacts,state.misses])for(let i=list.length-1;i>=0;i--){list[i].life-=dt;if(list[i].life<=0)list.splice(i,1);}}
function tick(ctx){const dt=clamp(Number(ctx.dt)||0,0,.05),t=now();if(state.hitStopVisual>0)state.hitStopVisual=Math.max(0,state.hitStopVisual-dt);state.dodgeCooldown=Math.max(0,state.dodgeCooldown-dt);syncGamepad();syncResources(false);if(state.basicResource)window.KeloMeleeEngine.tickResource(state.basicResource,rootProfile(),dt);const sp=rootProfile()&&rootProfile().specialAttackProfileId&&window.KeloMeleeEngine.getProfile(rootProfile().specialAttackProfileId);if(sp&&state.specialResource)window.KeloMeleeEngine.tickResource(state.specialResource,sp,dt);updateAttack(dt);updateDodge(dt);processIntents(t);updateFx(dt);if(state.comboExpiresAt&&t>state.comboExpiresAt+TUNING.comboGraceMs&&!state.basicAttack){state.comboStep=0;state.comboExpiresAt=0;}if(state.transitioning)freezeMovement();if(state.combatEnabled&&ready()){const r=localPlayer.radius||20;localPlayer.x=clamp(localPlayer.x,WORLD.x+r,WORLD.x+WORLD.w-r);localPlayer.y=clamp(localPlayer.y,WORLD.y+r,WORLD.y+WORLD.h-r);localPlayer._face=face(state.basicAttack?state.basicAttack.direction:state.aim);}audit('tick');}
function slotOf(target){const b=target&&target.closest&&target.closest('.stone-slot');return b?Number(b.dataset.slot):null;}
window.addEventListener('pointermove',e=>{if(!state.combatEnabled||state.transitioning)return;if(e.pointerType==='mouse'&&e.target===canvas){setAimScreen(e.clientX,e.clientY,'mouse');return;}if(e.pointerId===state.combatPointerId||e.pointerId===state.abilityPointerId)setAimScreen(e.clientX,e.clientY,e.pointerType||'pointer');},true);
window.addEventListener('pointerdown',e=>{if(!state.combatEnabled||state.transitioning)return;const slot=slotOf(e.target);state.lastPointerType=e.pointerType;if(slot!=null){e.preventDefault();e.stopImmediatePropagation();inputOwner.combat.push('ABILITY_PRESS',{slot});state.abilityPointerId=e.pointerId;state.abilityPointerSlot=slot;try{e.target.setPointerCapture(e.pointerId);}catch(_){}return;}if(e.target!==canvas)return;if(e.pointerType==='touch'&&e.clientX<(window.innerWidth||screenW)*TUNING.mobileCombatSplit)return;e.preventDefault();e.stopImmediatePropagation();setAimScreen(e.clientX,e.clientY,e.pointerType||'pointer');state.combatPointerId=e.pointerId;try{canvas.setPointerCapture(e.pointerId);}catch(_){}if(e.pointerType==='mouse'){inputOwner.combat.push(e.button===2?'SPECIAL_PRESS':'BASIC_PRESS',{source:'mouse'});}},true);
window.addEventListener('pointerup',e=>{if(!state.combatEnabled||state.transitioning)return;if(e.pointerId===state.abilityPointerId){setAimScreen(e.clientX,e.clientY,e.pointerType||'pointer');state.abilityPointerId=null;state.abilityPointerSlot=-1;inputOwner.combat.push('ABILITY_RELEASE');e.preventDefault();return;}if(e.pointerId===state.combatPointerId){setAimScreen(e.clientX,e.clientY,e.pointerType||'pointer');state.combatPointerId=null;if(e.pointerType==='touch'){inputOwner.combat.push('BASIC_PRESS',{source:'touch'});inputOwner.combat.push('BASIC_RELEASE',{source:'touch'});}else inputOwner.combat.push(e.button===2?'SPECIAL_RELEASE':'BASIC_RELEASE',{source:'mouse'});e.preventDefault();}},true);
window.addEventListener('pointercancel',e=>{if(e.pointerId===state.combatPointerId)state.combatPointerId=null;if(e.pointerId===state.abilityPointerId){state.abilityPointerId=null;state.abilityPointerSlot=-1;inputOwner.combat.push('CANCEL_CAST');}},true);
window.addEventListener('keydown',e=>{if(!state.combatEnabled||state.transitioning||inputOwner.isLocked())return;if(/^Digit[1-5]$/.test(e.code)){const slot=Number(e.code.slice(-1))-1;inputOwner.combat.push('ABILITY_PRESS',{slot});inputOwner.combat.push('ABILITY_RELEASE',{slot});e.preventDefault();}else if(e.code==='Space'){inputOwner.combat.push('DODGE_PRESS',{source:'keyboard'});e.preventDefault();}else if(e.code==='KeyQ'&&!e.repeat){inputOwner.combat.push('SPECIAL_PRESS',{source:'keyboard'});e.preventDefault();}else if(e.code==='Escape'){inputOwner.combat.push('CANCEL_CAST');e.preventDefault();}},true);
window.addEventListener('keyup',e=>{if(state.combatEnabled&&!state.transitioning&&e.code==='KeyQ'){inputOwner.combat.push('SPECIAL_RELEASE',{source:'keyboard'});e.preventDefault();}},true);window.addEventListener('contextmenu',e=>{if(state.combatEnabled&&e.target===canvas)e.preventDefault();},true);window.addEventListener('orientationchange',()=>{state.combatPointerId=null;state.abilityPointerId=null;state.abilityPointerSlot=-1;inputOwner.combat.push('CANCEL_CAST');});
function cancelAim(){state.armedSlot=-1;state.abilityPointerId=null;inputOwner.combat.push('CANCEL_CAST');}
function audit(event){const p=rootProfile(),a=state.basicAttack;window.KELO_PVP_AUDIT={version:VERSION,event,mode:state.mode,combatEnabled:state.combatEnabled,targetLock:false,aim360:true,rawAim:{x:state.aim.rawX,y:state.aim.rawY},aim:{x:state.aim.x,y:state.aim.y,source:state.aim.source},assistTargetId:state.assistTargetId,basicPhase:a&&a.phase||null,basicResource:state.basicResource&&{current:state.basicResource.current,max:state.basicResource.max,rechargeElapsed:state.basicResource.rechargeElapsed},comboStep:state.comboStep,comboSteps:p&&p.combo&&p.combo.length||1,inputBufferMs:inputOwner.combat.bufferMs,specialHolding:!!state.specialHold,dodgeActive:!!state.dodge,dodgeCooldown:state.dodgeCooldown,multitouchPointerEvents:true,radialDeadzone:true,softAimAssist:true,hysteresis:true,gamepadReady:true,telegraphsPresentationOnly:true,premiumAimIndicator:true,arenaActors:arenaActive(),onlineAuthority:online(),authority:online()?'server-intent+prediction':arenaActive()?'arena-local-fallback':'local-command-fallback',lastAuthorityTick:state.lastAuthorityTick,lastError:state.lastError};}
if(window.KeloMovement){window.KeloMovement.before('pvp-world:movement-scale',movementHook,70);window.KeloMovement.after('pvp-world:facing',facingHook,970);}if(!window.KeloSimulation||!window.KeloRender)throw new Error('PvP render/simulation owners unavailable');window.KeloSimulation.after('pvp-world:tick',tick,60);window.KeloRender.intercept('pvp-world:arena-exclusive',renderIntercept,10);
window.addEventListener('kelo:runtime-foundations-ready',()=>{if(state.pendingEnter){state.pendingEnter=false;enter();}},{passive:true});
window.enterPvPWorld=enter;window.leavePvPWorld=leave;window.KeloPvPWorld=Object.freeze({version:VERSION,enter,leave,startBasicAttack(source){inputOwner.combat.push('BASIC_PRESS',{source:source||'api'});return true;},quickCastSlot(slot){inputOwner.combat.push('ABILITY_PRESS',{slot:Number(slot)});inputOwner.combat.push('ABILITY_RELEASE',{slot:Number(slot)});return true;},setAimWorld,cancelAim,reconcileAuthority,get state(){return Object.freeze({mode:state.mode,combatEnabled:state.combatEnabled,armedSlot:state.armedSlot,aim:Object.freeze({x:state.aim.x,y:state.aim.y,worldX:state.aim.worldX,worldY:state.aim.worldY,source:state.aim.source}),basicResource:state.basicResource&&Object.freeze({current:state.basicResource.current,max:state.basicResource.max,rechargeElapsed:state.basicResource.rechargeElapsed}),specialResource:state.specialResource&&Object.freeze({current:state.specialResource.current,max:state.specialResource.max,rechargeElapsed:state.specialResource.rechargeElapsed}),comboStep:state.comboStep,basicAttack:state.basicAttack&&Object.freeze({id:state.basicAttack.id,kind:state.basicAttack.kind,phase:state.basicAttack.phase,profileId:state.basicAttack.profileId}),specialHolding:!!state.specialHold,dodgeActive:!!state.dodge,dodgeCooldown:state.dodgeCooldown,lastError:state.lastError});}});
function boot(){ensureExit();setExit(false);syncResources(true);audit('boot');}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
