/* KELO-INDEX
 * area: CREATORS / APPEARANCE UI
 * owner: shared Appearance Creator workspace UI
 * purpose: authoring outfits para character/mount con slots/perfiles compartidos, anchor drag, list virtualization e import
 * public-api: openAppearanceCreator
 * consumes: KeloAppearance, Character adapter, definition session, virtualRange, tabular importer
 * state-owned: draft appearance items only
 * online: drafts local; ownership/publish authority futura usa stable item IDs
 * do-not: no aplicar stats; no reemplazar CharacterCustomization; no crear editores separados por target
 */
import { createDefinitionWorkspaceSession } from '../core/definition-workspace-session.mjs';
import { virtualRange } from '../../studio/ui/virtual-list.mjs';
import { createDefinitionCreatorShell } from './definition-creator-shell.mjs';
import { importDefinitionFile } from '../importers/tabular-definition-importer.mjs';
let active=null;const copy=v=>v==null?v:JSON.parse(JSON.stringify(v));
function download(root,name,text){const u=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=root.document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),0);}
function tabularRows(rows){return(rows||[]).map((r,index)=>({schemaVersion:1,id:String(r.id||'').trim(),displayName:String(r.displayName||r.name||'').trim(),targetType:String(r.targetType||'mount').trim().toLowerCase(),slotId:String(r.slotId||'').trim(),compatibleProfiles:String(r.compatibleProfiles||r.profileId||'').split(/[|;]/).map(v=>v.trim()).filter(Boolean),assetBundleId:String(r.assetBundleId||'').trim(),transforms:{default:{x:Number(r.x)||0,y:Number(r.y)||0,scaleX:Number(r.scaleX)||1,scaleY:Number(r.scaleY)||1,rotation:Number(r.rotation)||0,flipX:String(r.flipX).toLowerCase()==='true',flipY:String(r.flipY).toLowerCase()==='true'}},layerRules:{depth:Number(r.depth)||0},animationMapping:{},tags:String(r.tags||'').split(/[|;]/).map(v=>v.trim()).filter(Boolean),rarity:String(r.rarity||'common'),__sourceRow:index+2}));}
export async function openAppearanceCreator({root=globalThis}={}){
 if(active)return active;if(!root.document||!root.KeloAppearance)throw new Error('APPEARANCE_CREATOR_RUNTIME_REQUIRED');root.KeloCharacterAppearanceAdapter?.install?.();const A=root.KeloAppearance;const session=createDefinitionWorkspaceSession({id:'creator:appearance',type:'APPEARANCE',rows:A.listItems().map(copy),validate:A.validateItem,normalize:A.migrate});const shell=createDefinitionCreatorShell({root,title:'KELO APPEARANCE CREATOR',subtitle:'One editor · Character + Mount · cosmetics stay gameplay-free'});let target='mount',query='',status='',drag=null;
 function profiles(){return A.listProfiles().filter(p=>p.targetType===target);}function rows(){let all=session.list().filter(r=>r.targetType===target);if(query){const q=query.toLowerCase();all=all.filter(r=>r.id.toLowerCase().includes(q)||r.displayName.toLowerCase().includes(q)||r.slotId.toLowerCase().includes(q));}return all;}
 function renderList(){const data=rows(),rh=42,range=virtualRange({count:data.length,rowHeight:rh,scrollTop:shell.list.scrollTop,viewportHeight:shell.list.clientHeight||600,overscan:5});shell.spacer.style.height=range.totalHeight+'px';shell.list.querySelectorAll('.kdc-row').forEach(n=>n.remove());for(let i=range.start;i<range.end;i++){const r=data[i],n=root.document.createElement('div');n.className='kdc-row'+(session.selectedId===r.id?' sel':'');n.style.top=(i*rh)+'px';n.innerHTML='<b>'+r.displayName+'</b><small>'+r.slotId+' · '+r.id+'</small>';n.onclick=()=>{session.select(r.id);renderAll();};shell.list.append(n);}}
 function selectedProfile(row){return A.getProfile(row?.compatibleProfiles?.[0])||profiles()[0]||null;}
 function renderPreview(){const row=session.get(session.selectedId);shell.stage.replaceChildren();const card=root.document.createElement('div');card.className='kdc-card';if(!row){card.innerHTML='<div><div style="font-size:48px">👕</div><h2>'+target.toUpperCase()+' OUTFITS</h2><p style="font-size:10px;color:#7e8791">Select an item or create one.</p></div>';shell.stage.append(card);return;}const t=row.transforms?.default||{},profile=selectedProfile(row);card.style.position='relative';card.style.overflow='hidden';card.innerHTML='<div style="position:absolute;top:12px;left:12px;text-align:left;font-size:8px;color:#68717c">'+row.assetBundleId+'</div><div style="position:relative;width:250px;height:250px;border:1px dashed rgba(255,255,255,.14);border-radius:18px;background:rgba(255,255,255,.018)" data-drag-zone><div style="position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);font-size:76px;opacity:.48">'+(target==='mount'?'🐎':'🧍')+'</div><div data-piece style="position:absolute;left:calc(50% + '+(Number(t.x)||0)+'px);top:calc(50% + '+(Number(t.y)||0)+'px);transform:translate(-50%,-50%) scale('+(Number(t.scaleX)||1)+','+(Number(t.scaleY)||1)+') rotate('+(Number(t.rotation)||0)+'deg);width:76px;height:46px;border:2px solid #d7b66b;border-radius:12px;background:rgba(215,182,107,.18);display:grid;place-items:center;color:#f3dda4;font-size:9px;font-weight:900;touch-action:none">'+row.slotId.toUpperCase()+'</div><div style="position:absolute;left:50%;top:50%;width:5px;height:5px;background:#fff;border-radius:50%;transform:translate(-50%,-50%);opacity:.6"></div></div><h3 style="margin:12px 0 3px">'+row.displayName+'</h3><div style="font-size:8px;color:#7e8791">'+(profile?.id||'NO PROFILE')+' · drag gold box to set X/Y</div>';shell.stage.append(card);const piece=card.querySelector('[data-piece]');piece.onpointerdown=e=>{e.preventDefault();drag={id:row.id,pointerId:e.pointerId,x0:e.clientX,y0:e.clientY,startX:Number(t.x)||0,startY:Number(t.y)||0};try{piece.setPointerCapture(e.pointerId);}catch{}};piece.onpointermove=e=>{if(!drag||e.pointerId!==drag.pointerId)return;const x=drag.startX+(e.clientX-drag.x0),y=drag.startY+(e.clientY-drag.y0);piece.style.left='calc(50% + '+x+'px)';piece.style.top='calc(50% + '+y+'px)';};piece.onpointerup=async e=>{if(!drag||e.pointerId!==drag.pointerId)return;const x=Math.round(drag.startX+(e.clientX-drag.x0)),y=Math.round(drag.startY+(e.clientY-drag.y0));drag=null;const current=session.get(row.id),next={...current,transforms:{...(current.transforms||{}),default:{...(current.transforms?.default||{}),x,y}}};const res=await session.upsert(next,{label:'move appearance anchor'});status=res.ok?'Anchor '+x+', '+y:(res.errors||[]).join('\n');renderAll();};piece.onpointercancel=()=>{drag=null;};}
 function f(label,key,value,options){const l=root.document.createElement('label');l.className='kdc-label';l.textContent=label;const n=options?root.document.createElement('select'):root.document.createElement('input');n.className='kdc-field';n.dataset.field=key;if(options){for(const v of options){const o=root.document.createElement('option');o.value=v;o.textContent=v;if(v===value)o.selected=true;n.append(o);}}else n.value=value??'';l.append(n);return l;}
 function renderInspector(){const row=session.get(session.selectedId);shell.inspector.replaceChildren();const toggle=root.document.createElement('div');toggle.className='kdc-grid2';for(const type of ['character','mount']){const b=root.document.createElement('button');b.className='kdc-btn'+(target===type?' gold':'');b.textContent=type.toUpperCase();b.onclick=()=>{target=type;const first=rows()[0];session.select(first?.id||null);renderAll();};toggle.append(b);}shell.inspector.append(toggle);if(!row){shell.inspector.insertAdjacentHTML('beforeend','<div class="kdc-foot">Shared Appearance Core. Select a '+target+' outfit.</div>');return;}const ps=profiles(),p=selectedProfile(row),slotOptions=p?.slots||[];shell.inspector.append(f('ID','id',row.id),f('DISPLAY NAME','displayName',row.displayName),f('TARGET','targetType',row.targetType,['character','mount']),f('PROFILE','profileId',p?.id||'',ps.map(x=>x.id)),f('SLOT','slotId',row.slotId,slotOptions),f('ASSET BUNDLE','assetBundleId',row.assetBundleId),f('RARITY','rarity',row.rarity,['common','rare','epic','legendary','mythic','divine']),f('X','x',row.transforms?.default?.x||0),f('Y','y',row.transforms?.default?.y||0),f('SCALE X','scaleX',row.transforms?.default?.scaleX??1),f('SCALE Y','scaleY',row.transforms?.default?.scaleY??1),f('ROTATION','rotation',row.transforms?.default?.rotation||0),f('DEPTH','depth',row.layerRules?.depth||0),f('TAGS ; separated','tags',(row.tags||[]).join(';')));const apply=root.document.createElement('button');apply.className='kdc-btn gold';apply.textContent='APPLY CHANGES';apply.style.marginTop='12px';apply.onclick=async()=>{const v=Object.fromEntries([...shell.inspector.querySelectorAll('[data-field]')].map(n=>[n.dataset.field,n.value])),next={...row,id:v.id.trim(),displayName:v.displayName.trim(),targetType:v.targetType,slotId:v.slotId,compatibleProfiles:[v.profileId],assetBundleId:v.assetBundleId.trim(),rarity:v.rarity,transforms:{...(row.transforms||{}),default:{...(row.transforms?.default||{}),x:Number(v.x)||0,y:Number(v.y)||0,scaleX:Number(v.scaleX)||1,scaleY:Number(v.scaleY)||1,rotation:Number(v.rotation)||0}},layerRules:{...(row.layerRules||{}),depth:Number(v.depth)||0},tags:v.tags.split(';').map(x=>x.trim()).filter(Boolean)};const r=await session.upsert(next,{label:'edit appearance'});status=r.ok?'✓ Visual definition valid':(r.errors||[]).join('\n');if(r.ok&&row.id!==next.id)await session.remove(row.id);target=next.targetType;renderAll();};shell.inspector.append(apply);const check=A.validateItem(row),m=root.document.createElement('div');m.className=check.ok?'kdc-ok':'kdc-errors';m.textContent=status||(check.ok?'✓ Cosmetic only · no stat modifiers':check.errors.join('\n'));shell.inspector.append(m);shell.inspector.insertAdjacentHTML('beforeend','<div class="kdc-foot">Preview box represents transform/anchor until the declared asset bundle is available. The definition does not modify gameplay stats.</div>');}
 function renderAll(){renderList();renderPreview();renderInspector();}
 shell.search.oninput=()=>{query=shell.search.value.trim();renderList();};shell.list.onscroll=renderList;
 shell.action('NEW',async()=>{const p=profiles()[0];if(!p)return;const row={schemaVersion:1,id:'outfit.'+target+'.new_'+Date.now().toString(36),displayName:'New Outfit',targetType:target,slotId:p.slots[0],compatibleProfiles:[p.id],assetBundleId:'outfit.'+target+'.asset.new',transforms:{default:{x:0,y:0,scaleX:1,scaleY:1,rotation:0}},layerRules:{depth:0},animationMapping:{},tags:[],rarity:'common'};const r=await session.upsert(row,{label:'new appearance'});if(r.ok)session.select(row.id);renderAll();},{gold:true});
 shell.action('DUPLICATE',async()=>{const row=session.get(session.selectedId);if(!row)return;row.id=row.id+'.copy_'+Date.now().toString(36);row.displayName+=' Copy';const r=await session.upsert(row,{label:'duplicate appearance'});if(r.ok)session.select(row.id);renderAll();});
 shell.action('IMPORT',()=>{const i=root.document.createElement('input');i.type='file';i.accept='.csv,.xlsx,.xls';i.onchange=async()=>{if(!i.files?.[0])return;try{const parsed=await importDefinitionFile(i.files[0],{root}),incoming=tabularRows(parsed.rows),errors=[],valid=[];for(const row of incoming){const c=A.validateItem(row);if(c.ok)valid.push(row);else errors.push({row:row.__sourceRow,id:row.id,errors:c.errors});}if(!errors.length)await session.importRows(valid);status=errors.length?errors.slice(0,8).map(e=>'Row '+e.row+' · '+(e.id||'?')+' · '+e.errors.join(', ')).join('\n'):'Import valid · '+valid.length+' outfits';renderAll();}catch(e){status=e.message;renderAll();}};i.click();});
 shell.action('UNDO',async()=>{await session.undo();renderAll();});shell.action('REDO',async()=>{await session.redo();renderAll();});shell.action('SAVE',async()=>{await session.save();status='Draft checkpoint saved';renderAll();},{gold:true});shell.action('EXPORT',()=>download(root,'kelo-appearance.json',JSON.stringify(session.snapshot(),null,2)));shell.action('CLOSE',close);
 function close(){session.close();shell.close();active=null;}
 session.onChange(()=>renderAll());const first=rows()[0];if(first)session.select(first.id);renderAll();active=Object.freeze({version:'appearance-creator-v1.0.0',session,shell,close});return active;
}
