/* KELO-INDEX
 * area: CORE
 * owner: KeloUpdater
 * keys: UPDATE PWA SERVICEWORKER BUILD VERSION IPHONE DELTA HASH CACHE PING NETWORK INSTANT
 * purpose: detect deployed builds and stage only missing content-addressed boot bytes before atomic activation
 * public-api: KeloUpdater.check(), prepareUpdate(), applyUpdate(), evaluateNetwork(), setGameplayBusy(), setNetworkPriority(), getState()
 * consumes: version.json, GitHub tree manifest for deployed SHA, Cache Storage, Service Worker, KeloUpdateDelta
 * state-owned: updater metadata, static update caches and ephemeral network/update metrics; never gameplay/auth/API state
 * do-not: never cache gameplay/API/session responses and never compete with active PVP/combat
 */
(function initKeloUpdater(global) {
  'use strict';
  if (global.KeloUpdater) return;

  const STORAGE_KEY = 'kelo.world.updater.installedBuild.v1';
  const BUILD_RE = /^[0-9a-f]{7,64}$/i;
  const GIT_BLOB_RE = /^[0-9a-f]{40,64}$/i;
  const STAGE_CACHE_PREFIX = 'kelo-update-stage-v3-';
  const LEGACY_STAGE_CACHE_PREFIX = 'kelo-update-stage-v2-';
  const ASSET_CACHE_NAME = 'kelo-assets-v3';
  const META_CACHE_NAME = 'kelo-update-meta-v3';
  const STAGE_META_PATH = '__kelo_update_stage_meta_v3__.json';
  const MANIFEST_META_PATH = '__kelo_update_manifest_v3__.json';
  const TREE_META_PATH = '__kelo_update_tree_v3__.json';
  const ACTIVE_BUILD_META_PATH = '__kelo_update_active_build_v3__.json';
  const GITHUB_TREE_API = 'https://api.github.com/repos/kelffren/gemini/git/trees/';
  const PING_TIMEOUT_MS = 3500;
  const FETCH_TIMEOUT_MS = 20000;
  const MANIFEST_TIMEOUT_MS = 12000;
  const PROBE_FRESH_MS = 5000;
  const PAUSE_RETRY_MS = 4000;
  const NETWORK_POLICY = Object.freeze({ goodMaxMs:100, fairMaxMs:150, constrainedMaxMs:200, goodDelayMs:0, fairDelayMs:120, constrainedDelayMs:450 });

  const deltaCore = global.KeloUpdateDelta;
  const baseUrl = new URL('./', document.baseURI);
  const indexUrl = new URL('index.html', baseUrl);
  const versionUrl = new URL('version.json', baseUrl);
  const serviceWorkerUrl = new URL('sw.js', baseUrl);
  let stageGeneration = 0;
  let activeStagePromise = null;
  let foregroundStage = false;
  const activeFetchControllers = new Set();

  const state = {
    status:'booting', installedBuild:normalizeBuild(safeGet(STORAGE_KEY)), deployedBuild:null, availableBuild:null,
    serviceWorkerReady:false, lastError:null, manualGameplayBusy:false, stage:emptyStage(),
    storage:{ persisted:null, usageBytes:null, quotaBytes:null },
    network:{ status:'unknown', pingMs:null, samples:[], failures:0, saveData:false, effectiveType:null, downlinkMbps:null, lastDownloadMbps:null, lastProbeAt:0, recovering:false, healthyStreak:0, reason:null }
  };

  function safeGet(key){ try{return global.localStorage?global.localStorage.getItem(key):null;}catch(_){return null;} }
  function safeSet(key,value){ try{if(global.localStorage)global.localStorage.setItem(key,value);}catch(_){} }
  function normalizeBuild(value){const build=String(value||'').trim();return BUILD_RE.test(build)?build.toLowerCase():null;}
  function normalizeBlob(value){const blob=String(value||'').trim();return GIT_BLOB_RE.test(blob)?blob.toLowerCase():null;}
  function emptyStage(){return {build:null,status:'idle',total:0,completed:0,percent:0,currentUrl:null,deltaBytes:0,reusedBytes:0,deltaFiles:0,reusedFiles:0,downloadedBytes:0,timeToReadyMs:null,concurrency:0,manifestSource:null};}
  function writeInstalledBuild(build){const n=normalizeBuild(build);if(!n)return;state.installedBuild=n;safeSet(STORAGE_KEY,n);}
  function networkSnapshot(){return {status:state.network.status,pingMs:state.network.pingMs,failures:state.network.failures,saveData:state.network.saveData,effectiveType:state.network.effectiveType,downlinkMbps:state.network.downlinkMbps,lastDownloadMbps:state.network.lastDownloadMbps,lastProbeAt:state.network.lastProbeAt,recovering:state.network.recovering,reason:state.network.reason};}
  function getState(){return Object.freeze({status:state.status,installedBuild:state.installedBuild,deployedBuild:state.deployedBuild,availableBuild:state.availableBuild,serviceWorkerReady:state.serviceWorkerReady,gameplayBusy:isGameplayBusy(),stage:Object.assign({},state.stage),storage:Object.assign({},state.storage),network:networkSnapshot(),lastError:state.lastError});}
  function emit(name,detail){global.dispatchEvent(new CustomEvent('kelo:update:'+name,{detail:Object.assign({},getState(),detail||{})}));}
  function median(values){if(!values.length)return null;const s=values.slice().sort((a,b)=>a-b),m=Math.floor(s.length/2);return s.length%2?s[m]:Math.round((s[m-1]+s[m])/2);}
  function sleep(ms){return new Promise(r=>global.setTimeout(r,Math.max(0,Number(ms)||0)));}
  async function timedFetch(url,options,timeoutMs,tracked){const controller=new AbortController();const timer=global.setTimeout(()=>controller.abort(),Math.max(500,Number(timeoutMs)||FETCH_TIMEOUT_MS));if(tracked)activeFetchControllers.add(controller);try{return await fetch(url,Object.assign({},options||{},{signal:controller.signal}));}finally{global.clearTimeout(timer);if(tracked)activeFetchControllers.delete(controller);}}
  function abortBackgroundDownloads(){for(const c of activeFetchControllers){try{c.abort();}catch(_){}}activeFetchControllers.clear();}
  function connectionHints(){const c=navigator.connection||navigator.mozConnection||navigator.webkitConnection||null;return {saveData:!!(c&&c.saveData),effectiveType:c&&c.effectiveType?String(c.effectiveType):null,downlinkMbps:c&&Number.isFinite(Number(c.downlink))?Number(c.downlink):null,rtt:c&&Number.isFinite(Number(c.rtt))?Number(c.rtt):null};}
  function isGameplayBusy(){if(state.manualGameplayBusy)return true;if(global.KELO_COMBAT_ENABLED===true)return true;try{if(global.KeloArena&&typeof global.KeloArena.isActive==='function'&&global.KeloArena.isActive())return true;}catch(_){}return false;}
  function networkGateFromState(options){const o=options||{};if(!navigator.onLine)return {allow:false,delayMs:PAUSE_RETRY_MS,reason:'offline'};if(isGameplayBusy())return {allow:false,delayMs:2000,reason:'gameplay-priority'};if(document.visibilityState==='hidden'&&!o.foreground)return {allow:false,delayMs:PAUSE_RETRY_MS,reason:'background'};if(state.network.saveData&&!o.foreground)return {allow:false,delayMs:15000,reason:'save-data'};if((state.network.effectiveType==='slow-2g'||state.network.effectiveType==='2g')&&!o.foreground)return {allow:false,delayMs:15000,reason:'slow-network'};if(o.foreground)return {allow:true,delayMs:0,reason:'foreground'};if(state.network.status==='good')return {allow:true,delayMs:NETWORK_POLICY.goodDelayMs,reason:'good'};if(state.network.status==='fair')return {allow:true,delayMs:NETWORK_POLICY.fairDelayMs,reason:'fair'};if(state.network.status==='constrained')return {allow:true,delayMs:NETWORK_POLICY.constrainedDelayMs,reason:'constrained'};return {allow:false,delayMs:PAUSE_RETRY_MS,reason:state.network.reason||state.network.status||'unknown'};}

  async function evaluateNetwork(options){
    const o=options||{},h=connectionHints();state.network.saveData=h.saveData;state.network.effectiveType=h.effectiveType;state.network.downlinkMbps=h.downlinkMbps;
    if(!navigator.onLine)return finishBlockedProbe('offline',PAUSE_RETRY_MS);if(isGameplayBusy())return finishBlockedProbe('gameplay-priority',2000);if(document.visibilityState==='hidden'&&!o.foreground)return finishBlockedProbe('background',PAUSE_RETRY_MS);if(h.saveData&&!o.foreground)return finishBlockedProbe('save-data',15000);if((h.effectiveType==='slow-2g'||h.effectiveType==='2g')&&!o.foreground)return finishBlockedProbe('slow-network',15000);
    const probe=new URL(versionUrl.href);probe.searchParams.set('_kelo_ping',Date.now().toString(36));const started=performance.now();
    try{const response=await timedFetch(probe.href,{cache:'no-store',credentials:'same-origin',priority:o.foreground?'high':'low'},PING_TIMEOUT_MS,true);if(!response.ok)throw new Error('ping_http_'+response.status);await response.text();const measured=Math.max(1,Math.round(performance.now()-started));state.network.samples.push(measured);if(state.network.samples.length>5)state.network.samples.shift();const sample=median(state.network.samples)||measured,effective=h.rtt!=null?Math.max(sample,h.rtt):sample;state.network.pingMs=Math.round(effective);state.network.failures=0;state.network.lastProbeAt=Date.now();let next='poor',reason='latency';if(effective<=NETWORK_POLICY.goodMaxMs){next='good';reason=null;}else if(effective<=NETWORK_POLICY.fairMaxMs){next='fair';reason=null;}else if(effective<=NETWORK_POLICY.constrainedMaxMs){next='constrained';reason=null;}if(h.downlinkMbps!=null&&h.downlinkMbps<0.8&&!o.foreground){next='poor';reason='low-throughput';}if(next==='poor'){state.network.recovering=true;state.network.healthyStreak=0;state.network.status='poor';state.network.reason=reason;}else if(state.network.recovering){state.network.healthyStreak+=1;if(state.network.healthyStreak<2&&!o.foreground){state.network.status='recovering';state.network.reason='latency-recovery';}else{state.network.recovering=false;state.network.healthyStreak=0;state.network.status=next;state.network.reason=null;}}else{state.network.status=next;state.network.reason=null;}}
    catch(error){state.network.failures+=1;state.network.lastProbeAt=Date.now();state.network.recovering=true;state.network.healthyStreak=0;state.network.status='unstable';state.network.reason=error&&error.name==='AbortError'?'timeout':'probe-failed';}
    const gate=networkGateFromState(o),snapshot=Object.assign({allow:gate.allow,delayMs:gate.delayMs,reason:gate.reason},networkSnapshot());emit('network',snapshot);return snapshot;
  }
  function finishBlockedProbe(reason,delayMs){state.network.status=reason;state.network.reason=reason;state.network.lastProbeAt=Date.now();const snapshot=Object.assign({allow:false,delayMs,reason},networkSnapshot());emit('network',snapshot);return snapshot;}
  async function fetchDeployedBuild(){if(isGameplayBusy())throw new Error('update_blocked_combat');const url=new URL(versionUrl.href);url.searchParams.set('_kelo_check',Date.now().toString(36));const response=await timedFetch(url.href,{cache:'no-store',credentials:'same-origin',priority:'low'},PING_TIMEOUT_MS,true);if(!response.ok)throw new Error('version_http_'+response.status);let p;try{p=await response.json();}catch(_){throw new Error('version_not_json');}const b=normalizeBuild(p&&p.sha);if(!b)throw new Error('version_missing_sha');return b;}
  async function requestPersistentStorage(){try{if(!navigator.storage)return;if(typeof navigator.storage.persisted==='function')state.storage.persisted=await navigator.storage.persisted();if(!state.storage.persisted&&typeof navigator.storage.persist==='function')state.storage.persisted=await navigator.storage.persist();if(typeof navigator.storage.estimate==='function'){const e=await navigator.storage.estimate();state.storage.usageBytes=Number(e&&e.usage)||0;state.storage.quotaBytes=Number(e&&e.quota)||0;}}catch(_){} }
  async function registerServiceWorker(){if(!('serviceWorker'in navigator)||!global.isSecureContext){state.serviceWorkerReady=false;return null;}if(/iPhone|iPad|iPod/i.test(global.navigator&&global.navigator.userAgent||'')){state.serviceWorkerReady=false;return null;}try{const r=await navigator.serviceWorker.register(serviceWorkerUrl.href,{scope:baseUrl.pathname,updateViaCache:'none'});try{await r.update();}catch(_){}await navigator.serviceWorker.ready;state.serviceWorkerReady=true;return r;}catch(error){state.serviceWorkerReady=false;state.lastError=String(error&&error.message||error);emit('service-worker-error');return null;}}
  function requestedUpdateBuild(){try{return normalizeBuild(new URL(global.location.href).searchParams.get('kelo_update'));}catch(_){return null;}}
  function clearUpdateQuery(){try{const u=new URL(global.location.href);if(!u.searchParams.has('kelo_update')&&!u.searchParams.has('kelo_update_nonce'))return;u.searchParams.delete('kelo_update');u.searchParams.delete('kelo_update_nonce');global.history.replaceState(global.history.state,'',u.href);}catch(_){} }
  function stageCacheName(build){const n=normalizeBuild(build);return n?STAGE_CACHE_PREFIX+n:null;}
  function metaUrl(pathname,build){const u=new URL(pathname,baseUrl);if(build)u.searchParams.set('build',normalizeBuild(build)||String(build));return u.href;}
  function stageMetaUrl(build){return metaUrl(STAGE_META_PATH,build);}function manifestMetaUrl(build){return metaUrl(MANIFEST_META_PATH,build);}function treeMetaUrl(build){return metaUrl(TREE_META_PATH,build);}function activeBuildMetaUrl(){return metaUrl(ACTIVE_BUILD_META_PATH);}
  function assetObjectUrl(blob){const n=normalizeBlob(blob);return n?new URL('__kelo_asset_v3__/'+n,baseUrl).href:null;}
  async function readJsonResponse(r){if(!r)return null;try{return await r.json();}catch(_){return null;}}
  async function getCachedMeta(url){if(!('caches'in global))return null;try{const c=await caches.open(META_CACHE_NAME);return await readJsonResponse(await c.match(url));}catch(_){return null;}}
  async function putCachedMeta(url,payload){if(!('caches'in global))return;const c=await caches.open(META_CACHE_NAME);await c.put(url,new Response(JSON.stringify(payload),{headers:{'content-type':'application/json','cache-control':'no-store'}}));}
  async function setActiveBuild(build){const n=normalizeBuild(build);if(!n)return;try{await putCachedMeta(activeBuildMetaUrl(),{build:n,updatedAt:new Date().toISOString()});}catch(_){}try{const r=await navigator.serviceWorker.ready,w=navigator.serviceWorker.controller||r.active||r.waiting;if(w)w.postMessage({type:'KELO_SET_ACTIVE_BUILD',build:n});}catch(_){} }
  async function isBuildStaged(build){const n=normalizeBuild(build);if(!n||!('caches'in global))return false;try{const c=await caches.open(stageCacheName(n)),p=await readJsonResponse(await c.match(stageMetaUrl(n)));return !!(p&&p.complete===true&&normalizeBuild(p.build)===n);}catch(_){return false;}}
  async function cleanupStageCaches(keepBuild){if(!('caches'in global))return;const keep=keepBuild?stageCacheName(keepBuild):null;try{const names=await caches.keys();await Promise.all(names.filter(n=>(n.startsWith(STAGE_CACHE_PREFIX)||n.startsWith(LEGACY_STAGE_CACHE_PREFIX))&&n!==keep).map(n=>caches.delete(n)));}catch(_){} }
  function isStageableUrl(value){try{const u=new URL(value,baseUrl);if(u.origin!==baseUrl.origin||!u.pathname.startsWith(baseUrl.pathname)||u.pathname===versionUrl.pathname||u.pathname===serviceWorkerUrl.pathname)return false;return u.protocol==='https:'||u.protocol==='http:';}catch(_){return false;}}
  function assetPriority(url,source){const p=new URL(url).pathname.toLowerCase();let priority=4;if(p.endsWith('.css')||p.includes('/src/core/'))priority=0;else if(p.endsWith('.js')||p.endsWith('.mjs')||p.includes('engine-net'))priority=1;else if(p.endsWith('.webmanifest')||/\.(woff2?|ttf|otf)$/.test(p))priority=2;else if(/\.(png|jpe?g|webp|gif|svg|avif)$/.test(p))priority=3;return source==='session'?priority+10:priority;}
  function repoPathForUrl(url){if(deltaCore&&typeof deltaCore.normalizeRepoPath==='function')return deltaCore.normalizeRepoPath(url,baseUrl.href);try{const p=new URL(url,baseUrl);return decodeURIComponent(p.pathname.slice(baseUrl.pathname.length).replace(/^\/+/, '')||'index.html');}catch(_){return null;}}

  async function fetchBuildTree(build){
    const n=normalizeBuild(build);if(!n)throw new Error('manifest_invalid_build');if(isGameplayBusy())throw new Error('update_blocked_combat');const cached=await getCachedMeta(treeMetaUrl(n));if(cached&&cached.build===n&&cached.files)return cached;
    const response=await timedFetch(GITHUB_TREE_API+n+'?recursive=1',{cache:'no-store',headers:{accept:'application/vnd.github+json'},priority:'low'},MANIFEST_TIMEOUT_MS,true);if(!response.ok)throw new Error('manifest_tree_http_'+response.status);const payload=await response.json(),files={};for(const item of Array.isArray(payload&&payload.tree)?payload.tree:[]){if(!item||item.type!=='blob'||!item.path)continue;const blob=normalizeBlob(item.sha);if(blob)files[String(item.path)]={blob,bytes:Number(item.size)||0};}const manifest={build:n,source:'github-tree',files,createdAt:new Date().toISOString()};await putCachedMeta(treeMetaUrl(n),manifest);return manifest;
  }
  async function buildStagePlan(build){
    if(isGameplayBusy())throw new Error('update_blocked_combat');const fresh=new URL(indexUrl.href);fresh.searchParams.set('_kelo_stage',build);fresh.searchParams.set('_kelo_nonce',Date.now().toString(36));
    const [indexResponse,tree]=await Promise.all([timedFetch(fresh.href,{cache:'reload',credentials:'same-origin',priority:foregroundStage?'high':'low'},FETCH_TIMEOUT_MS,true),fetchBuildTree(build)]);if(!indexResponse.ok)throw new Error('stage_index_http_'+indexResponse.status);
    const indexForCache=indexResponse.clone(),html=await indexResponse.text(),parsed=new DOMParser().parseFromString(html,'text/html'),entries=new Map();
    function add(value,source,required){if(!value||!isStageableUrl(value))return;const u=new URL(value,baseUrl);u.hash='';const key=u.href;if(key===baseUrl.href||key===indexUrl.href)return;const path=repoPathForUrl(key),identity=path&&tree.files[path]||null,existing=entries.get(key);if(existing){existing.required=existing.required||!!required;return;}entries.set(key,{url:key,path,blob:identity&&identity.blob||null,bytes:identity&&identity.bytes||0,source:source||'index',group:required?'critical':'deferred',required:!!required,priority:assetPriority(key,source||'index')});}
    parsed.querySelectorAll('script[src]').forEach(n=>add(n.getAttribute('src'),'index',true));parsed.querySelectorAll('link[href]').forEach(n=>{const rel=String(n.getAttribute('rel')||'').toLowerCase();if(/(stylesheet|preload|modulepreload|manifest|icon)/.test(rel))add(n.getAttribute('href'),'index',true);});
    try{performance.getEntriesByType('resource').forEach(e=>{const name=e&&e.name;if(!name||!isStageableUrl(name)||!/\.(?:js|mjs|css|woff2?|ttf|otf)(?:[?#].*)?$/i.test(name))return;add(name,'session',false);});}catch(_){}
    const plan=Array.from(entries.values()).sort((a,b)=>a.priority-b.priority),manifest={build,source:tree.source,files:plan.map(e=>({url:e.url,path:e.path,blob:e.blob,bytes:e.bytes,group:e.group,required:e.required})),createdAt:new Date().toISOString()};await putCachedMeta(manifestMetaUrl(build),manifest);return {plan,indexForCache,manifest};
  }
  async function cachedBlobSet(){const set=new Set();if(!('caches'in global))return set;try{const c=await caches.open(ASSET_CACHE_NAME),keys=await c.keys();for(const request of keys){const marker='/__kelo_asset_v3__/',i=request.url.indexOf(marker);if(i<0)continue;const b=normalizeBlob(request.url.slice(i+marker.length).split(/[?#]/)[0]);if(b)set.add(b);}}catch(_){}return set;}
  function computeDiff(entries,cached){if(deltaCore&&typeof deltaCore.diffManifest==='function')return deltaCore.diffManifest(entries,cached);const missing=[],reused=[];let deltaBytes=0,reusedBytes=0;for(const e of entries){if(e.blob&&cached.has(e.blob)){reused.push(e);reusedBytes+=Number(e.bytes)||0;}else{missing.push(e);deltaBytes+=Number(e.bytes)||0;}}return {missing,reused,deltaFiles:missing.length,reusedFiles:reused.length,deltaBytes,reusedBytes};}
  function updateStageProgress(build,completed,total,currentUrl){state.stage.build=build;state.stage.completed=completed;state.stage.total=total;state.stage.percent=total?Math.min(100,Math.round(completed/total*100)):100;state.stage.currentUrl=currentUrl||null;emit('staging-progress',{build,completed,total,percent:state.stage.percent,deltaBytes:state.stage.deltaBytes,reusedBytes:state.stage.reusedBytes,downloadedBytes:state.stage.downloadedBytes,deltaFiles:state.stage.deltaFiles,reusedFiles:state.stage.reusedFiles,concurrency:state.stage.concurrency,pingMs:state.network.pingMs,networkStatus:state.network.status});}
  async function waitForNetworkGate(generation,build,options){const o=options||{};for(;;){if(generation!==stageGeneration||state.availableBuild!==build)throw new Error('stage_cancelled');const immediate=networkGateFromState(o),fresh=Date.now()-state.network.lastProbeAt<PROBE_FRESH_MS,gate=fresh&&immediate.reason!=='unknown'?immediate:await evaluateNetwork(o);if(gate.allow){if(state.stage.status==='paused'){state.stage.status='downloading';emit('staging-resumed',{build,pingMs:state.network.pingMs,networkStatus:state.network.status});}return gate;}state.stage.status='paused';state.network.reason=gate.reason||state.network.reason;emit('staging-paused',{build,reason:gate.reason||state.network.reason,pingMs:state.network.pingMs,networkStatus:state.network.status});await sleep(gate.delayMs||PAUSE_RETRY_MS);state.network.lastProbeAt=0;}}
  function chooseConcurrency(options){const o=options||{};if(deltaCore&&typeof deltaCore.chooseConcurrency==='function')return deltaCore.chooseConcurrency({gameplayBusy:isGameplayBusy(),foreground:!!o.foreground,status:state.network.status,pingMs:state.network.pingMs,downlinkMbps:state.network.downlinkMbps});if(isGameplayBusy())return 0;if(o.foreground)return 6;if(state.network.status==='constrained'||Number.isFinite(state.network.pingMs)&&state.network.pingMs>150)return 1;if(state.network.status==='fair'||Number.isFinite(state.network.pingMs)&&state.network.pingMs>100)return 2;if(state.network.status==='good'||Number.isFinite(state.network.pingMs)&&state.network.pingMs<=100){if(Number.isFinite(state.network.pingMs)&&state.network.pingMs<70&&Number.isFinite(state.network.downlinkMbps)&&state.network.downlinkMbps>=10)return 6;return 4;}return 1;}
  function hex(buffer){return Array.from(new Uint8Array(buffer),b=>b.toString(16).padStart(2,'0')).join('');}
  async function computeGitBlobSha(buffer){if(!global.crypto||!global.crypto.subtle||!global.TextEncoder)return null;try{const bytes=new Uint8Array(buffer),header=new TextEncoder().encode('blob '+bytes.byteLength+'\0'),payload=new Uint8Array(header.byteLength+bytes.byteLength);payload.set(header,0);payload.set(bytes,header.byteLength);return hex(await global.crypto.subtle.digest('SHA-1',payload));}catch(_){return null;}}
  async function fetchAndStoreAsset(entry,options){if(isGameplayBusy())throw new Error('update_blocked_combat');const o=options||{},started=performance.now(),response=await timedFetch(entry.url,{cache:'default',credentials:'same-origin',priority:o.foreground?'high':'low'},FETCH_TIMEOUT_MS,true);if(!response.ok)throw new Error('stage_asset_http_'+response.status);const buffer=await response.arrayBuffer(),bytes=buffer.byteLength,elapsed=Math.max(1,performance.now()-started);if(bytes>0){state.network.lastDownloadMbps=Math.round((bytes*8/(elapsed/1000)/1000000)*10)/10;state.stage.downloadedBytes+=bytes;}if(entry.blob){const verified=await computeGitBlobSha(buffer);if(verified&&verified!==entry.blob)throw new Error('stage_asset_hash_mismatch');}const headers=new Headers(response.headers);headers.set('x-kelo-content-blob',entry.blob||'');const stored=new Response(buffer,{status:response.status,statusText:response.statusText,headers});if(entry.blob){const c=await caches.open(ASSET_CACHE_NAME);await c.put(assetObjectUrl(entry.blob),stored);}else{const c=await caches.open(stageCacheName(state.stage.build));await c.put(entry.url,stored);}}
  async function downloadEntryWithRetry(entry,generation,build,options){let attempts=0;while(attempts<3){attempts+=1;await waitForNetworkGate(generation,build,options);try{await fetchAndStoreAsset(entry,options);return;}catch(error){if(String(error&&error.message||error)==='stage_cancelled')throw error;if((error&&error.name==='AbortError'||String(error&&error.message||error)==='update_blocked_combat')&&isGameplayBusy()){state.stage.status='paused';state.network.reason='gameplay-priority';await sleep(350);continue;}state.network.failures+=1;state.network.recovering=true;state.network.healthyStreak=0;state.network.status='unstable';state.network.reason=error&&error.name==='AbortError'?'timeout':'download-failed';state.network.lastProbeAt=0;if(!entry.required&&attempts>=2)return;if(attempts>=3)throw error;state.stage.status='paused';emit('staging-paused',{build,reason:state.network.reason,pingMs:state.network.pingMs,networkStatus:state.network.status});await sleep(options&&options.foreground?250:PAUSE_RETRY_MS);}}}
  async function downloadMissing(entries,generation,build,options,progress){const queue=entries.slice(),o=options||{};while(queue.length){const gate=await waitForNetworkGate(generation,build,o);let concurrency=chooseConcurrency(o);if(concurrency<=0){await sleep(500);continue;}concurrency=Math.max(1,Math.min(concurrency,queue.length));state.stage.concurrency=concurrency;const batch=queue.splice(0,concurrency);await Promise.all(batch.map(async entry=>{await downloadEntryWithRetry(entry,generation,build,o);progress.completed+=1;updateStageProgress(build,progress.completed,progress.total,entry.url);}));if(gate.delayMs)await sleep(gate.delayMs);}}
  function scheduleDeferredStage(entries,generation,build){if(!entries.length)return;const run=async()=>{if(generation!==stageGeneration||state.availableBuild!==build||isGameplayBusy())return;try{const cached=await cachedBlobSet(),diff=computeDiff(entries,cached);if(!diff.missing.length)return;const progress={completed:0,total:diff.missing.length};await downloadMissing(diff.missing,generation,build,{foreground:false},progress);emit('deferred-staged',{build,downloadedFiles:diff.missing.length,downloadedBytes:state.stage.downloadedBytes});}catch(_){}};if(typeof global.requestIdleCallback==='function')global.requestIdleCallback(()=>run(),{timeout:8000});else global.setTimeout(run,2500);}

  async function prepareUpdate(build,options){
    if(isGameplayBusy())throw new Error('update_blocked_combat');const o=options||{},target=normalizeBuild(build||state.availableBuild||state.deployedBuild);if(!target)throw new Error('no_update_build');if(state.installedBuild===target)return getState();if(!('caches'in global)){state.status='available';state.stage=Object.assign(emptyStage(),{build:target,status:'unsupported'});emit('staging-unsupported',{build:target});return getState();}
    if(await isBuildStaged(target)){state.status='ready';state.stage.build=target;state.stage.status='ready';state.stage.percent=100;emit('staged',Object.assign({build:target,percent:100,reused:true},state.stage));return getState();}
    if(activeStagePromise&&state.stage.build===target&&['planning','downloading','paused'].includes(state.stage.status))return activeStagePromise;
    const generation=++stageGeneration,started=performance.now();foregroundStage=!!o.foreground;state.status='preparing';state.stage=Object.assign(emptyStage(),{build:target,status:'planning'});state.lastError=null;emit('staging',{build:target});
    activeStagePromise=(async()=>{await cleanupStageCaches(target);await waitForNetworkGate(generation,target,o);const {plan,indexForCache,manifest}=await buildStagePlan(target);if(generation!==stageGeneration||state.availableBuild!==target)throw new Error('stage_cancelled');const stageCache=await caches.open(stageCacheName(target));await stageCache.put(baseUrl.href,indexForCache.clone());await stageCache.put(indexUrl.href,indexForCache.clone());const critical=plan.filter(e=>e.required),deferred=plan.filter(e=>!e.required),cached=await cachedBlobSet(),diff=computeDiff(critical,cached);state.stage.manifestSource=manifest.source;state.stage.deltaBytes=diff.deltaBytes;state.stage.reusedBytes=diff.reusedBytes;state.stage.deltaFiles=diff.deltaFiles;state.stage.reusedFiles=diff.reusedFiles;state.stage.total=critical.length+1;state.stage.completed=diff.reusedFiles+1;state.stage.status='downloading';updateStageProgress(target,state.stage.completed,state.stage.total,indexUrl.href);const progress={completed:state.stage.completed,total:state.stage.total};await downloadMissing(diff.missing,generation,target,o,progress);await stageCache.put(stageMetaUrl(target),new Response(JSON.stringify({build:target,complete:true,required:critical.length,deltaFiles:state.stage.deltaFiles,deltaBytes:state.stage.deltaBytes,reusedFiles:state.stage.reusedFiles,reusedBytes:state.stage.reusedBytes,completedAt:new Date().toISOString()}),{headers:{'content-type':'application/json'}}));if(generation!==stageGeneration||state.availableBuild!==target)throw new Error('stage_cancelled');state.status='ready';state.stage.status='ready';state.stage.percent=100;state.stage.completed=state.stage.total;state.stage.currentUrl=null;state.stage.timeToReadyMs=Math.max(0,Math.round(performance.now()-started));emit('staged',Object.assign({build:target,completed:state.stage.total,total:state.stage.total,percent:100,pingMs:state.network.pingMs},state.stage));scheduleDeferredStage(deferred,generation,target);return getState();})().catch(error=>{if(String(error&&error.message||error)==='stage_cancelled')return getState();if(String(error&&error.message||error)==='update_blocked_combat'){state.status='available';state.stage.status='paused';state.network.reason='gameplay-priority';emit('staging-paused',{build:target,reason:'gameplay-priority'});return getState();}state.status='available';state.stage.status='error';state.lastError=String(error&&error.message||error);emit('staging-error',{build:target,error:state.lastError});return getState();}).finally(()=>{if(generation===stageGeneration)activeStagePromise=null;foregroundStage=false;});return activeStagePromise;
  }
  async function check(options){const o=options||{};if(isGameplayBusy())return getState();if(state.status==='checking'&&!o.force)return getState();const previous=state.status;state.status='checking';state.lastError=null;emit('checking');try{const deployed=await fetchDeployedBuild();state.deployedBuild=deployed;const requested=requestedUpdateBuild();if(requested&&requested===deployed){writeInstalledBuild(deployed);await setActiveBuild(deployed);clearUpdateQuery();scheduleStageCleanup();}if(!state.installedBuild){writeInstalledBuild(deployed);await setActiveBuild(deployed);}if(state.installedBuild!==deployed){state.availableBuild=deployed;state.status=previous==='ready'&&state.stage.build===deployed?'ready':'available';emit('available',{build:deployed});prepareUpdate(deployed).catch(()=>{});}else{stageGeneration+=1;state.availableBuild=null;state.status='current';state.stage=emptyStage();await setActiveBuild(deployed);emit('current',{build:deployed});if(!requested)cleanupStageCaches(null).catch(()=>{});}}catch(error){state.status=previous==='ready'?'ready':'error';state.lastError=String(error&&error.message||error);emit('error');}return getState();}
  function scheduleStageCleanup(){const cleanup=()=>global.setTimeout(()=>cleanupStageCaches(null).catch(()=>{}),5000);if(document.readyState==='complete')cleanup();else global.addEventListener('load',cleanup,{once:true});}
  async function applyUpdate(){if(isGameplayBusy())throw new Error('update_blocked_combat');if(!state.availableBuild)await check({force:true});const target=state.availableBuild||state.deployedBuild;if(!target)throw new Error('no_update_build');const staged=await isBuildStaged(target);if(!staged&&state.stage.status!=='unsupported'){await prepareUpdate(target,{foreground:true});if(!await isBuildStaged(target))throw new Error('update_not_staged');}if(isGameplayBusy())throw new Error('update_blocked_combat');state.status='applying';emit('applying',{build:target,priority:'high'});const registration=await registerServiceWorker();if(registration){const worker=registration.waiting||registration.active||navigator.serviceWorker.controller;try{if(worker)worker.postMessage({type:'KELO_SKIP_WAITING'});}catch(_){}}const next=new URL(global.location.href);next.searchParams.set('kelo_update',target);next.searchParams.set('kelo_update_nonce',Date.now().toString(36));global.location.replace(next.href);}
  function setGameplayBusy(busy,source){state.manualGameplayBusy=!!busy;state.network.lastProbeAt=0;if(state.manualGameplayBusy){stageGeneration+=1;abortBackgroundDownloads();if(state.stage&&['planning','downloading'].includes(state.stage.status))state.stage.status='paused';state.network.reason='gameplay-priority';}emit('network-priority',{busy:state.manualGameplayBusy,source:String(source||'manual')});return getState();}
  function setNetworkPriority(priority,source){const v=String(priority||'').toLowerCase();return setGameplayBusy(v==='critical'||v==='gameplay'||v==='combat',source||'priority-api');}
  async function boot(){requestPersistentStorage().catch(()=>{});await registerServiceWorker();if(!isGameplayBusy())await check({force:true});}
  global.KeloUpdater=Object.freeze({check,prepareUpdate,applyUpdate,evaluateNetwork,setGameplayBusy,setNetworkPriority,getState});
  global.addEventListener('kelo:network-priority',event=>{const d=event&&event.detail||{};if(typeof d.busy==='boolean')setGameplayBusy(d.busy,d.source||'event');else if(d.priority)setNetworkPriority(d.priority,d.source||'event');});
  document.addEventListener('visibilitychange',()=>{state.network.lastProbeAt=0;if(document.visibilityState==='visible'&&!isGameplayBusy())check().catch(()=>{});});global.addEventListener('online',()=>{state.network.lastProbeAt=0;if(!isGameplayBusy())check().catch(()=>{});});global.addEventListener('offline',()=>{state.network.status='offline';state.network.reason='offline';state.network.lastProbeAt=Date.now();});global.addEventListener('pageshow',event=>{if(event.persisted&&!isGameplayBusy())check({force:true}).catch(()=>{});});
  boot().catch(error=>{state.status='error';state.lastError=String(error&&error.message||error);emit('error');});
})(window);
