create table if not exists public.equipment_items (
  id text primary key,
  player_id text not null,
  template_id text not null,
  slot text not null,
  item_level integer not null default 1 check (item_level between 1 and 9),
  quality integer not null default 1 check (quality between 1 and 9),
  grade integer not null default 1 check (grade between 1 and 9),
  base_stats jsonb not null default '{}'::jsonb,
  special_stats jsonb not null default '{}'::jsonb,
  equipped boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists equipment_items_player_idx on public.equipment_items(player_id);
create unique index if not exists equipment_items_equipped_slot_idx on public.equipment_items(player_id, slot) where equipped;

create table if not exists public.forge_history (
  id bigint generated by default as identity primary key,
  player_id text not null,
  item_id text not null,
  forge_type text not null check (forge_type in ('level','quality','grade')),
  from_tier integer not null,
  to_tier integer not null,
  chance numeric(6,2) not null,
  roll numeric(6,2),
  success boolean not null,
  cost bigint not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists forge_history_player_idx on public.forge_history(player_id, created_at desc);

alter table public.equipment_items enable row level security;
alter table public.forge_history enable row level security;

revoke all on public.equipment_items from anon, authenticated;
revoke all on public.forge_history from anon, authenticated;

comment on table public.equipment_items is 'Server-authoritative Kelo equipment. Service role only.';
comment on table public.forge_history is 'Immutable forge attempt history written by the authoritative server.';